### ISSUE TITLE
编译报错--跟protobuf相关

### ISSUE THREAD

**Issue by stevenwake** [brpc/brpc#100]
如下:
Linking protoc-gen-mcpack
src/mcpack2pb/generator.o: In function `google::protobuf::FieldDescriptor::cpp_type() const':
/usr/local/include/google/protobuf/descriptor.h:2015: undefined reference to `google::protobuf::FieldDescriptor::type() const'
src/mcpack2pb/generator.o: In function `mcpack2pb::field_to_string(google::protobuf::FieldDescriptor const*)':
/data/brpc/src/mcpack2pb/generator.cpp:53: undefined reference to `google::protobuf::FieldDescriptor::type() const'
/data/brpc/src/mcpack2pb/generator.cpp:65: undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
/data/brpc/src/mcpack2pb/generator.cpp:69: undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
src/mcpack2pb/generator.o: In function `mcpack2pb::to_mcpack_typestr(google::protobuf::FieldDescriptor const*)':
/data/brpc/src/mcpack2pb/generator.cpp:79: undefined reference to `google::protobuf::FieldDescriptor::type() const'

**Comment by stevenwake** [comment]
protobuf版本冲突，已解决

**Comment by zheng39562** [comment]
我也遇见了。问题在于：proto-dev 和 proto-compiler 的版本必须一致。
我出现的情况在：之前使用过protobuf的某个版本，导致dev 和compiler不一致。
