### ISSUE TITLE
flag 'minloglevel' was defined more than once的问题

### ISSUE THREAD

**Issue by zhaolei** [brpc/brpc#101]
背景： 项目同时 依赖 brpc 和 caffe 
问题： 
brpc依赖gflags 在src/butil/logging.cc 的130行 使用gflags的 DEFINE_int32=> minloglevel
caffe依赖的glog在的src/glog/logging.h的344行同样使用了gflags的DECLARE_int32=>minloglevel

编译没问题，运行就会报
`ERROR: flag 'minloglevel' was defined more than once (in files 'src/butil/logging.cc' and 'src/logging.cc').`

**Comment by chenzhangyi** [comment]
编译执行config_brpc.sh的时候加入 --with-glog

**Comment by zhaolei** [comment]
出了新问题 
server.cpp: In member function ‘virtual void example::EchoServiceImpl::Echo(google::protobuf::RpcController*, const example::EchoRequest*, example::EchoResponse*, google::protobuf::Closure*)’:
server.cpp:58:54: error: ‘noflush’ was not declared in this scope
                   << " to " << cntl->local_side() << noflush;
                                                      ^

**Comment by jamesge** [comment]
把noflush去掉，这个意思是“暂时先别换行并刷出日志”，但glog是不支持的，示例程序中的noflush可能没有去干净。

**Comment by kfstorm** [comment]
What if I linked glog but I don't want to use glog?
