### ISSUE TITLE
bvar::Variable 示例程序问题

### ISSUE THREAD

**Issue by machaelliu** [brpc/brpc#102]
bvar::Adder<int> count1;

count1 << 10 << 20 << 30;   // values add up to 60.
count1.expose("my_count");  // expose the variable globally
CHECK_EQ("60", bvar::Variable::describe_exposed("count1"));
my_count.expose("another_name_for_count1");  // expose the variable with another nam

上面最后两行的 “count1" 和 my_count 位置写反了。

**Comment by jamesge** [comment]
Thanks for pointing out, fixed.
