### ISSUE TITLE
LOG宏定义冲突

### ISSUE THREAD

**Issue by dl239** [brpc/brpc#103]
brpc定义了LOG宏和自己内部定义的冲突了，有好的解决方案吗

**Comment by imotai** [comment]
+1

**Comment by neverdizzy** [comment]
发生冲突的是头文件，当两个头文件都定义了同一个宏，并且两个宏定义不太一致。

**Comment by neverchanje** [comment]
有没有试过使用 ifdef undef define endif 来解决这个问题呢？
比如
```cpp
#ifdef LOG
#undef LOG
#define the logger of yourself
#endif
```

**Comment by dl239** [comment]
#define LOG(level, fmt, args...)  XXX
原来使用的log库是这种格式的，如果undef之后重新define LOG brpc就编不过了，和brpc内部是用的LOG格式不一致

**Comment by imotai** [comment]
brpc是一个基础库，log 这些通用的定义应该尽量考虑到与上层的应用冲突，不然使用的成本会变得很大

**Comment by jamesge** [comment]
LOG宏会考虑加上前缀，其他还有什么宏会冲突？

**Comment by imotai** [comment]
@jamesge  目前 发现冲突 只有LOG这个定义
