### ISSUE TITLE
使用ParallelChannel时如何集成redis、memcache以及自定义的message？

### ISSUE THREAD

**Issue by feng-y** [brpc/brpc#106]
调用CallMethod需要把不同的Request组合成一个Message，如何组装redis、memcache的Request以及Response？
另外下面两个文件是否可以开源？
baidu/rpc/redis_base.proto
baidu/rpc/memcache_base.proto

**Comment by jamesge** [comment]
调用ParallelChannel.CallMethod时并不一定需要"把不同的Request组合成一个Message"，比如广播一个request，或者基于一个request做些修改再发，都是不需要的。redis和memcache的请求比较特殊，它们只是继承了google::protobuf::Message，从而可以给CallMethod使用，但其中的字段是brpc自己添加的，所以它们和proto中的定义是不一致的，那两个proto并不存在，也不需要。一些场景下用半同步可能会更快捷。

**Comment by feng-y** [comment]
考虑一个场景，需要redis + memcache + rpc异步，是否需要组合成一个Message，然后通过CallMapper指定各个的Request？
另外如果使用继承google::protobuf::Message组合Message， 类似于下面的代码如何编写的？
::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\032baidu/rpc/redis_base.proto\022\tbaidu.rpc\032"
    " google/protobuf/descriptor.proto\"\016\n\014Red"
    "isRequest\"\017\n\rRedisResponseB\003\200\001\001", 111);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "baidu/rpc/redis_base.proto", &protobuf_RegisterTypes);

**Comment by jamesge** [comment]
redis/memcache这类message是无法组合的。你可以用半同步，或者自己把多个异步组合起来。
