### ISSUE TITLE
http client如何拿到原始响应结果

### ISSUE THREAD

**Issue by gydong** [brpc/brpc#110]
从接口上看到，获取header的方法和获取body的方法，有办法获取到整个响应的原文吗？即获取headers 和 body连在一起的原文。

**Comment by jamesge** [comment]
你要原文干嘛？

**Comment by gydong** [comment]
说来话长，我用的一个第三方模块，只接受原文。可以理解为一个函数的输入参数是原文，我理解它这么干的原因是，这个模块只考虑到了libcurl用户的使用方便。

**Comment by jamesge** [comment]
不支持。不过看起来这个函数的性能也好不到哪去，你也许考虑重新拼出一个request或response, 用[这里的函数](https://github.com/brpc/brpc/blob/master/src/brpc/details/http_message.h#L120)

**Comment by gydong** [comment]
好的，多谢解答。
