### ISSUE TITLE
建议建一个IM交流群，比如Telegram，或者google group，有利于brpc推广和细节交流

### ISSUE THREAD

**Issue by joostshao** [brpc/brpc#111]
建议建一个IM交流群，比如Telegram，或者google group，有利于brpc推广和细节交流

**Comment by jamesge** [comment]
交流群和issue的角色有所重合。另外因为问群比查文档快，所以群内大量的问题都是入门问题，达不到“交流”的效果，这也是我们在百度内的实际体会。对于brpc项目issues机制目前应该够用了。问题都可以问，无关、重合的会定期关掉。
