### ISSUE TITLE
correlation_id在扩展新协议的时候应该怎么处理

### ISSUE THREAD

**Issue by kevin-xu-158** [brpc/brpc#112]

**Comment by kevin-xu-158** [comment]
新协议里没有这个概念，该怎么处理呢

**Comment by jamesge** [comment]
那这个协议只能用连接池或短连接访问。correlation-id存在发送的socket中，response回来时取出来。比如见https://github.com/brpc/brpc/blob/master/src/brpc/policy/nshead_protocol.cpp#L394

**Comment by kevin-xu-158** [comment]
我刚才就是参照这个代码写的，这样，是不是会影响single连接的模式

**Comment by jamesge** [comment]
无法让server原样返回correlation-id，一般就无法支持单连接，因为client端不知道一个连接上同时返回的多个response该分别对应哪个request。除非response的序保证和request一样，比如redis。

**Comment by kevin-xu-158** [comment]
明白了，谢谢你啊
