### ISSUE TITLE
能否换一个角度提供延迟分位值

### ISSUE THREAD

**Issue by tjb1216** [brpc/brpc#113]
目前内置服务提供的延迟数据：latency_99表示99%的请求延迟在多长时间以内。
换个角度，如果我比较关心某个具体时间以内的延迟占比呢，比如10ms以内的请求占比是多少？
这个数据有计划提供吗？如果不能提供，我们自己在源码基础上实现的话，有什么建议？

**Comment by jamesge** [comment]
查cdf图，通过纵轴反查横轴。
典型的cdf见![img](https://github.com/brpc/brpc/blob/master/docs/images/vars_4.png)

**Comment by tjb1216** [comment]
谢谢及时回复。
这个数据不够准确吧，我们需要连续的、准确的数据，最终也会形成曲线，需要在上面添加报警。

**Comment by tjb1216** [comment]
好的，谢谢及时服务

**Comment by jamesge** [comment]
附带说一句，如果采样数据有无穷多个的话（把cdf曲线看成连续的），对应的函数是严格单调的，所以它有同样单调的反函数，f(percent)<=latency和g(latency)>=percent是等价的，其中g是f的反函数。换句话说，你们应该用业界通行的percentile，而不是自己弄个实为“percentile的反函数”的指标。

**Comment by zyearn** [comment]
如果cdf曲线是单调递增的，用一个二分搜索就可以满足这个需求。
