### ISSUE TITLE
When release the version with openucx support?

### ISSUE THREAD

**Issue by wormwang** [brpc/brpc#116]
feature list: rdma support via openucx (will be opensourced)
When release the version with openucx support?
We need bprc to support RDMA.

**Comment by jamesge** [comment]
the rdma code is not merged yet.

**Comment by gydong** [comment]
@jamesge 
1. 现在rdma 的进度如何，是否有望在最近merge到master分支？
2. 如果不能merge的话，能先扫盲一下，rdma 的具体features吗？以及未来它的一些典型使用场景。

**Comment by jamesge** [comment]
1. 还在内部使用和改进中
2. 会merge。rdma主要用在高性能存储和计算的场景，对吞吐和延时的要求比较高
