### ISSUE TITLE
redis cluster access

### ISSUE THREAD

**Issue by seiyap70** [brpc/brpc#118]
Could please someone tell me how to access redis cluster by brpc?

**Comment by jamesge** [comment]
https://github.com/brpc/brpc/blob/master/docs/cn/redis_client.md#访问redis集群

**Comment by seiyap70** [comment]
I have read it,  but don't get it. more detail please?

**Comment by jamesge** [comment]
你说的cluster是特指redis cluster吧，这个协议是可以基于基本的redis协议封装出来的，但目前brpc并不直接支持。你可以用专门的proxy做这个事情。

**Comment by seiyap70** [comment]
哦，明白了，brpc支持的集群是指每个Redis作为一个单独的节点，然后使用一致性哈希或者MD5映射分配到不同的节点。

**Comment by shanghx** [comment]
什么时候可以支持redis cluster呀，或者考虑支持redis cluster吗？

**Comment by shanghx** [comment]
> 你说的cluster是特指redis cluster吧，这个协议是可以基于基本的redis协议封装出来的，但目前brpc并不直接支持。你可以用专门的proxy做这个事情。
什么时候可以支持redis cluster呀，或者考虑支持redis cluster吗？
