### ISSUE TITLE
bvar<int> 在页面显示值不对问题

### ISSUE THREAD

**Issue by songguiquan** [brpc/brpc#119]
g_error_count << 1; 操作，打印日志g_error_count .get_value() 显示的是1。但是页面上为什么显示的是0

**Comment by songguiquan** [comment]
在.h 文件 定义 static bvar::Adder<int> g_error_count("error_count")，改成在.cpp 文件定义 bvar::Adder<int> g_error_count("error_count") 就有数据了，这个是为什么啊？

**Comment by jamesge** [comment]
定义在头文件中的static变量在每个包含它的Compilation unit中都有一份，各用各的了。虽然这里没有链接错误，但bvar多半是会报重名的fatal错误的，可能你没注意。
