### ISSUE TITLE
能不能加上ice的性能对比

### ISSUE THREAD

**Issue by Nocturnana** [brpc/brpc#12]

**Comment by jamesge** [comment]
这个跨平台框架在互联网公司似乎用的很少，我们近期也不太可能重做性能测试（因为需要借用很多物理机器）。你如果使用ICE的话，其实可以自己做做对比。未必要像benchmark中那样特别严格，根据自己的场景，写一些demo code对比一下应该就差不多了。

**Comment by Nocturnana** [comment]
好的 谢谢 ！主要是ice是我用过性能最好的rpc框架，和thrift 之类的对比还是比较欺负人的
