### ISSUE TITLE
bthread_id_join 与 bthread_join 的区别

### ISSUE THREAD

**Issue by Tsrign** [brpc/brpc#121]
baidu::rpc::CallId callid = cntl->call_id();
queryServiceStub.query_batch_khash(cntl, request, response, baidu::rpc::NewCallback(OnRPCDone, cntl, request, response));

        1.  baidu::rpc::Join(callid);   OK
        2. bthread_id_join(callid); OK
        3.  bthread_id_join(bthread_id_t{callid.value});  OK
        4. bthread_join(callid.value, NULL); NOT OK
      
因为我的实现场景，需要在外层实现异步 io 和 cpu 计算的半同步，但是遇到一点问题，如上，经过测试 1、2、3对异步 IO阻塞是有效，能保证异步 IO以及回调执行完成， 但是4却没什么效果，辛苦给指点一下。

**Comment by Tsrign** [comment]
最终我想通过 bthread_list_join 函数实现 io 和 cpu 的半同步。 bthread_list_join 如同上述测试bthread_join 都是没能达到目标，不知道哪里出问题了。

**Comment by jamesge** [comment]
bthread_id_join的参数是bthread_id_t, bthread_join的参数是bthread_t, 这是完全不同的两个东西。

**Comment by Tsrign** [comment]
你好，我查看bthread_id_t和 bthread_t 类型定义，我觉得 bthread_id_t 与 bthread_t 之间应该可以互相转化。
callid 是 badiu::rpc::Callid 类型，由 cntl 返回的。
 3. bthread_id_join(bthread_id_t{callid.value});  OK  能等待 bthread 完成
 4. bthread_join(callid.value, NULL); NOT OK  未能等待 bthread 完成

**Comment by jamesge** [comment]
bthread_t是对应一个bthread，bthread_id_t是对应一个bthread_id，这两个东西完全没有关系。不是说类型兼容就可以“互相转化”，何况你还是取callid的内部字段value出来。
