### ISSUE TITLE
server cancelation功能无效

### ISSUE THREAD

**Issue by tjb1216** [brpc/brpc#122]
// If true, indicates that the client canceled the RPC or the connection has
    // broken, so the server may as well give up on replying to it.  The server
    // should still call the final "done" callback.
    bool IsCanceled() const;

    // Asks that the given callback be called when the RPC is canceled or the
    // connection has broken.  The callback will always be called exactly once.
    // If the RPC completes without being canceled/broken connection, the callback
    // will be called after completion.  If the RPC has already been canceled/broken
    // when NotifyOnCancel() is called, the callback will be called immediately.
    //
    // NotifyOnCancel() must be called no more than once per request.
    void NotifyOnCancel(google::protobuf::Closure* callback);

如注释所说，当客户端取消的时候，IsCanceled()返回true，NotifyOnCancel注册的回调函数却永远不执行（客户端没有取消，成功返回也不会执行）。

**Comment by jamesge** [comment]
这个接口是不跨client/server的，client端调用cancel并不会**直接**导致server端的IsCancel为true。server端的IsCanceled只是针对连接断开，你碰到的情况可能是恰好client端关闭了连接，被server发现了。但你的描述有问题的地方在于，如果IsCanceled为true，NotifyOnCancel注册时的回调是会被调用的。

**Comment by tjb1216** [comment]
// Asks that the given callback be called when the RPC is canceled or the
// connection has broken. 
我的理解是：客户端取消rpc或者断开连接时，服务端会调用注册的回调。
如果我理解不对的话，NotifyOnCancel的用途是什么？

**Comment by jamesge** [comment]
这个注释是从通用的角度说的，但"when the rpc is canceled"这条并未实现。

**Comment by tjb1216** [comment]
OK，测试显示，确实是在断开连接时会触发执行。
但只对服务端发出的同步请求生效，如果服务端发出的是异步请求，即使客户端连接断开，服务端的请求还是会正常返回，且NotifyOnCancel注册的回调函数也是在服务端请求正常完成之后再执行的。
请问这是正常的逻辑吗？为什么同步异步会有差异？

**Comment by jamesge** [comment]
”服务端发出的请求" ?

**Comment by tjb1216** [comment]
是，我们想要实现的是一个链路取消的功能，在一个请求链路中，一个服务端也会是下一个服务端的客户端，会往下一个节点发请求，如A-->B-->C；B是A的服务端，也是C的客户端。那么当A的请求取消的时候，我们想要B到C的同一个链路的请求也取消，避免浪费资源。
从目前的测试结果来看，B上NotifyOnCancel注册的回调函数只在两种情况下执行：
1：B发给C的请求顺利完成；
2：A发给B的请求达到超时时间。
你之前说的A到B的连接断开也不会触发。

**Comment by tjb1216** [comment]
是，我们想要实现的是一个链路取消的功能，在一个请求链路中，一个服务端也会是下一个服务端的客户端，会往下一个节点发请求，如A-->B-->C；B是A的服务端，也是C的客户端。那么当A的请求取消的时候，我们想要B到C的同一个链路的请求也取消，避免浪费资源。
从目前的测试结果来看，B上NotifyOnCancel注册的回调函数只在两种情况下执行：
1：B发给C的请求顺利完成或超时；
2：A断开到B的连接，A发给B的请求达到超时时间；

**Comment by tjb1216** [comment]
这个注释是从通用的角度说的，但"when the rpc is canceled"这条并未实现。
cancel为什么不实现呢，是有难度还是觉得意义不大？

**Comment by jamesge** [comment]
你说的两个现象是符合预期的。事实上超时和NotifyOnCancel也没有关系，可能是因为client端用的是连接池或短链接，超时后会关闭连接，从而触发了NotifyOnCancel。本质上还是只有连接断开或当前请求处理结束会触发server端的NotifyOnCancel。不实现的原因在于RPC的大部分应用场景中，单个请求的代价都不是很大，所以server cancelation的应用场景比较少，真正特别需要这个功能的产品会自己做类似的功能。另一方面cancel本身要耗费一个RPC在一些场景中可能是负面作用，这里需要一些优化技巧。只支持原地cancel还是能跑到另一台server上去做cancel (cross-server cancelation in backup requests)，这个差别也很大。最后不同的协议支持跨机器cancel的方式可能是不同的，要根据协议特点对应设计，比较麻烦。综合这些因素就没有做跨机器的cancel。

**Comment by tjb1216** [comment]
了解了，谢谢及时回复，32个赞！
