### ISSUE TITLE
event_dispatcher.cpp中的volatile变量_stop

### ISSUE THREAD

**Issue by gaodq** [brpc/brpc#123]
https://github.com/brpc/brpc/blob/83c55dceb2caa6bf2f7e8d0b6afaa1a983464646/src/brpc/event_dispatcher.cpp#L204
请问这里为什么要用volatile，而不用atomic，这样原子性不会有问题吗

**Comment by jamesge** [comment]
这个变量原子与否是不重要的，它只是一个退出标识。volatile只是避免编译器做过度优化。
