### ISSUE TITLE
Missing file to compile brpc in Mac OS

### ISSUE THREAD

**Issue by WangJiannan** [brpc/brpc#124]
butil/mac/ folder is not exist in the source code

**./test/shared_memory_unittest.cc:#include "butil/mac/scoped_nsautorelease_pool.h"**
./src/butil/strings/sys_string_conversions_mac.mm:#include "base/strings/sys_string_conversions.h"
./src/butil/strings/sys_string_conversions_mac.mm:#include "base/mac/foundation_util.h"
./src/butil/strings/sys_string_conversions_mac.mm:#include "base/mac/scoped_cftyperef.h"
./src/butil/strings/sys_string_conversions_mac.mm:#include "base/strings/string_piece.h"
**./src/butil/time/time_mac.cc:#include "butil/mac/mach_logging.h"
./src/butil/time/time_mac.cc:#include "butil/mac/scoped_cftyperef.h"
./src/butil/time/time_mac.cc:#include "butil/mac/scoped_mach_port.h"
./src/butil/files/file_path.cc:#include "butil/mac/scoped_cftyperef.h"
./src/butil/file_util_posix.cc:#include "butil/mac/foundation_util.h"**
./src/butil/threading/platform_thread_mac.mm:#include "base/threading/platform_thread.h"
./src/butil/threading/platform_thread_mac.mm:#include "base/lazy_instance.h"
./src/butil/threading/platform_thread_mac.mm:#include "base/logging.h"
./src/butil/threading/platform_thread_mac.mm:#include "base/mac/mach_logging.h"
./src/butil/threading/platform_thread_mac.mm:#include "base/threading/thread_id_name_manager.h"
./src/butil/threading/platform_thread_mac.mm:#include "base/tracked_objects.h"
./src/butil/file_util_mac.mm:#include "base/file_util.h"
./src/butil/file_util_mac.mm:#include "base/basictypes.h"
./src/butil/file_util_mac.mm:#include "base/files/file_path.h"
./src/butil/file_util_mac.mm:#include "base/mac/foundation_util.h"
./src/butil/file_util_mac.mm:#include "base/strings/string_util.h"
./src/butil/file_util_mac.mm:#include "base/threading/thread_restrictions.h"

**Comment by jamesge** [comment]
Use a linux distro right now. Mac is not supported yet.

**Comment by qiuxiafei** [comment]
Any plan on mac ?

**Comment by jamesge** [comment]
Will support Mac gradually

**Comment by jamesge** [comment]
Missing files are added in [this commit](https://github.com/brpc/brpc/commit/3d9a6ec81b74c875464fab1a6ab2ebf6081cadaa), however the MAC build is not complete yet, we're still working on adaptation for futex and epoll.
