### ISSUE TITLE
名字服务中file://协议相关问题

### ISSUE THREAD

**Issue by gydong** [brpc/brpc#126]
担心文件修改到中间状态的时候，被brpc监测到并加载了不完整的内容，这个问题怎么解决？是用mv命令覆盖旧文件吗？

**Comment by jamesge** [comment]
是

**Comment by tjb1216** [comment]
file://<file-path>  请问这个file-path要怎么填？
启动命令：./client -server=file:///ads-backend/consul/template/backup/sag_brpc_test
报错：Invalid address=`file:///ads-backend/consul/template/backup/sag_brpc_test'
看代码好像是不能有‘/’

**Comment by tjb1216** [comment]
file:// 请问这个file-path如果是绝对路径要怎么填？
启动命令：./client -server=file:///ads-backend/consul/template/backup/sag_brpc_test -load_balancer=rr
报错：Fail to open `ads-backend/consul/template/backup/sag_brpc_test': No such file or directory [2]

**Comment by tjb1216** [comment]
@jamesge

**Comment by jamesge** [comment]
@tjb1216 https://github.com/brpc/brpc/commit/6c34eb537f453207238047036133fe9dd74ae58b
