### ISSUE TITLE
后续有计划支持opentracing么

### ISSUE THREAD

**Issue by xmm1989218** [brpc/brpc#127]
后续有计划支持opentracing么

**Comment by jamesge** [comment]
opentracing统一数据格式了么？似乎并没有。

**Comment by xmm1989218** [comment]
额 是没有 有没有可能接入比较知名的 比如zipkin之类的

**Comment by jamesge** [comment]
如果有具体的接入spec（数据格式为主），我们可以评估一下接入的难度。这块如果需求比较多样（我看到的比如zipkin, aws x-ray, 国内xx云），也许会加个通用的扩展接口让用户自己扩展。

**Comment by xmm1989218** [comment]
对于存在很多服务相互调用的情况 比如广告系统中的 AS/BS/UFS/PB 一个调用另外一个的 百度的经验是怎么去处理服务监控 排查问题的 只是单独分别做监控告警么 还是说链路跟踪 不是做在rpc框架层面 做在业务层面？

**Comment by xmm1989218** [comment]
- [ ]
