### ISSUE TITLE
Brpc cannot link on Ubuntu LTS 16.04

### ISSUE THREAD

**Issue by beenchaos** [brpc/brpc#13]
Linking echo_client
../..//output/lib/libbrpc.a(channel.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > butil::class_name_str<brpc::Describable>(brpc::Describable const&)':
/home/brpc/brpc/./src/butil/class_name.h:52: undefined reference to `butil::demangle(char const*)'
../..//output/lib/libbrpc.a(load_balancer.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > butil::class_name_str<brpc::NonConstDescribable>(brpc::NonConstDescribable const&)':
/home/brpc/brpc/./src/butil/class_name.h:52: undefined reference to `butil::demangle(char const*)'
/home/brpc/brpc/./src/butil/class_name.h:52: undefined reference to `butil::demangle(char const*)'
../..//output/lib/libbrpc.a(socket.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > butil::class_name_str<brpc::Describable>(brpc::Describable const&)':
/home/brpc/brpc/./src/butil/class_name.h:52: undefined reference to `butil::demangle(char const*)'
../..//output/lib/libbrpc.a(socket.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > butil::class_name_str<brpc::SocketUser>(brpc::SocketUser const&)':
/home/brpc/brpc/./src/butil/class_name.h:52: undefined reference to `butil::demangle(char const*)'
../..//output/lib/libbrpc.a(socket.o):/home/brpc/brpc/./src/butil/class_name.h:52: more undefined references to `butil::demangle(char const*)' follow
collect2: error: ld returned 1 exit status
Makefile:34: recipe for target 'echo_client' failed
make: *** [echo_client] Error 1

**Comment by chenzhangyi** [comment]
Looks like it's duplicated with https://github.com/brpc/brpc/issues/6.  Please try update brpc.
