### ISSUE TITLE
brpc 方法级别并发限制存在bug，里面引用计数有问题

### ISSUE THREAD

**Issue by imotai** [brpc/brpc#130]
我把某个方法设置最大并发为8，在发大压力情况下10个请求线程，服务端返回到达并发上限，到这里是没问题，但是请求停止后，再简单发给请求给那个方法还是出现下面问题
```
W 11/24 16:49:40.285062 94781  request error. [E2004][172.27.128.35:5527][E2004]Reached xxxxxxxxx's max_concurrency=8 [R1][E2004][172.27.128.35:5527][E2004]Reached xxxxxx's max_concurrency=8
```
@jamesge 能否一起看看能不能解决这个问题，我这边还有现场

**Comment by imotai** [comment]
不好意思，刚才进程被kill掉了， 我又运行了一下，虽然没有完全复现 ，但是已经复现一部分了， 我保持发的压力不变，运行一段时间后qps从6万一下降到3千，processing 在8 和7之间变化，应该是已经出问题了
@jamesge

**Comment by imotai** [comment]
[](url)
<img width="810" alt="2017-11-24 5 50 28" src="https://user-images.githubusercontent.com/8623385/33204928-0f8dd632-d140-11e7-8b42-e8c0c5391989.png">

**Comment by imotai** [comment]
<img width="824" alt="2017-11-24 5 53 16" src="https://user-images.githubusercontent.com/8623385/33205013-61d174a8-d140-11e7-9550-c312eea98585.png">

**Comment by imotai** [comment]
Server done->Run()是肯定调用了的， 出问题协议是sofa-pbrpc, 换成brpc协议同样的方式没有出问题。

**Comment by jamesge** [comment]
这两个协议这部分代码基本上是一样的。你可以再测试一下hulu_pbrpc这个协议有没有问题，以及client完全退出后，processing能否归0.

**Comment by imotai** [comment]
我这边没法测试hulu_pbrpc,  我是直接把client kill -9 , 然后就出问题了， 应该还是服务端的问题

**Comment by jamesge** [comment]
qps下降不能说明一定有问题，也可能是server不停在做的事情就是变慢了。看下这个“以及client完全退出后，processing能否归0.”

**Comment by imotai** [comment]
我看了出问题时候的cpu, 也下降了相应的倍数，而且我对server很清楚，不可能做其他事情
