### ISSUE TITLE
redis client 不支持subscribe 

### ISSUE THREAD

**Issue by tjb1216** [brpc/brpc#132]
测试发现redis client不支持subscribe功能，请问后续是否有计划支持，是否考虑过如何实现？

**Comment by jamesge** [comment]
pub/sub是纯server端功能，肯定是支持的。

**Comment by tjb1216** [comment]
以下是运行example下的redis_client，收到publish消息后的报错信息：
redis 127.0.0.1:6379> subscribe test_channel
["subscribe", "test_channel", (integer) 1]
redis 127.0.0.1:6379> WARNING: Logging before InitGoogleLogging() is written to STDERR
W1127 12:17:44.279266 26746 redis_protocol.cpp:69] No corresponding PipelinedInfo in socket
E1127 12:17:44.279451 26746 input_messenger.cpp:87] Fail to parse response from 127.0.0.1:6379 by redis at client-side
W1127 12:17:44.279470 26746 input_messenger.cpp:249] Close fd=3 SocketId=0@127.0.0.1:6379@26437: absolutely wrong message
I1127 12:17:44.380089 26752 socket.cpp:2091] Checking SocketId=0@127.0.0.1:6379
I1127 12:17:44.380267 26746 socket.cpp:2153] Revived SocketId=0@127.0.0.1:6379

**Comment by gydong** [comment]
@jamesge ：我看了一下源码，猜测了一下原因，不知道是否正确。现在实现的PipelinedInfo应该是基于一个假设：redis请求message和redis响应message是一一对应的。而redis subscribe命令，打破了这个假设，该命令只有一个请求message，而却可以有无限多个响应message，所以造成了client无法正常工作。

**Comment by jamesge** [comment]
如果pub/sub是这么工作的，那么目前的代码确实是不行的。

**Comment by gydong** [comment]
@jamesge 那brpc会有支持subscribe命令的计划吗？ ^_^

**Comment by gydong** [comment]
@jamesge ping

**Comment by jamesge** [comment]
这要增加专门的编程接口，我们可能目前不会做这个事情。不过你可以自己试试，一种方法是在controller中可设置redis的message handler（一般要引用计数），碰到被pub的message就扔给那个handler。

**Comment by gydong** [comment]
收到，多谢答复。
