### ISSUE TITLE
支持https client

### ISSUE THREAD

**Issue by songguiquan** [brpc/brpc#136]
brpc 支持https 么?

**Comment by songguiquan** [comment]
如果支持的话，是不是要设置什么参数？

**Comment by jamesge** [comment]
https://github.com/brpc/brpc/blob/master/docs/cn/http_service.md#%E5%BC%80%E5%90%AFhttps

**Comment by seiyap70** [comment]
支持客户端的https吗

**Comment by jamesge** [comment]
client端的https年底前不出意外会加上。

**Comment by jamesge** [comment]
Already supported. The remaining issue was stated in #325
