### ISSUE TITLE
bvar_dump_interval无效

### ISSUE THREAD

**Issue by tjb1216** [brpc/brpc#139]
bvar::LatencyRecorder

专用于计算latency和qps的计数器。只需填入latency数据，就能获得latency / max_latency / qps / count。统计窗口是最后一个参数，不填为bvar_dump_interval（这里没填）。

文档里面说指定bvar_dump_interval后，能获得指定时间窗口内的平均值，但是测试发现不管是通过http访问还是导出到文件的方式，看到的都是当时的值。
测试用例：设定bvar_dump_interval为10s，在10s内不停变换客户端发送的qps，如前2s为1，中间5s为100，后面3s为1000，导出的文件里面看到的qps是1000.
通过阅读源码发现，取的应该是时间窗口内的平均值才对。
求解惑？

**Comment by tjb1216** [comment]
@jamesge

**Comment by jamesge** [comment]
LatencyRecorder中的qps比较特殊，是一个PassiveStatus（调用一个回调获得数值，非自身统计），为了在内置界面以1秒精度显示，qps默认是取上一秒的均值。反之如果是原生统计的话，内置界面中窗口总是1秒，dump出来的窗口是-bvar_dump_interval。
dump出来的值一般会被监控系统采集，从"天"这个尺度来说，每10秒取最后一秒也是一种有效的采样。
