### ISSUE TITLE
EpollThread 和 EventDispatcher

### ISSUE THREAD

**Issue by gydong** [brpc/brpc#140]
从源码看EpollThread和EventDispatcher两个类的设计相似，没理解为什么要同时支持着两个相似的工具类，而不是合并成一个。他们之间有着什么样的区别呢？

**Comment by jamesge** [comment]
这两个类除了都有epoll_wait其实没什么共同点？

**Comment by gydong** [comment]
@jamesge 从使用场景上讲，他们有着怎样的区别呢？ EventDispatcher专门用于socket相关的事件管理，而EpollThread用于其它事件管理，是这么理解吗？

**Comment by gydong** [comment]
@jamesge 求解惑，小白今晚要失眠。。。

**Comment by jamesge** [comment]
EventDispatcher是brpc中转发所有socket读写事件的类。EpollThread是bthread中实现与fd相关的几个函数用到的类。它们确实有共同点就是用到了epoll_wait，没有太多可抽象或复用的。当然硬是要全面地封装一下epoll也是可以的，那就是libevent, libev这些库干的事情了。

**Comment by gydong** [comment]
明白了，多谢解答。

**Comment by condy0919** [comment]
EpollThread 和它相关的只有 `bthread_timed_wait` 相关的函数，似乎都与 `tcp_connect` 这个函数相关。而这个函数 brpc 代码中基本没怎么使用到，除了自己创建 bthread 然后 `bthread_connect()` 外应该都用不到了吧？  我也是刚开始看 brpc 源码。

**Comment by chenBright** [comment]
> EpollThread 和它相关的只有 `bthread_timed_wait` 相关的函数，似乎都与 `tcp_connect` 这个函数相关。而这个函数 brpc 代码中基本没怎么使用到，除了自己创建 bthread 然后 `bthread_connect()` 外应该都用不到了吧？ 我也是刚开始看 brpc 源码。

是的，就是上面提到的"fd相关的几个函数用到"。
