### ISSUE TITLE
添加文件 src/butil/config.h  的原因是什么

### ISSUE THREAD

**Issue by dhx1989** [brpc/brpc#141]
想问下config_brpc.sh 中生成src/butil/config.h文件的原因是什么？ 
通过CXXFLAGS定义宏BRPC_WITH_GLOG会有什么问题吗？

**Comment by jamesge** [comment]
支持glog是在运行config_brpc.sh加上--with-glog

**Comment by dhx1989** [comment]
直接通过CXXFLAGS -Dxxx 会有什么问题吗？

**Comment by chenzhangyi** [comment]
定义CXXFLAGS只当前project有效，对logging.h会同样被外部用户引用， 要保证所有地方看到的行为都是一致的， 只能把宏放在头文件中.

**Comment by dhx1989** [comment]
明白，谢谢啦！
