### ISSUE TITLE
bthread 及读写锁问题

### ISSUE THREAD

**Issue by machaelliu** [brpc/brpc#142]
请教两个问题：
1、服务端需要单开一个线程从其他地方更新数据，这个新线程是需要用 bthread_start 还是用系统原有的 pthread_create ?
2、使用 bthread 读写锁时，报 undefined reference to `bthread_rwlock_init'，查了一下源码，没有这个函数定义，怎么解决？

**Comment by jamesge** [comment]
1.都可以。2.没有实现，一般来说读写锁的使用场景也很少。

**Comment by chenguangpeng1** [comment]
@jamesge  1. 在读多写少的时候 确实需要读写锁  2 读写锁没有实现的原因是什么？

**Comment by chenguangpeng1** [comment]
@jamesge  thanks

**Comment by kimlongli** [comment]
请问btrehad里面可以直接用pthtread_rwlock邪猎函数吗
