### ISSUE TITLE
关于socket pool

### ISSUE THREAD

**Issue by cool-colo** [brpc/brpc#144]
背景：项目里用brpc做为client向http server并发请求， 连接方式为pooled, 由于并发量超过100， 测试过程中发现client会不停的创建连接和关闭连接， 于是将max pool size改大至500， 但发现稳定的连接数还是无法接近500， 不断的有连接被server端关闭（已经开启http keep alive)。

问题：上面这种情况有没有可能是socket pool的实现方式导致，即不停的对vector pop_back和push_back, 导致vector中最先push_back进去的某接链接得不到使用， 最终被client或server端的idle timeout干掉。   

想法：
1. 改成队列是否合适？  需要的时候从一边取， 归还的时候放另一边。 保证所有链接都会被使用。
2. brpc很多地方都是无锁的， 这个是不是可以用一读一写的无锁队列 + 两把锁 实现。

有哪里说的不对的地方请大神们见谅哈。。

**Comment by jamesge** [comment]
1. 不合理。那样只要一个连接被创建出来，就很难被删了。因为只要连接数小于idle_timeout_sec * QPS，所有的连接就会在idle_timeout_sec内被轮转到，从而不会闲置。
2. 也就不用讨论了。

client和server的并发连接数，在pooled的前提下，主要是取决于QPS * latency，不是某个选项能决定的。max_pool_size只是限制了client和server间的最大连接数。关闭频率不是特别高的话，其实是不太用关注的。如果server不是brpc，可以去看看本身有什么关闭策略。

**Comment by gydong** [comment]
@cool-colo 请教一下，设置为500的时候还出现这个现象，其直接原因可以理解为流量不均衡造成的吗？即流量在某个时间点把连接池撑大（没有大到500），随后的一段时间内，流量一直处于低水位。

**Comment by cool-colo** [comment]
@gydong 应该是流量不均造成的。  服务器端为HAProxy, connection idle timeout为1秒， 如果流量波动周期为2秒的话，估计就会引发反复创建和关闭连接。
@jamesge 谢谢回复， 我让服务器端发idle timeout 延长一点试试看， 目前有0.5%流量因为connection timeout(E110)损失了。

**Comment by jamesge** [comment]
1秒有点太短了，如果对idle的理解是一致的，我觉得至少10秒以上。这应该是个不太触发的机制，否则server端会有大量TIME_WAIT端口。

**Comment by bozhbo** [comment]
问下，使用baidu_std时设置了options.connection_type = "pooled"; 但是在大并发的情况下容易出现[E112]Not connected to 10.0.0.1:8000 yet，应该是socket被关闭了，导致消息在一段时间消息发送不成功，baidu_std协议能使用pooled吗？

**Comment by jamesge** [comment]
baidu_std可以用pooled，那个日志说明那台机器在被健康检查，可以翻翻日志中有没有Checking开头的
