### ISSUE TITLE
brpc streaming方式接收不到完整数据

### ISSUE THREAD

**Issue by dl239** [brpc/brpc#147]
用brpc streaming方式发送数据时接收方接收到的数据不完整
发送方如果发送完数据立马调用StreamClose，接收方没有接收到最后的数据就回调on_closed函数了，并打出如下warning
W1205 15:09:34.991225 28945 src/brpc/input_messenger.cpp:213] Fail to read from fd=11 SocketId=384@xxxx:56410@9991: Connection reset by peer

如果发送方发送完数据sleep一会再调用StreamClose就没问题

> Both sides |on_closed| would be notifed after all the pending buffers have been  received

看文档说接收方接收完数据才调用on_closed

**Comment by chenzhangyi** [comment]
你这个问题应该是发送端进程提前退出导致的, 不然收到的是Got EOF, 而不是Connection reset. 可以试下StreamClose之后再sleep一会， 应该也是类似的效果.

**Comment by dl239** [comment]
发送端进程没有提前退出，发送端是一个serve
调用StreamClose之后sleep正常了。但是试了下把发送逻辑放到一个大括号作用域里，在作用域外面sleep，问题依旧存在。怀疑是Channel,Controller或者是stub等对象析构之后就有问题了
@chenzhangyi

**Comment by dl239** [comment]
排查了下是由Channel析构导致的，除了sleep有其他的解决方案吗

**Comment by gydong** [comment]
可以设置一个gflag来work around，好像叫-defer_close_second。不过我也不理解为什么析构立即引起close，应该等pending事件处理完才close吧？

**Comment by dl239** [comment]
@gydong 简单看了下defer_close_second的实现原理是延时释放，和sleep差不多，如果设置了这个gflag所有的connection都得延时释放
应该是等接收方消费掉所有数据才close，或者close掉不影响接收方消费数据

**Comment by dl239** [comment]
@jamesge 求指导

**Comment by chenzhangyi** [comment]
本地尝试了发完立即close stream并且析构channel， 并没有复现这个场景。如果方便的还麻烦贴上你的测试代码， 并且说明下测试环境(物理机/虚拟机, server/client延迟)之类的。

**Comment by dl239** [comment]
`#include <gflags/gflags.h>
#include <butil/logging.h>
#include <brpc/channel.h>
#include <brpc/stream.h>
#include "echo.pb.h"

DEFINE_bool(send_attachment, true, "Carry attachment along with requests");
DEFINE_string(connection_type, "", "Connection type. Available values: single, pooled, short");
DEFINE_string(server, "0.0.0.0:8001", "IP Address of server");
DEFINE_int32(timeout_ms, 100, "RPC timeout in milliseconds");
DEFINE_int32(max_retry, 3, "Max retries(not including the first RPC)");

int main(int argc, char* argv[]) {
    // Parse gflags. We recommend you to use gflags as well.
    GFLAGS_NS::ParseCommandLineFlags(&argc, &argv, true);

    // A Channel represents a communication line to a Server. Notice that
    // Channel is thread-safe and can be shared by all threads in your program.
    brpc::Channel channel;

    // Initialize the channel, NULL means using default options.
    brpc::ChannelOptions options;
    options.protocol = brpc::PROTOCOL_BAIDU_STD;
    options.connection_type = FLAGS_connection_type;
    options.timeout_ms = FLAGS_timeout_ms/*milliseconds*/;
    options.max_retry = FLAGS_max_retry;
    LOG(ERROR) << "server:" << FLAGS_server.c_str();

    if (channel.Init(FLAGS_server.c_str(), NULL) != 0) {
        LOG(ERROR) << "Fail to initialize channel";
        return -1;
    }

    // Normally, you should not call a Channel directly, but instead construct
    // a stub Service wrapping it. stub can be shared by all threads as well.
    example::EchoService_Stub stub(&channel);
    brpc::Controller cntl;
    brpc::StreamId stream;
    if (brpc::StreamCreate(&stream, cntl, NULL) != 0) {
        LOG(ERROR) << "Fail to create stream";
        return -1;
    }
    LOG(INFO) << "Created Stream=" << stream;
    example::EchoRequest request;
    example::EchoResponse response;
    request.set_message("I'm a RPC to connect stream");
    stub.Echo(&cntl, &request, &response, NULL);
    if (cntl.Failed()) {
        LOG(ERROR) << "Fail to connect stream, " << cntl.ErrorText();
        return -1;
    }
    FILE* file = fopen("test.txt", "rb");
    if (file == NULL) {
        LOG(ERROR) << "Fail to open file";
        return -1;
    }
    uint32_t stream_read_block_size = 1024;
    char buffer[stream_read_block_size];
    while (true) {
        size_t len = fread(buffer, 1, stream_read_block_size, file);
        butil::IOBuf data;
        data.append(buffer, len);
        while (true) {
            int ret_code = brpc::StreamWrite(stream, data);
            if (ret_code == 0) {
                break;
            } else if (ret_code == EAGAIN) {
                if (brpc::StreamWait(stream, NULL) == EINVAL) {
                    LOG(ERROR) << "stream has closed";
                    return -1;
                }
            } else {
                LOG(ERROR) << "stream write failed";
                return -1;
            }
        }
        if (feof(file)) {
            LOG(INFO) << "end of file";
            break;
        }
    }
    fclose(file);
    brpc::StreamClose(stream);
    LOG(INFO) << "EchoClient is going to quit";
    return 0;
}`

**Comment by chenzhangyi** [comment]
你这个不是关闭channel了，而是进程退出. 进程退出的时候还在用户buffer中的数据会丢失.

**Comment by jamesge** [comment]
@dl239 你上面不是说“发送端是一个server”么

**Comment by dl239** [comment]
我这边实际环境中发送端和接收端都是一个server，不会退出进程，昨天那个例子是为了方便在example下改的，忽略了client进程退出这一点，抱歉。我又改了下，和上面的client有两点不同
1、client发送完之后一直sleep，保证进程不会退出
2、将发送逻辑用大括号包起来，再现channel析构的场景
@chenzhangyi @jamesge 
[client.txt](https://github.com/brpc/brpc/files/1573951/client.txt)

**Comment by chaoqizhao** [comment]
请问博主这个问题解决了吗
