### ISSUE TITLE
cache locality 

### ISSUE THREAD

**Issue by gydong** [brpc/brpc#148]
[文档](https://github.com/brpc/brpc/blob/master/docs/cn/io.md)中，有这么一段话：“在背后，EDISP把所在的pthread让给了新建的bthread，使其有更好的cache locality，可以尽快地读取fd上的数据。”  

@jamesge 没理解这里的“更好的cache locality”是怎么获得到的？监听到一个fd可读的情况下，数据就已经进入cache了吗？

**Comment by gydong** [comment]
@chenzhangyi  @jamesge 求解惑。

**Comment by jamesge** [comment]
这里的主要作用是让那个被建立的线程尽快运行，而不用等待被调度。cache locality算是加分项，但不是最重要的。

**Comment by gydong** [comment]
嗯，但是没理解这里的cache locality是怎么理解。具体地讲，没理解什么数据已经在cache中可用了？

**Comment by gydong** [comment]
@jamesge ping

**Comment by gydong** [comment]
戈神哪里去liao？

**Comment by gydong** [comment]
@jamesge ping

**Comment by jamesge** [comment]
线程跳转越少，locality就会更好，就是这个正向关系。也未必是内核中的数据，框架本身探测事件和读取事件，也有重叠的内存区域。
