### ISSUE TITLE
新人培训宝典的内容什么时候能开放出来？

### ISSUE THREAD

**Issue by youngkan** [brpc/brpc#149]
你好，我是rpc的新人，想对着文档学习这块内容，觉得新人培训宝典应该有很多基础的东西，想了解一下，不知道这块的内容什么时候能开源出来呢？

**Comment by jamesge** [comment]
主页有个ppt

**Comment by youngkan** [comment]
具体在哪，能把链接发下么？多谢了

**Comment by icylord** [comment]
https://github.com/brpc/brpc/blob/master/docs/cn/brpc_intro.pptx @youngkan
