### ISSUE TITLE
cannot access "https://svn.baidu.com/com-test/trunk/public/rpc-perf/“

### ISSUE THREAD

**Issue by huaqiangwang** [brpc/brpc#15]
Dear Maintainer, 

**“测试代码：https://svn.baidu.com/com-test/trunk/public/rpc-perf/”**

I cannot access the url "https://svn.baidu.com/com-test/trunk/public/rpc-perf/" from a public network, can you fix this?

**Comment by jamesge** [comment]
The code relates many internal infra that are not opensourced right now, especially toolings to remotely control testing machines. The perf code will not be opensourced in near future and the link will be removed.
