### ISSUE TITLE
如何确保dummy server启动起来呢？

### ISSUE THREAD

**Issue by xiaohei520321** [brpc/brpc#150]
比如我指定了11111端口用于brpc的内置服务，用bvar来做一些监控和统计类的工作。
但是如果服务器上是混布（nginx，redis，server等放在一台机子上），每个服务新建tcp连接的时候，都会随机的开一个端口出来。如果我的server在启动时，刚好nginx新建的连接占用了11111端口，会导致dummyServer没有启动起来。有没有办法让其它服务不要占用11111端口？或者只能启动的时候检查，如果被占用，就一直while等待&&尝试占用？有没有什么好的方法？

**Comment by gydong** [comment]
看看你用的操作系中，是否有类似于这个内核参数（net.ipv4.ip_local_port_range）可以配置，以帮助解决问题。

**Comment by jamesge** [comment]
pull最新的，允许dummy_port为0 (内核会自动选一个端口）
