### ISSUE TITLE
HTTP request body压缩问题

### ISSUE THREAD

**Issue by machunleilei** [brpc/brpc#153]
看了下代码实现，发现对于http有几个问题
1. HTTP request body目前只支持gzip压缩
2. HTTP request body上层无法控制是否开启压缩，而是在实现的时候根据body大小来动态判断的

这个设计的考虑是有什么特定原因吗？

还是希望这种灵活性留给用户可能会更好，也希望能支持zlib和snappy，我看代码中是有这几种压缩算法实现的

**Comment by jamesge** [comment]
1. 因为浏览器和大部分http client只支持gzip。snappy不是http的压缩标准
2. -http_body_compress_threshold可以设置为0.

**Comment by machunleilei** [comment]
@jamesge 
1. 我感觉对于第一种其实可以完全给用户使用，如果用户自己配置了，说明是有这种需求的
2. http_body_compress_threshold这个虽然可以设置，但是设置为0，说明所有的数据都会采用gzip压缩，这满足不了不需要压缩的用户需求，如果设置过大，多大是合适的，这个不太好评估。
以上只是我自己的看法，当然可能并不一定是正确的，我先fork一个，把这个限制去掉，满足我这边的需求吧
非常感谢回复

**Comment by jamesge** [comment]
"设置为0，说明所有的数据都会采用gzip压缩", 并不是这样，设置了request/response_compress_type才会压缩。
