### ISSUE TITLE
双向stream的需求

### ISSUE THREAD

**Issue by zheng39562** [brpc/brpc#155]
看了几天。感觉bthread看起来挺不错的。
但关于双向stream存在疑惑。https://github.com/brpc/brpc/blob/master/docs/en/server_push.md
在某些场景下（比如我做的游戏），会需要server其实需要频繁的发送包给client。
文章中说道：client首先得认识server发来的消息，否则是鸡同鸭讲。但在某些场景，其实client是一直保持上下文的。如果一定要使用server push。那就必须一个一个消息的去从client拉（或server每次请求把所有准备好的都发过来）。在使用上，会有大量无用的client请求（用来注册）
希望可以考虑一下双向stream的问题。
比如我的场景下，如果没有双向stream，我现在好像只能循环request。

**Comment by zheng39562** [comment]
理论上，使用request就可以获取到数据。但在使用上，会多出很多没有意义的注册请求。游戏中小包非常多，如果一秒10个包，也就是每个client就都需要10个req。

**Comment by jamesge** [comment]
那篇文章讲的场景偏向通知，一般来说通知的频率不会特别高。如果是server要频繁地想client发数据，那就不算通知，而是streaming了。如果client也是brpc，可以用[streaming rpc](https://github.com/brpc/brpc/blob/master/docs/cn/streaming_rpc.md)；如果client不是brpc，或者想用http，可以用[持续发送](https://github.com/brpc/brpc/blob/master/docs/cn/http_service.md#持续发送)和[持续下载](https://github.com/brpc/brpc/blob/master/docs/cn/http_client.md#持续下载)。还有一种方法是用websocket，扩展不困难，不过brpc目前并未支持。

**Comment by zheng39562** [comment]
非常感谢。当时看streaming rpc的example时，以为是单向的，没反应过来是双工的。
