### ISSUE TITLE
日志问题

### ISSUE THREAD

**Issue by luxu02** [brpc/brpc#158]
brpc的日志没有打到我的项目日志文件里面，而是输出到了命令行。
请问需要配置什么吗？

**Comment by jamesge** [comment]
调用[InitLogging](https://github.com/brpc/brpc/blob/master/src/butil/logging.h#L262)或者使用glog

**Comment by luxu02** [comment]
请问是在哪里调用呢？

**Comment by jamesge** [comment]
一般在main函数入口的地方
