### ISSUE TITLE
Fail to read from Socket   Connection reset by peer [104]

### ISSUE THREAD

**Issue by zengxianbing** [brpc/brpc#1581]
用brpc写的http服务，一直会有 Fail to read from Socket   Connection reset by peer [104]日志打印，这是什么原因？

W1015 21:12:36.599551  1615 input_messenger.cpp:212] Fail to read from Socket{id=9740985829509 fd=17 addr=172.20.17.198:61284:4499} (0x7fe38409de40): Connection reset by peer [104]
W1015 21:12:36.613711  1623 input_messenger.cpp:212] Fail to read from Socket{id=2147483648271 fd=17 addr=172.20.17.204:34285:4499} (0x7fe398137950): Connection reset by peer [104]
W1015 21:12:36.620992  1621 input_messenger.cpp:212] Fail to read from Socket{id=4028679325640 fd=17 addr=172.20.17.217:40590:4499} (0x7fe3a80a71e0): Connection reset by peer [104]
W1015 21:12:37.190973  1626 input_messenger.cpp:212] Fail to read from Socket{id=1975684958648 fd=17 addr=172.20.17.224:27660:4499} (0x7fe38c0a1c20): Connection reset by peer [104]
W1015 21:12:37.205332  1615 input_messenger.cpp:212] Fail to read from Socket{id=9749575764101 fd=17 addr=172.20.17.205:9608:4499} (0x7fe38409de40): Connection reset by peer [104]
W1015 21:12:37.208849  1626 input_messenger.cpp:212] Fail to read from Socket{id=2156073582863 fd=17 addr=172.20.17.204:36939:4499} (0x7fe398137950): Connection reset by peer [104]
W1015 21:12:37.256283  1621 input_messenger.cpp:212] Fail to read from Socket{id=4037269260232 fd=17 addr=172.20.17.216:27277:4499} (0x7fe3a80a71e0): Connection reset by peer [104]
W1015 21:12:38.787305  1623 input_messenger.cpp:212] Fail to read from Socket{id=6932077216767 fd=17 addr=172.20.17.214:7874:4499} (0x7fe37402aa80): Connection reset by peer [104]
W1015 21:12:38.791271  1623 input_messenger.cpp:212] Fail to read from Socket{id=9758165698693 fd=17 addr=172.20.17.193:23834:4499} (0x7fe38409de40): Connection reset by peer [104]
W1015 21:12:38.791416  1615 input_messenger.cpp:212] Fail to read from Socket{id=2190433323444 fd=21 addr=172.20.17.211:60387:4499} (0x7fe38c0a1420): Connection reset by peer [104]
W1015 21:12:38.791520  1620 input_messenger.cpp:212] Fail to read from Socket{id=11055245822214 fd=20 addr=172.20.17.221:53526:4499} (0x7fe3740aad90): Connection reset by peer [104]
W1015 21:12:38.791572  1612 input_messenger.cpp:212] Fail to read from Socket{id=6940667151359 fd=22 addr=172.20.17.204:50548:4499} (0x7fe37402aa80): Connection reset by peer [104]
W1015 21:12:38.800129  1626 input_messenger.cpp:212] Fail to read from Socket{id=2164663517455 fd=17 addr=172.20.17.196:25901:4499} (0x7fe398137950): Connection reset by peer [104]
W1015 21:12:38.809661  1615 input_messenger.cpp:212] Fail to read from Socket{id=2199023258036 fd=17 addr=172.20.17.201:49555:4499} (0x7fe38c0a1420): Connection reset by peer [104]
W1015 21:12:38.812070  1620 input_messenger.cpp:212] Fail to read from Socket{id=9766755633285 fd=17 addr=172.20.17.219:43309:4499} (0x7fe38409de40): Connection reset by peer [104]
W1015 21:12:38.812194  1623 input_messenger.cpp:212] Fail to read from Socket{id=3186865735600 fd=20 addr=172.20.17.204:50640:4499} (0x7fe3a80a41e0): Connection reset by peer [104]
W1015 21:12:38.812786  1621 input_messenger.cpp:212] Fail to read from Socket{id=11063835756806 fd=21 addr=172.20.17.219:43310:4499} (0x7fe3740aad90): Connection reset by peer [104]
W1015 21:12:38.814734  1615 input_messenger.cpp:212] Fail to read from Socket{id=6949257085951 fd=17 addr=172.20.17.196:25981:4499} (0x7fe37402aa80): Connection reset by peer [104]
W1015 21:12:38.828716  1626 input_messenger.cpp:212] Fail to read from Socket{id=9775345567877 fd=17 addr=172.20.17.205:17541:4499} (0x7fe38409de40): Connection reset by peer [104]
W1015 21:12:38.829767  1615 input_messenger.cpp:212] Fail to read from Socket{id=5222680234247 fd=20 addr=172.20.17.200:41467:4499} (0x7fe3740aaf90): Connection reset by peer [104]
W1015 21:12:38.836995  1623 input_messenger.cpp:212] Fail to read from Socket{id=11072425691398 fd=17 addr=172.20.17.213:19035:4499} (0x7fe3740aad90): Connection reset by peer [104]
W1015 21:12:38.859191  1612 input_messenger.cpp:212] Fail to read from Socket{id=2783138808771 fd=17 addr=172.20.17.213:19134:4499} (0x7fe374023280): Connection reset by peer [104]
W1015 21:12:38.910203  1621 input_messenger.cpp:212] Fail to read from Socket{id=4045859194824 fd=17 addr=172.20.17.198:11149:4499} (0x7fe3a80a71e0): Connection reset by peer [104]

**Comment by Gliushuai** [comment]
你能编译通过吗，能帮忙提供下编译所依赖的版本吗 比如，gflags, protobuf, leveldb，我目前编译PB一直报版本错误
