### ISSUE TITLE
基于权重的负载均衡

### ISSUE THREAD

**Issue by gydong** [brpc/brpc#159]
我这里有这么一种需求：在服务器配置完全相同的情况下，想让部分机器处于高流量状态运行，比如这部分机器流量总是比其他机器高出20%。这么做的目的是为了，提前知道单台服务器的负载上限。用brpc，怎么满足这种需求？

**Comment by jamesge** [comment]
可以试下[la](https://github.com/brpc/brpc/blob/master/docs/cn/lalb.md)

**Comment by gydong** [comment]
@jamesge la 是自动根据下游服务节点的响应延迟做权重计算，我需要的是人为指定权重，其实也就是WRR的负载均衡方式。

**Comment by jamesge** [comment]
人为的权重在bns里到是支持的，不过这是百度内的系统。实现方法是让一台机器在LB中重复多次以实现（整数）权重，重复方法是配置不同的tag。

**Comment by jamesge** [comment]
此功能已经在PR #243 中合入。

**Comment by one0320heart** [comment]
用tag多配几个实例在你想要高流量状态运行的机器上
