### ISSUE TITLE
ParallelChannel 问题

### ISSUE THREAD

**Issue by machaelliu** [brpc/brpc#160]
你好，请教个问题，在 ParallelChannel 的如下示例中：

```
class UseFieldAsSubRequest : public CallMapper {
  public:
    SubCall Map(int channel_index/*starting from 0*/,
                const google::protobuf::MethodDescriptor* method,
                const google::protobuf::Message* request,
                google::protobuf::Message* response) {
        if (channel_index >= request->sub_request_size()) {
            // sub_request不够，说明外面准备数据的地方和pchan中sub channel的个数不符.
            // 返回Bad()让该次访问立刻失败
            return SubCall::Bad();
        }
        // 取出对应的sub request，增加一个sub response，最后的flag为0告诉pchan什么都不用删
        return SubCall(sub_method, request->sub_request(channel_index), response->add_sub_response(), 0);
    }
  };
```

return 语句中 SubCall 的第一个参数 sub_method 是什么？ 是指可以把原始ParallelChannel
 的 method 方法替换掉吗？具体如何替换？

**Comment by jamesge** [comment]
看下https://github.com/brpc/brpc/blob/master/docs/cn/combo_channel.md

**Comment by machaelliu** [comment]
上面的代码就是从您给出的页面中截取出来的，sub_method 从哪里取到的？

**Comment by jamesge** [comment]
那个sub_method就是代表可能和method不同，但一般是相同的，因为大部分情况用这个是为了”parallel地“访问同一种method。如果不同的话，一般是访问google::protobuf::ServiceDescriptor::method(int index)获得对应的method，例子可以看下[这个单测](https://github.com/brpc/brpc/blob/ef4eddde8b861780ab3ccc3abda3e806e0ea3f09/test/brpc_channel_unittest.cpp#L455)
