### ISSUE TITLE
每次rpc请求增加条日志打印

### ISSUE THREAD

**Issue by luxu02** [brpc/brpc#163]
我想把每次rpc请求的下游ip打条日志出来，请问源码是在哪里？

**Comment by jamesge** [comment]
框架不会打这种日志，需要可以自己打，下游ip的[获取方式](https://github.com/brpc/brpc/blob/master/docs/cn/client.md#%E8%8E%B7%E5%8F%96server%E7%9A%84%E5%9C%B0%E5%9D%80%E5%92%8C%E7%AB%AF%E5%8F%A3)
