### ISSUE TITLE
compile with glog，运行echo_c++示例程序会报错

### ISSUE THREAD

**Issue by bushidonggua** [brpc/brpc#164]
如题，使用--with_glog，得到的rpc库用于运行example/echo_c++的echo_server会报错，错误如下：

ERROR: something wrong with flag 'flagfile' in file 'src/gflags.cc'.  One possibility: file 'src/gflags.cc' is being linked both statically and dynamically into this executable.

**Comment by dhx1989** [comment]
使用bazel编译

**Comment by jamesge** [comment]
没有libgflags.so。
