### ISSUE TITLE
bvar's design and implemetation

### ISSUE THREAD

**Issue by demiaowu** [brpc/brpc#166]
hi, @jamesge 想问一个关于bvar性能和实现的问题。

在https://github.com/brpc/brpc/blob/master/docs/cn/bvar.md 中性能测试对比中，bvar的set性能表现非常出色，而且总是好于atomic。但是在自己的测试中，发现 thread local变量的性能比atomic要差不少，所以这样基于thread local来实现bvar类似的东西性能肯定不会好。尽管在多线程状态下基于thread local冲突较少，仍然无法弥补这种差距，因为atomic的延迟曲线随着线程数增加并不是特别明显。自己也利用thread local做了一个小类似bvar的demo，发现性能确实不太好。

不知道bvar是如何设计实现的，虽然自己看了一下代码，但是没怎么看懂，不知道能不能从设计和实现的角度来解答一下我疑惑，使自己能更好的看懂bvar这部分实现代码，万分感激。

**Comment by chenzhangyi** [comment]
这个取决于你的thread_local实现，你可以在你的环境里面跑下bvar的ut, 里面含有benchmark.

**Comment by demiaowu** [comment]
我测试和小demo的实现都是使用的就是C++11的thread_local

**Comment by jamesge** [comment]
bvar C++版中的reducer和recorder等变量是每个线程累加到自己的TLS中去，局部数据过大或读取时会合并。java版是累加到绑定的bucket中去（可能有冲突）。概念上是简单的。性能实现的话就不太好说了。另外这种代码对优化是敏感的，确认你的测试代码开了O2。

**Comment by chenzhangyi** [comment]
@demiaowu 建议贴一下你的测试代码，环境(OS和机器配置), 以及最后的数据
单纯从这个issue中很难获取任何有用的信息.

**Comment by demiaowu** [comment]
@jamesge 就是日常用的笔记本，i7-7代，标准电压版。现在的主要疑问还是，单单测试cpp11的thread_local，在单线程的情况下性能较atomic相差较多，随着线程数增加，thread_local的性能比atomic慢慢好一些（因为在多线程情况下atomic存在竞争和CPU cache失效），**但是在https://github.com/brpc/brpc/blob/master/docs/cn/bvar.md图中显示，bvar性能总是优于atomic**（这是我比较疑惑的地方）。而bvar是基于thread local实现的，那么理论上在线程数据较少（我这边机器测试显示1~2个线程）的时候，bvar的性能应该比atomic差才对。比如下面代码给出单个线程thread_local测试和atomic的比较，thread local比atomic性能差，当然随着线程数增加，thread local性能开始比atomic好了。
```
    uint64_t kMaxLoop = 1000000000UL;

    thread_local int64_t count1 = 0;
    TestTimer t1;
    for (uint64_t i=0; i<kMaxLoop; ++i)
    {
        ++ count1;
    }

    double time1 = t1.elapsed_micro();
    std::cout << "thread local: " << time1 /1000/1000<< std::endl;


    std::atomic<int64_t> atomic1(0);
    TestTimer t2;
    for (uint64_t i=0; i<kMaxLoop; ++i)
    {
        ++ atomic1;
    }

    double time2 = t2.elapsed_micro();
    std::cout << "atomic: " << time2 / 1000 / 1000 << std::endl;
```

不知道您那边具体TLS使用的是？

**Comment by jamesge** [comment]
可以试下__thread，看看有什么变化，并且一定要加上-O2. atomic那个作为对比应该这么调用atomic1.fetch_add(1, std::memory_order_relaxed)，默认的fence是memory_order_seq_cst，有所不同。

**Comment by demiaowu** [comment]
有对比__thread和cpp11 thread_local，性能相差无几，有加O2选项。atomic确实用的默认最严格内存序，改成atomic1.fetch_add(1, std::memory_order_relaxed)，估计atomic性能会更好。手边暂时没机器，明天再测测~

**Comment by demiaowu** [comment]
@jamesge @chenzhangyi  找到原因了，原来是自己在camke中加-O2加错了，大写的尴尬~自己的写的类似bvar的小demo，单线程my: 10ns，atomic: 5.7ns，两个线程就开始翻身了：my: 还是10ns左右，atomic到40+ns。复合预期。

看您的bvar在单线程的情况下都比atomic好，厉害。感觉自己从 “bvar“ 到thread_local的映射查找还需要优化，现在只是简单的用unordered_map来实现的，感觉查找消耗比较大
