### ISSUE TITLE
bthread 内存屏障问题

### ISSUE THREAD

**Issue by zylthinking** [brpc/brpc#168]
刚开始看bthread代码， 有点疑问， 涉及内存屏障， 我对c++11的内存屏障语义并没有太多研究， 只是粗略看过部分介绍， 与之前理解的概念大概对应上就不研究了。

但以下代码其实与我的理解是冲突的， 在我理解里面， memory_order_consume 其实就是数据依赖屏障， 就是基本上在alpha 这种多个 LSQUEUE 的 CPU 才有意义的那个。

那么， 从概念上讲， 数据依赖屏障其实是为了防止存在依赖关系的数据可见性问题， 比如

int n = 0;
int* p = NULL;

cpu 1:
n = 1;
wmb();
p = &n;

cpu 2:
int * p2 = p;
read_barrier_depends();
if (p2 != NULL) {
    assert(*p2 == 1);
}

如果没有 read_barrier_depends， 则在 p2 != NULL 也就是 p 已经被其他核观察到时， 也不能保证 assert 成立。 这里不考虑 load 自身可能会是非原子问题。

那么看以下代码， 
1. 其实并没有数据依赖， 弄来弄去都是 &g_task_control;
2. atomic 本身就是原子性的， 附加的内存屏障操作影响的是原子变量之外的其他变量与之的可见关系， 而这里还是问题 1， 并没有其他变量, 本身的可见性， atomic已经保证了

因此， 在我看来， 这里的 load 也罢， store 也罢， 统统 relax 即可， concume 与 release, 在这里没有什么用。

 58 inline TaskControl* get_or_new_task_control() {
 59     butil::atomic<TaskControl*>* p = (butil::atomic<TaskControl*>*)&g_task_control;
 60     TaskControl* c = p->load(butil::memory_order_consume);
 61     if (c != NULL) {
 62         return c;
 63     }
 64     BAIDU_SCOPED_LOCK(g_task_control_mutex);
 65     c = p->load(butil::memory_order_consume);
 66     if (c != NULL) {
 67         return c;
 68     }
 69     c = new (std::nothrow) TaskControl;
 70     if (NULL == c) {
 71         return NULL;
 72     }
 73     if (c->init(FLAGS_bthread_concurrency) != 0) {
 74         LOG(ERROR) << "Fail to init g_task_control";
 75         delete c;
 76         return NULL;
 77     }
 78     p->store(c, butil::memory_order_release);
 79     return c;
 80 }

**Comment by jamesge** [comment]
65行的consume是和78行的release配对的，你想象一个线程在正好在78行要store完时，另一个线程在65行调用了load，这时需要那对fence来确保TaskControl::init中的对TaskControl的修改对第二个线程可见。consume的意思是只关注指针指向的区域。如果init中还修改了TaskControl意外的东西，我也要确保可见的话，就要用acquire。这套机制在singleton模式中很常见，但在刚接触memory fence时是有点难理解的。

**Comment by zylthinking** [comment]
我知道你们想干什么， 但你仔细想想， 是不是 所有 memory_order_release， memory_order_consume 都能用 memory_order_relax 替换？ 甚至在 x86, x64 上， 干脆可以直接将 atomic 省略掉

**Comment by jamesge** [comment]
需要可见的不是"g_task_control"这个指针，而是它指向内存段中的各种字段。后续对Taskcontrol的函数调用操作的内存并不是那个指针本身（的字面值），而是指向的各种字段。你只盯着那个指针的可见性，就忘记它并不是真正被需要的东西了。x86上不用fence也能工作是因为x64的load/save自带acquire和release。

**Comment by zylthinking** [comment]
G_task_control 指向的结构体的各个字段的可见性和你这里这个atomic 及内存屏障有关系？ 换句话说 你解释解释你这里的屏障怎么影响相关变量的可见性的 不管指针本身还是他的成员

**Comment by zylthinking** [comment]
貌似你是对的 我没仔细想

**Comment by zylthinking** [comment]
但是我还是有点嘀咕啊， 你看
59 butil::atomic<TaskControl*>* p = (butil::atomic<TaskControl*>)&g_task_control;
60 TaskControl c = p->load(butil::memory_order_consume);

我不清楚  (butil::atomic<TaskControl*>)&g_task_control; 发生了什么操作， 但如果只是普通 &g_task_control 的话， 那么， c的可见性保证并不是 p->store(c, butil::memory_order_release); 时才发生的， 有没有可能在  c = new (std::nothrow) TaskControl; 就已经潜在发生了， 虽然并不绝对可保证。

但如果真的在那时就可能会被 TaskControl c = p->load(butil::memory_order_consume); 观察到， 那么， 你的 init 就不能保证被及时观察到了
