### ISSUE TITLE
为什么bthread 会比eventloop 更好

### ISSUE THREAD

**Issue by zylthinking** [brpc/brpc#169]
文档是如下解释的：

在这点上eventloop是类似的，一个回调卡住整个loop就卡住了，比如ubaserver（注意那个a，不是ubserver）是百度对异步框架的尝试，由多个并行的eventloop组成，真实表现糟糕：回调里打日志慢一些，访问redis卡顿，计算重一点，等待中的其他请求就会大量超时。所以这个框架从未流行起来。
bthread是一个M:N线程库，一个bthread被卡住不会影响其他bthread。关键技术两点：work stealing调度和butex，前者让bthread更快地被调度到更多的核心上，后者让bthread和pthread可以相互等待和唤醒。这两点协程都不需要。

我大概理解是， eventloop .会卡线程， 导致任务队列其他任务得不到处理。 因此， 这个任务队列应该是每个线程一个自己的队列， 否则共用一个队列， 则天生就是work strealing 的， 不存在  真实表现糟糕：回调里打日志慢一些，访问redis卡顿，计算重一点，等待中的其他请求就会大量超时。

但就算如此， 既然bthread能work stealing, 难道每线程一个任务队列的模式就不能 work strealing吗？ 优先处理自己的队列， 自己空了后， 就从其他线程队列里弄一部分任务过来， 看上去实现难度并不比 bthread 更困难。 如果这个不是优势， butex 应该也不是， 照文档，他作用就是和 pthread_mutex互相等待， 并不是比 pthread_mutex 更轻量。

**Comment by demiaowu** [comment]
一个线程一个Event loop，event loop上面的任务并不都能work stealing，因为很多任务都是关注某一个fd，而这个fd polling在这个Event loop上，这是一种强相关，并不能简单的转到其他的event loop来实现work stealing。

    “回调里打日志慢一些，访问redis卡顿，计算重一点，等待中的其他请求就会大量超时”——这是长尾，遵循排队论的原则，1,2,3,4,5,6,7,8个请求，先进先出，1如果延迟100ms，那么2,3,4,5,6,7,8的延迟都将增加100ms，长尾处理不好会对服务质量产生较大的影响。

    所以简单的mutil event loop可能只使用与一些简单，延迟分布统一的服务端（有长尾的服务端并不合适），类似Web服务器，以Nginx为例，就是多个进程，多个event loop，一个event loop服务listen和链接分发。

   “ 这个任务队列应该是每个线程一个自己的队列， 否则共用一个队列， 则天生就是work strealing 的”——这样虽然work stealing了，但是多个线程竞争同一个队列，这种竞争开销不容忽视，而且很多时候是致命的。

    自己所理解的可能得，多线程（一个线程一个event loop）+ 线程池，长尾请求从event loop丢给线程池处理，线程池实现work stealing。

    自己从自己所了解的点来讨论这个问题，更多关于bthread是如何处理长尾，如何work stealing来充分利用多核心，避免长尾影响的？期待 @jamesge 解疑

**Comment by zylthinking** [comment]
因为很多任务都是关注某一个fd，而这个fd polling在这个Event loop上，这是一种强相关，并不能简单的转到其他的event loop来实现work stealing。

如果这是理由 很显然bthread  也做不到stealing  这和线程模型完全没关系

**Comment by zylthinking** [comment]
“ 这个任务队列应该是每个线程一个自己的队列， 否则共用一个队列， 则天生就是work strealing 的”——这样虽然work stealing了，但是多个线程竞争同一个队列，这种竞争开销不容忽视，而且很多时候是致命的。

你这话和你fd强相关是有冲突的 不知意识到没有。
其实想想大概可以知道 bthread 应该就是每线程一队列的实现   加上任务在线程队列之间重平衡 也就是其实bthread 就是一个任务队列的实现模式。

**Comment by zylthinking** [comment]
我大概明白所谓eventloop 不好是什么意思了 感情是没有任务队列这个概念 所有请求在socket缓冲区排队的意思啊

**Comment by jamesge** [comment]
eventloop, work stealing都只是线程调度的一部分，这里该看的是要解决的问题或想达成的目标：只要工作线程还有空闲，请求就应该被及时地被处理，而不是等在某个队列里。多个平行运行的eventloop是做不到这点的，而共享一个队列性能又差。怎么让所有cpu尽量并行，同时又让请求被及时处理，还要考虑系统调用的开销、cpu coherence的制约等主要因素，到目前为止仍然是困难的。这里的问题早不是可行与否，而是能做到多好。要理解具体的困难，可能得看的深入一点才能明白，恐怕不是我几句话就能概括好的。举个例子，目前CPU正在从SMP逐渐转移至NUMA架构，CPU数目（不是核心数）越来越多，这个架构要尽量避免访问其他CPU上的内存，否则性能就差的非常多（20%以上），怎么调度目前仍然非常困难的。这和调模型是类似的，有很多idea，然后要一个个试，最后找到平衡了功能和简洁的方案。
