### ISSUE TITLE
bthread 内存屏障问题2

### ISSUE THREAD

**Issue by zylthinking** [brpc/brpc#170]
又看了部分bthread源码， 又有些疑问：
这次涉及2个线程：
1. 线程 1 创建 bthread, 他依次调用 get_or_new_task_control--->TaskControl->init---->创建worker thread(线程2)， 然后在循环里面等待 ngroups > 1 ---> choose_one_group

choose_one_group 代码如下： 是 relax, 
TaskGroup* TaskControl::choose_one_group() {
    const size_t ngroup = _ngroup.load(butil::memory_order_relaxed);
    if (ngroup != 0) {
        return _groups[butil::fast_rand_less_than(ngroup)];
    }
    CHECK(false) << "Impossible: ngroup is 0";
    return NULL;
} 
2. 线程 2 create_group-->add_group
add group 代码片段如下：
    std::unique_lock<butil::Mutex> mu(_modify_group_mutex);
    if (_stop) {
        return -1;
    }
    size_t ngroup = _ngroup.load(butil::memory_order_relaxed);
    if (ngroup < (size_t)BTHREAD_MAX_CONCURRENCY) {
        _groups[ngroup] = g;
        _ngroup.store(ngroup + 1, butil::memory_order_release);
    }
    mu.unlock();

这里是release,  算是个写屏障，

.那么就是 线程 1:
_groups[ngroup] = g；
wmb();
ngroup = ngroup + 1;

线程 2:
   这里有注释说能保证不返回空， 其实这里单纯死循环观察，只能保证观察到 _ngroup.store(ngroup + 1, butil::memory_order_release); 不能保证观察到  _groups[ngroup] = g;
    // Wait for at least one group is added so that choose_one_group()
    // never returns NULL
    while (_ngroup == 0) {
        usleep(100);  // TODO: Elaborate
    }

之后 choose one group 的逻辑大概等同如下， 也不能保证 观察到  _groups[ngroup] = g;：
n = ngroup;
if (n > 0) {
    group = groups[randon_index];
    assert(group != NULL);
}

 整理感觉线程 2 似乎少一个读屏障， relax 承担不了这样的角色； 这样在观察到 n > 0 时， 并不能保证观察到 groups[randon_index] 一定不是一个空

**Comment by jamesge** [comment]
choose_one_group的fence是不严谨的，应该用acquire，可能是直接从上下文直接拷贝过来没有改。
