### ISSUE TITLE
内存屏障问题3

### ISSUE THREAD

**Issue by zylthinking** [brpc/brpc#171]
请问在这里面使用 memory_order_release, memory_order_acquire 又是出于什么考虑?
    
int signal(int num_task) {
        _pending_signal.fetch_add((num_task << 1), butil::memory_order_release);
        return futex_wake_private(&_pending_signal, num_task);
    }

    // Get a state for later wait().
    State get_state() {
        return _pending_signal.load(butil::memory_order_acquire);
    }

**Comment by jamesge** [comment]
某个工作线程被唤醒之后要看到signal之前的内存修改（一般是相应的job），如果没有这个fence，被唤醒的线程可能会看到还在init过程中的job。

**Comment by zylthinking** [comment]
也就是说其实这个release 并不是同 get_state 的 acquire配对的?
这里就有2个疑问了:
1, 那么  get_state 的 acquire 是想干什么?
2, 按你的解释, 应该是想让这里可见所有的更改:
bool TaskGroup::wait_task(bthread_t* tid) {
    do {
#ifndef BTHREAD_DONT_SAVE_PARKING_STATE
        if (_last_pl_state.stopped()) {
            return -1;
        }
        _pl->wait(_last_pl_state);
        if (steal_task(tid)) {
            return true;
        }
#else
        const ParkingLot::State st = _pl->get_state();
        if (st.stopped()) {
            return -1;
        }
        if (steal_task(tid)) {
            return true;
        }
        _pl->wait(st);
#endif
    } while (true);
}

从编码上考虑, 这个读屏障应该存在于 wait 中,  除非 futex 自己带着读屏障, 或者streal_task里面带了一个读屏障, 否则, 单有写屏障是起不到保障作用的; utex 如果是经历了从睡眠中唤醒, 调度时记得带着读屏障, 但如果它压根没睡眠, 直接返回的, 就不太确定了.

**Comment by zylthinking** [comment]
哦, 错了, 就是和它搭配的, wait 之前就是这个
