### ISSUE TITLE
bthread 文档不精确?

### ISSUE THREAD

**Issue by zylthinking** [brpc/brpc#172]
bthread_start_urgent 文档保证新函数会被立刻调度,  bthread_start_urgent 的  caller 会被暂停; 然而似乎是有一个前提条件, 就是 caller 的 stacktype 不能是 pthread 类型, 否则做不到,  而这个caller 的stack 类型也可能不是用户指定的,在内存耗尽的情况下, 就算是其他类型的 stack, 也会被永久性的修改为 pthread 类型,  用户还不知道.  同样, 似乎 yield 之类的, 都是在最顶层 API 上做了防护, 不让真的调用 协程 式的yield,  如果直接调用内部的 sched 之类, 就会乱套了.

不知理解是不是准确

// Create bthread `fn(args)' with attributes `attr' and put the identifier into
// `tid'. Switch to the new thread and schedule old thread to run. Use this
// function when the new thread is more urgent.
// Returns 0 on success, errno otherwise.
extern int bthread_start_urgent(bthread_t* __restrict tid,
                                const bthread_attr_t* __restrict attr,
                                void * (*fn)(void*),
                                void* __restrict args) __THROW;

**Comment by jamesge** [comment]
“在内存耗尽的情况下“ 这种情况已经不太正常了。内存耗尽的前提下，按我的经验绝大部分C++程序都不能正常运行，总会有什么地方忘记判断malloc/new的返回值或是没有捕捉异常。所以这种情况下尽力即可，对用户保持一定的透明，也方便未来调整。

**Comment by zylthinking** [comment]
也就是说我的理解是没问题的是吗, 我其实是想确认这个

**Comment by jamesge** [comment]
是
