### ISSUE TITLE
BRPC有要求特定的protobuf版本吗？

### ISSUE THREAD

**Issue by qiuxiafei** [brpc/brpc#173]
brpc是否有特定的pb版本要求？
用3.5.0测试可以，用pb 2.4 可以吗？

**Comment by jamesge** [comment]
都可以

**Comment by qiuxiafei** [comment]
thanks!

**Comment by yjhjstz** [comment]
> libprotoc 3.1.0 
#error This file was generated by an older version of protoc 
这是什么问题呢？
