### ISSUE TITLE
bthread_stop_world 系统资源泄漏

### ISSUE THREAD

**Issue by zylthinking** [brpc/brpc#174]
先看几个资源回收的时机:

1. corutine 执行完毕后, 在 task_runner里面调度到下一个协程时回收
2. timer中回收, 这个还没仔细看回收的是什么,  一律称之为X
3. stop world 导致main task回收

现在调用 stop_world, 题外话是pthread主循环其实并不会像期待的会最终退出, 因此, stop_world会死在那里, 原因是 wait_task 要么返回true, 要么返回 -1, 就是不返回 false, 这个也先不管.

假设wait_task 返回false, pthread 主循环退出, main task回收, 现在的问题是其他压在 rq 或 remote_rq 或者 remain function 里面的协程都没有人负责释放, 都泄漏了, rq, remote_rq自己的析构函数也帮不上忙

同理timer, 也是自己单纯退出, 那些 X 们没人管了

**Comment by Kontinuation** [comment]
除了bthread之外，bvar中也有许多leaky thread，这导致无法在需要能安全地unload的动态库中使用brpc channel。

**Comment by zylthinking** [comment]
在一个 bthread 中调用 bthread_stop_world 将会自己死锁

**Comment by jamesge** [comment]
线程都不用退，和能不能用动态库关系不大，bthread_stop_world这个接口是没有用的，只是历史原因予以保留

**Comment by Kontinuation** [comment]
这边有遇到过手动dlclose了使用了brpc channel的动态库之后，动态库中创建的bthread timer线程被调度到导致段错误的情况。

**Comment by jamesge** [comment]
这种一般和全局变量被删除有关，要具体看，你可以提issue。原则上，和线程相关的全局复杂变量都应该是指针，且从不删除，但可能有遗漏。

**Comment by zylthinking** [comment]
pthread并不是这样, 没有什么是必然的; 这里也能实现的不死锁, 不过在 "bthread_stop_world这个接口是没有用的，只是历史原因予以保留" 的前提下, 相关一切都没有意义了而已.
