### ISSUE TITLE
周期性定时器支持？

### ISSUE THREAD

**Issue by rongliang666** [brpc/brpc#175]
是否支持业务层面周期性定时任务，比如每分钟执行一次的任务。
查看bthread_timer_add只支持一次性的绝对时间，若是周期性任务，只能自己在time_proc结尾再次添加定时？

**Comment by jamesge** [comment]
是的，rpc框架不需要循环任务，所以timer接口是最简化的。

**Comment by rongliang666** [comment]
好的，感谢。
