### ISSUE TITLE
下游服务熔断

### ISSUE THREAD

**Issue by gydong** [brpc/brpc#176]
brpc 中的channel有没有一些对下游服务的熔断机制？比如，在固定时段段内，下游服务error（通常是超时）数量大于设定阈值，则规避一段向该下游服务的请求。我的业务场景是这样的，在公网上访问第三方的HTTP服务，需要类似于nginx中upstream模块支持的  max_fails 和 fail_timeout。

**Comment by jamesge** [comment]
没有这个功能，la有类似的效果。不过这个功能也许可以集成在健康检查里。

**Comment by gydong** [comment]
@jamesge 在创建channel的时候，可以支持自己定制CheckHealth吗？

**Comment by jamesge** [comment]
Socket层面的健康检查定制不了，那个CheckHealth不是这个。这两天我会看一下。

**Comment by gydong** [comment]
@jamesge 好的，多谢。

**Comment by jamesge** [comment]
此功能已在开发中。
