### ISSUE TITLE
gethostbyname 阻塞问题

### ISSUE THREAD

**Issue by gydong** [brpc/brpc#178]
brpc的EndPoint构造的时候，如果用的是域名，会调用到gethostbyname_r这个函数，这个函数是同步阻塞的。以前遇到的问题是，当DNS 服务有问题的时候，程序会被阻塞，造成无法正常提供服务，后来替换成c-ares异步请求DNS才解决了这个问题。所以，现在brpc中也会遇到上面提到的那个问题，是这样吗？

**Comment by jamesge** [comment]
如果对应的brpc::Channel是单server模式，是会这样的，不过多线程对单个线程阻塞不是那么敏感。如果对应的brpc::Channel是集群模式（设置了负载均衡），影响会更小些，因为gethostbyname是在后台线程中定义调用的，即使阻塞了也不影响前台访问。

**Comment by gydong** [comment]
但是后台的bthread可能会出现阻塞住所有pthread的情况（而且在我们的应用场景中很可能），进而导致前台bthread没有work可用。

**Comment by jamesge** [comment]
我说的“后台线程”是定期访问名字服务的线程，这里是[dns](https://github.com/brpc/brpc/blob/master/src/brpc/policy/domain_naming_service.cpp)。你说的“后台bthread”是指什么

**Comment by gydong** [comment]
我说的是下面这段代码，可能会因为名字服务而创建bthread。  

`
int NamingServiceThread::Start(const NamingService* naming_service,
                               const std::string& service_name,
                               const GetNamingServiceThreadOptions* opt_in) {
    if (naming_service == NULL) {
        LOG(ERROR) << "Param[naming_service] is NULL";
        return -1; 
    }   
    _source_ns = naming_service;
    _ns = naming_service->New();
    _service_name = service_name;
    if (opt_in) {
        _options = *opt_in;
    }   
    _last_sockets.clear();
    if (_ns->RunNamingServiceReturnsQuickly()) {
        RunThis(this);
    } else {
        int rc = bthread_start_urgent(&_tid, NULL, RunThis, this);
        if (rc) {
            LOG(ERROR) << "Fail to create bthread: " << berror(rc);
            return -1; 
        }   
    }   
    return WaitForFirstBatchOfServers();
}`

**Comment by jamesge** [comment]
如果有很多域名，且gethostbyname全部卡住，是有这个可能。c-ares比较重&公司内场景一般不超时，所以这块一直没动。如果有轻量的可靠的实现，可以考虑用。
