### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [brpc/brpc#18]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [GianoAuthenticator](https://github.com/brpc/brpc/blob/30992d3a50d1d39d58f804a6311a726ad99dba37/src/brpc/policy/giano_authenticator.cpp#L41 "Destructor for GianoAuthenticator")
- [SocketMap](https://github.com/brpc/brpc/blob/30992d3a50d1d39d58f804a6311a726ad99dba37/src/brpc/socket_map.cpp#L134 "Destructor for SocketMap")

**Comment by jamesge** [comment]
removed

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/brpc/brpc/commit/2a1d50d61ada491c4b24e979dea53f2909f90dd6 "remove unneeded if before delete").
