### ISSUE TITLE
http client 返回Connection refused，但状态码是200

### ISSUE THREAD

**Issue by tjb1216** [brpc/brpc#180]
用brpc http client访问错误的url（地址填错了，或者http服务挂了），cntl_->ErrorText()打印错误如下：
[E111]Fail to connect SocketId=2@10.10.132.212:8501: Connection refused
但是cntl_->http_response().status_code()为200，看源码里面状态码默认为200 。
这种不一致的状态容易让人误解，是不是应该解决？

**Comment by jamesge** [comment]
严格地来说。只有当错误码是EHTTP时，才能检查status-code。不过最近简化了下status-code的设置，之后合入后这种情况下status-code应该有合理的值了。

**Comment by tjb1216** [comment]
验证确实生效，返回500，多谢解惑
