### ISSUE TITLE
tls 问题

### ISSUE THREAD

**Issue by machaelliu** [brpc/brpc#181]
您好，有几个问题想请教一下
1、 下面加入到 server 中的 EchoSerrviceImpl 类是所有线程共用的是吗？这个类必须是线程安全的对吗？
`brpc::Server server;                                                         
example::EchoServiceImpl echo_service_impl;                                  
if (server.AddService(&echo_service_impl,   brpc::SERVER_DOESNT_OWN_SERVICE) != 0) {  ...}                                                                      `
2、看了 https://github.com/brpc/brpc/blob/master/docs/cn/server.md  中tls 相关的文档，没太懂。server-thread-local 中的示例代码中，我测试了一下，无论服务开几个线程，下面结构的构造函数只被调用了一次。
`struct MyThreadLocalData {
    MyThreadLocalData() : y(0) {}
    int y;
};`
这是否说明 session-local 和 thread-local 中定义的数据是类似于全局变量的，只存在全局的一个实例，然后供所有线程共用？

3、如果 session-local 和 thread-local 创建的数据是全局只有一个实例，那上面的 struct MyThreadLocalData 这个类应该设计成线程安全的，这样理解对吗？

4、bthread_key_create 创建的 bthread local 数据是每个线程都有一份吗？ 也就是 bthread_key_create 创建的变量是每个线程私有的、各自独立的数据对吗？

**Comment by jamesge** [comment]
1.是 2.并发小会复用 3.不对 4.是

**Comment by machaelliu** [comment]
1. tls 数据要并发小的时候会被多个线程复用，又不需要线程安全，使用不会出问题吗？

2. 测试了一下，开多个线程时，下面的代码中的 new 只会执行一次，之后所有线程的tls 都不为 NULL，多个线程用的是同一份数据，并不是每个线程都有自己的私有数据。
`MyThreadLocalData* tls = static_cast<MyThreadLocalData*>(bthread_getspecific(tls_key));
if (tls == NULL) {  // First call to bthread_getspecific (and before any bthread_setspecific) returns NULL
    tls = new MyThreadLocalData;   // Create thread-local data on demand.
    CHECK_EQ(0, bthread_setspecific(tls_key, tls));  // set the data so that next time bthread_getspecific in the thread returns the data.
}
`
如果想每个底层 pthread worker 都保存一份自己私有的数据，应该怎么做？

**Comment by colaghost** [comment]
这里看bthread_key_create的例子有点不太明白，pthread_key_create要保证全局只调一次，bthread_key_create是每个bthread都要调用一次吗？
