### ISSUE TITLE
关于ParallelChannel的sub channel负载均衡的疑问？

### ISSUE THREAD

**Issue by feng-y** [brpc/brpc#186]
基于[parallel_echo_c++](https://github.com/brpc/brpc/tree/master/example/parallel_echo_c++)
在server端输出log id，在本机上启动两个端口，client在线程数等于1时测试
./echo_client -server list://127.0.0.1:8002,127.0.0.1:8003 -load_balancer rr -thread_num 1

server端输出如下：

E0108 15:43:01.239829  8155 server.cpp:45] tt:72924
E0108 15:43:01.239870  8155 server.cpp:45] tt:72924
E0108 15:43:01.239896  8155 server.cpp:45] tt:72924
E0108 15:43:01.240180  8153 server.cpp:45] tt:72926
E0108 15:43:01.240189  8151 server.cpp:45] tt:72926
E0108 15:43:01.240184  8154 server.cpp:45] tt:72926
E0108 15:43:01.240560  8155 server.cpp:45] tt:72928
E0108 15:43:01.240599  8155 server.cpp:45] tt:72928
E0108 15:43:01.240627  8155 server.cpp:45] tt:72928
E0108 15:43:01.240903  8153 server.cpp:45] tt:72930
E0108 15:43:01.240912  8157 server.cpp:45] tt:72930
E0108 15:43:01.240905  8154 server.cpp:45] tt:72930
E0108 15:43:01.241272  8155 server.cpp:45] tt:72932
E0108 15:43:01.241278  8151 server.cpp:45] tt:72932
E0108 15:43:01.241294  8151 server.cpp:45] tt:72932
E0108 15:43:01.241590  8153 server.cpp:45] tt:72934
E0108 15:43:01.241599  8157 server.cpp:45] tt:72934
E0108 15:43:01.241591  8154 server.cpp:45] tt:72934

发现一次ParallelChannel请求的sub channel请求都发送到同一个server上，不知道我测试有误还是ParallelChannel本来就是这样做负载均衡的？
望解答，谢谢

**Comment by jamesge** [comment]
ParallelChannel同时访问所有的sub channel，本身是没有负载均衡概念的。
