### ISSUE TITLE
请问这种场景适合用bthread_local吗？

### ISSUE THREAD

**Issue by wclin88** [brpc/brpc#188]
bthread_local变量做的事情是第一次创建的时候建立一个mysql连接，之后用于做数据操作。这样如果有10个bthread_local线程，我就可以一直重用这10个连接，相当于一个连接池。请问这种做法会不会有什么坑呢？之前我们用pthread线程就是这样做法。

**Comment by jamesge** [comment]
mysql连接为什么要放TLS里？这样不同线程间不能共享，放一个全局pool里就行了。

**Comment by wclin88** [comment]
本身线程不多，没有共享的需求；再说共享可能还有竞争消耗。那bthread可以满足这种需求吗，还是说在server回调里还是用原来的用法，直接使用gcc的__thread，如果都有问题，那我再用其他方式。

**Comment by jamesge** [comment]
qps没有过万一般不用考虑多线程竞争的开销。用是可以用的，bthread-local在用法上和pthread_getspecific那套一致。

**Comment by wclin88** [comment]
一个server创建的bthread在退出时并不删除bthread-local，而是还回server的一个pool中，以被其他bthread复用。
这里的bthread退出是bthread销毁的意思吗？就是说只要bthread不销毁，设置在它身上的bthread-local就会一直属于他，下次在同一个bthread上跑的时候，就可以取到同一个bthread-local值，就跟pthread tls一样的用法。这样的理解对吗？谢谢

**Comment by jamesge** [comment]
对。另外退出指的是退出线程所在的那个函数。

**Comment by wclin88** [comment]
啊？那我又不明白了。如果退出指的是退出线程所在的那个函数，那文档的意思就是函数一执行完bthread-local就还回server的一个pool中，以被其他bthread复用了，那就是bthread-local不属于原来的bthread了，就算重用这个bthread，也不是原来的bthread-local了，那跟我上面说的bthread销毁时bthread-local才不属于它又冲突了。

**Comment by jamesge** [comment]
“那个函数”就是线程的入口函数，退出了就再也用不了那个bthread了，至于复用的更多细节，其实不是特别重要。

**Comment by wclin88** [comment]
哦，明白，是入口函数，而不是处理消息的那个函数（比如那个Echo）。再问下哈，在处理函数里，怎么得到这个bthread的唯一标识，如果bthread id之类的？

**Comment by gydong** [comment]
由框架创建的bthread，好像是没办法获取它的标识(地址)的，不过你需要获取标识来做什么呢？

**Comment by jamesge** [comment]
bthread_self()

**Comment by gydong** [comment]
学习了。
