### ISSUE TITLE
MAC上编译卡在了 prepare deps

### ISSUE THREAD

**Issue by GYiyouth** [brpc/brpc#19]
https://github.com/brpc/brpc/blob/master/docs/cn/getting_started.md
这里第一步就卡住了。Mac怎么安装这些库啊老铁门。。。

**Comment by GYiyouth** [comment]
geyaodeMacBook-Pro:brpc geyao$ sh config_brpc.sh --headers=/usr/include --libs=/usr/lib 
-e config_brpc: --headers=HDRPATHS --libs=LIBPATHS must be specified

第二步又卡住了了

**Comment by chenzhangyi** [comment]
暂时只支持Linux环境下的编译

**Comment by yjhjstz** [comment]
赞，但跨平台可以放到 Roadmap了。

**Comment by loveyacper** [comment]
要支持MAC OS，估计还得先迁移到C++11，不知道开发者是否有决心~

**Comment by chenzhangyi** [comment]
和C++11关系不大，迁移到MAC的主要问题在于epoll和futex需要做适配.

**Comment by loveyacper** [comment]
今天才得知brpc，好好研究下。。
嗯了解不多，感觉mutex、condition、thread等都进标准库了
不过貌似brpc对性能优化的比较高端，标准库可能满足不了？

但CPP11还是极大提高生产力的，lambda捕获变量咱也有closure了；
智能指针，基本告别new和delete，也算有gc了，还是实时、非搬迁、精准的gc；
std::function；auto和foreach等语法糖；
提高性能的std::move、emplace_back；
模板编程的一些辅助：std::enable_if，std::conditional等等

PS：util相关的一些东西觉得可以参考Facebook的folly。

**Comment by jamesge** [comment]
brpc本身一直支持c++11，没用c++11的东西是因为brpc其实是可以在gcc 3.4下编译和使用的（但要依赖boost.atomic）。随着百度的gcc版本逐渐突破三体人的技术封锁，相关代码也会逐渐调整。mac和win下的适配，主要是epoll适配到kqueue/poll/iocp，futex加模拟版本，fd做做抽象之类的。这种调整可能改起来很快也可能很慢，心急的可以自己尝试一下。

**Comment by davidxiaozhi** [comment]
第一时间在试用,确实卡在了mac编译上面,期望快速支持 mac

**Comment by jamesge** [comment]
Missing files are added in [this commit](https://github.com/brpc/brpc/commit/3d9a6ec81b74c875464fab1a6ab2ebf6081cadaa), however the MAC build is not complete yet, we're still working on adaptation for [cmake](https://github.com/brpc/brpc/pull/223) and futex/epoll.

**Comment by flowbehappy** [comment]
👍 Nice work! But we really need OS X portable, mainly because we develop on it.

**Comment by zyearn** [comment]
MacOS is supported now @davidxiaozhi @flowbehappy
