### ISSUE TITLE
支持grpc客户端

### ISSUE THREAD

**Issue by chukeer** [brpc/brpc#192]
看到文档里说支持http+json(proto)方式访问，是否也支持grpc协议呢，比如用grpc生成的客户端访问，如果可以的话，其它语言比如php,java, golang就可以直接使用grpc客户端访问brpc服务，省得还需要给他们开发相应的client sdk

**Comment by jamesge** [comment]
grpc只支持http2, brpc中的http2代码还未开源，估计要节后了。

**Comment by chukeer** [comment]
@jamesge 万分期待啊。有没有预计的开源时间节点，最近在改造我们内部的RPC服务，brpc有非常灵活的接口，私有协议我们可以自己实现，但是grpc这种属于比较通用的，很期待官方的版本

**Comment by jamesge** [comment]
春节前后就会支持。

**Comment by RobitYadda** [comment]
您好,h2/h2c的支持,发布的时间节点有确定下来吗

**Comment by billowqiu** [comment]
看来近期就会推出了，同期待啊

**Comment by yjhjstz** [comment]
+1

**Comment by alanxzj** [comment]
+1

**Comment by RobitYadda** [comment]
+1

**Comment by chchgb** [comment]
+1 想看看http2 push的参考实现

**Comment by liutong19890905** [comment]
+1

**Comment by feng-y** [comment]
+1

**Comment by baixiaohang** [comment]
+1

**Comment by tanguofu** [comment]
+1

**Comment by 06wagon** [comment]
+1

**Comment by jamesge** [comment]
主干已支持grpc, client端协议设置为"h2:grpc"即可，server端无需设置。
