### ISSUE TITLE
关于在bthread里调用网络操作的问题

### ISSUE THREAD

**Issue by chukeer** [brpc/brpc#194]
brpc的每个消息处理都是在一个bthread里，如果在消息处理里调用其它RPC，只会阻塞当前bthread，而不会阻塞底层的pthread，但如果在消息处理里调用的是MySQL操作，并且用的是我们自己实现的MySQL客户端，那必然会阻塞bthread以及它当前的pthread，对于这样的操作是否需要投递到单独的线程去处理

可能有人觉得把worker数量开大一点，哪怕阻塞当前pthread也没关系，但一个服务可能会处理不同种类请求，有些只需要操作MySQL，有些只需要操作redis，有些甚至只需要操作内存，也就是说不通消息处理延时是不同的，如果MySQL操作阻塞了所有pthread，那么其它类型的操作就无法及时响应

在golang中则不会有这种情况，因为它封装了所有IO操作，只要用它的IO实现的MySQL和redis客户端，在操作时只阻塞当前协程，而不会阻塞底层的线程，所以每个请求都能被及时响应

对于这种场景，我们使用brpc时有什么建议

**Comment by gydong** [comment]
估计是要在brpc的体系中去支持你所需要的通信协议，就像brpc中的redis client那样。

**Comment by jamesge** [comment]
这种场景下要追求更高的线程使用效率，就要框架支持对应的协议，golang里也是类似的。redis已经有了，mysql原来有基于myclient或mariadb的实现计划，不过目前pending了。如果你有兴趣的可以尝试下，我们可以提供协作。

**Comment by chukeer** [comment]
@jamesge 如果基于brpc封装相应客户这必然会让服务效率更高，但我想brpc并非是像glang那样提供一个基于协程的服务开发模型，毕竟brpc的bthread都是为rpc框架服务的。并且我们现在内部服务用的都是自己封装的redis， mysql， mongo客户端，改造也有一定代价。所以我想能不能有一种折中的方案，就是我前面提到的，我自己另起一个线程池，在rpc消息响应函数中将那些操作投递到我自己的线程池执行，操作完成后再切换回来发送消息回包（可能还会做一些其它处理逻辑），不知道这种思路在现有brpc框架中是否行得通

**Comment by jamesge** [comment]
可以，但和多开点worker+限制某个方法的concurrency没有太大的区别，还引入了额外的上下文切换。

**Comment by gydong** [comment]
@jamesge 搭车请教，有计划支持kafka吗？

**Comment by wclin88** [comment]
@jamesge 限制某个方法的concurrency？ 有这个设置吗，是某个server的ServerOptions.num_threads吧

**Comment by chukeer** [comment]
@jamesge 设置单个方法的concurrency并不能缓解我说的那种问题，比如worker数量为10，method1的concurrency为5，method2的concurrency也为5，并且这两个操作都会阻塞pthread，如果method1和method2各有5个请求，则worker被打满，假设method1和method2的处理时间较长，那么这时如果来一个处理时间较短的method请求，则会增加该请求的响应延时，除非对method1和method2这一类会阻塞pthread的方法concurrency之和限制为低于10

当然我说的这种情况比较极端，只是阐述这种现象，不知道我理解的对不对

**Comment by jamesge** [comment]
"对method1和method2这一类会阻塞pthread的方法concurrency之和限制为低于10", 你其实就可以这么做，确保总有一些线程不能被占掉。线程总数其实和搞自己的线程池是类似的。
同时回答下@gydong的问题，要支持各种各样的协议，最快的方法还是利用已有的client。如果这个client支持异步接口，那么在回调掉唤醒一个bthread_id结构，原阻塞处等待这个id一般就可以了。
