### ISSUE TITLE
域名映射的ip发生变更brpc工作不正常

### ISSUE THREAD

**Issue by machunleilei** [brpc/brpc#195]
redis fail, error code = 112, error message = [E112]Not connected to xxxx:6379 yet [R1][E112]

**Comment by machunleilei** [comment]
看了下文档，原因估计是我没有指定load balance导致的

**Comment by jamesge** [comment]
没有指定LB的话，域名解析只在init里做一次，指定了的话会持续地做。

**Comment by jamesge** [comment]
Related issue #207
