### ISSUE TITLE
动态链接abi兼容问题

### ISSUE THREAD

**Issue by tjb1216** [brpc/brpc#196]
贵公司内部估计用的是静态链接，无需考虑这个问题，但既然开源了，外部用户大都会用动态链接，所以建议还是得有版本号，保证每个大版本下的升级都是abi兼容的。

**Comment by jamesge** [comment]
要获得ABI兼容所有对用户的头文件都要用opaque指针的方式，这会使得快速迭代和代码调整变的很麻烦，所以brpc在设计之初就放弃了ABI兼容性，只保证API兼容性。现在的软件开发还是最好切换成主干开发，持续集成的模式，否则版本打平导致的问题会在未来浪费更多的时间。

**Comment by tjb1216** [comment]
了解了，多谢解惑
