### ISSUE TITLE
请问打印日志的问题

### ISSUE THREAD

**Issue by wclin88** [brpc/brpc#198]
log模块的性能怎么样？ 担心打印日志太多会不会塞住。看现在生产环境一小时产生3.4G的日志。
有方式可以根据时间打印到不同的日志文件吗？

**Comment by jamesge** [comment]
brpc自带的日志主要是提供一堆日志宏和一个简单的日志实现，生产环境可以考虑glog（锁较重）或通过logsink调用自己的日志模块（百度内便是这样）。

**Comment by gydong** [comment]
@jamesge 请问在百度内部，是通过什么方法来解决多线程环境下频繁写日志的锁竞争的？ 这部分不方便开源吗？ 用POSIX的O_APPEND模式的::write(2)函数可以解决吗？

**Comment by jamesge** [comment]
同步写就是O_APPEND，这不用加锁就可以保证原子，但磁盘卡还是会卡的。异步写的话就是常规的队列+独立的写线程，也没有完全规避锁，只是临界区小很多。最好的办法是用[类似这里的方法](https://github.com/brpc/brpc/blob/master/docs/cn/io.md#%E5%8F%91%E6%B6%88%E6%81%AF)异步写，同时在crash时刷出还未写完的日志以避免丢失，不过出于精力所限，我们并没有把这套方法用于日志。
