### ISSUE TITLE
doc: document should fix version information

### ISSUE THREAD

**Issue by yjhjstz** [brpc/brpc#21]
> r28921之前：如果closewait_ms不会0，且还有请求在被处理，那么Server不会立刻关闭与client的连接，而是继续处理请求，同时对client发来的新请求立刻回复ELOGOFF错误以防止新请求加入，这个过程最多持续closewait_ms毫秒，之后Server会关闭所有连接并退出。

> r28921之后：closewait_ms失效，不管它是什么值，server在退出时总会等待所有正在被处理的请求完成，同时对新请求立刻回复ELOGOFF错误。这么做的原因在于只要server退出时仍有处理线程运行，就有访问到已释放内存的风险。如果你的server“退不掉”，很有可能是由于某个检索线程hang住了，

under git version control ,  can you fix with git version instead of svn version?
many thanks.

**Comment by jamesge** [comment]
Docs are being reviewed during translations to English. All SVN revision will be removed when the translations are done.
