### ISSUE TITLE
new /rpcz

### ISSUE THREAD

**Issue by jamesge** [brpc/brpc#217]
目前的rpcz虽然能够提供per RPC级别的数据，发现一些明显的行为异常。但rpcz搜集的数据的利用程度仍然比较低，对解决问题的效率提升不明显，主要问题有：
 * 没有搜集request/response的内容。
 * 检索历史数据不方便，效率也不高。

我们最终想要的是，用户可以很快地定位到长尾，并对分析它们生命周期的所有细节。有两个思路可以做到：
 * 采样更多数据，建各种索引检索历史数据，就是标准的单机检索系统的做法。作为独立的程序是OK的，但RPC框架不适合这么做，开销太大。也许很强大，但不会有用户会启用的。
 * 用过滤表达式减少采样的范围，并能固化下来。rpcz不再是一个界面，而是根据动态建立的过滤条件分为多个界面，这是我们的思路。

新rpcz的大致逻辑：
 * rpcz默认还是显示所有的请求，但粒度很粗，主要是延时，size之类的信息，开销也很小。
 * 用户可以在一个本文框中键入过滤条件，下方的界面会实时加入满足过滤条件的请求，历史请求是不会加入进来的（因为历史请求很可能并没有存储过滤需要的字段）。过滤条件一般是request/response中的字段和常量比较关系的与或非，比如"weight &gt; 10 && count &lt; 3"。用户可以不断地调整过滤条件，最终捕捉到一小类请求。
 * 用户可以给过滤条件起名并固化下来，如果起名为large_and_slow_requests，下次可以直接通过/rpcz/large_and_slow_requests看到最近符合这个条件的请求。出于性能考虑，用户可以设定一个采样比例。固化信息会存储在server端，重新打开浏览器后仍可以看到。
 * 捕捉到的请求能可视化地展现出来，用户可对一些字段修改后可重发给同一个server。用户还能把请求的所有信息以文本形式粘贴下来(类似http://stackoverflow.com/a/6055620 的效果)，传递给其他人。

过滤条件中的字段可以是：
 * any field in request, size of request.
 * any field in response, size of response.
 * any field in protocol-specific meta.
 * latencies of different stages.
 * duration of locks.
 * user defined key/value.

通过前缀区分不同的字段的从属，比如request.status, meta.log_id, latency.callmethod。没有前缀的话默认认为是request的。
"user defined key/value"对应rpcz一直没有加的key/value annotation。用户可以把检索过程中的数据告诉rpcz，并作为过滤的一个条件。

关于过滤性能：
我们想达到的理想效果是总体开销 = 单次过滤的开销 * 过滤后的请求数量（而不是过滤前的）。如果对应请求比较小众，就可以用更重的过滤条件。这是比较难的。目前的思路是：
 * 把开销小，区分度大的字段排前面。如果全是AND，是比较简单的，但如果有OR和NOT，这个就会比较复杂。乐观地来说，框架应该能启发地找到不是最差的，但和最好的应该有距离。
 * 把开销以实时，简洁地方式告知用户，促进用户自己调节。当一个过滤条件被固化下来时，用户最好能明确地看到它对整体性能的影响，比如“大约每条请求的处理时间增加2微秒”。

Layout:
```
Filter:  [textbox]  (disabled by default on /rpcz/<filter>)
.________________________________________.
| matched request1 (click for details)   |
| matched request2 (click for details)   |
| matched request3 (click for details)   |
| matched request4 (click for details)   |
| ...                                    |
| ...                                    |
|________________________________________|

Save filter --------------------|
| probability: [textbox]        |
| [button: save filter]         |
|-------------------------------|
```

**Comment by tjb1216** [comment]
请问有开发计划吗？

**Comment by jamesge** [comment]
这个功能和tracing差别还挺大的，后者关注的主要是调用链和延时，而这个更多是一种“peek功能“：能实时查看request/response中的任意字段的统计状态，并按自定义条件筛出感兴趣的request/response来以供进一步分析。整体上是一个比较独立和新的功能，具体在什么场景下怎么用，可能仍需要细化。你有想法的话也可以贡献出来。

**Comment by tjb1216** [comment]
想要过滤request和response里的内容确实比较复杂，我觉得一期可以简单一点，只过滤Span spec里定义的字段，比如请求耗时和自定义字段，这样对定位长尾流量也有不小帮助。

**Comment by billowqiu** [comment]
“检索历史数据不方便，效率也不高”
这个是不是像tracing一样把数据集中收集存储比较好？
