### ISSUE TITLE
BRPC Server的pthread有设置name吗？

### ISSUE THREAD

**Issue by qiuxiafei** [brpc/brpc#221]
看起来是没有设置thread name。
有些日志框架可以方便地打印当前线程的名称，设置的话会更友好。

**Comment by jamesge** [comment]
pthead workers会被所有server/channel共用，名字可能没有特别大的意义。

**Comment by qiuxiafei** [comment]
但是在看一些trace的信息时，线程name可以把混在一起的不同线程的日志区分开来。

**Comment by qiuxiafei** [comment]
但是在看一些trace的信息时，线程name可以把混在一起的不同线程的日志区分开来。

**Comment by jamesge** [comment]
trace是通过log-id / request-id / span-id等形式来连接到一起的

**Comment by qiuxiafei** [comment]
OK, 谢谢，我尝试一下~
