### ISSUE TITLE
在Centos7.3下无法编译，请问该怎么解决？

### ISSUE THREAD

**Issue by fengme** [brpc/brpc#224]
/brpc-master/src/bthread/bthread.cpp:52:7: 错误：‘::google’尚未声明
     ::google::RegisterFlagValidator(&FLAGS_bthread_min_concurrency,
       ^
make[2]: *** [src/CMakeFiles/OBJ_LIB.dir/bthread/bthread.cpp.o] 错误 1
make[1]: *** [src/CMakeFiles/OBJ_LIB.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by jamesge** [comment]
Fixed in [this commit](https://github.com/brpc/brpc/commit/bea9ac8f703c211541a41c961d720028cd8951d3). Thanks for reporting.
