### ISSUE TITLE
能否提供java client与brpc通信的实例？

### ISSUE THREAD

**Issue by fengme** [brpc/brpc#225]
建议，不是bug

**Comment by jamesge** [comment]
可以使用http+json通信。

**Comment by fengnex** [comment]
内置的HTTP的性能如何？

**Comment by fengnex** [comment]
建议提供java的客户端，可以做长连接、序列化等工作

**Comment by jamesge** [comment]
brpc的http性能很好。

**Comment by jamesge** [comment]
你说的“服务治理”指什么

**Comment by lik0914** [comment]
@jamesge 指的就是，服务发现， 注册， 负载均衡之类的

**Comment by jamesge** [comment]
client直接支持负载均衡，名字服务（服务发现）和机器管理结合比较紧密，一般各个公司有自己的方案，brpc一侧则需要继承NamingService做定制，默认提供的是更宽泛的dns，file-ns之类的，使用方式文档里有介绍。

**Comment by billowqiu** [comment]
刚看到这个，https://github.com/baidu/brpc-java
