### ISSUE TITLE
系统最大并发数的应用与实践

### ISSUE THREAD

**Issue by gydong** [brpc/brpc#229]
@jamesge 请教一下，系统最大并发设置方面的心得。其实，也就是想问一下little‘s law的应用和实践方式。读了这方面的文档之后，我理解的一种应用方式是，通过线下压测某个服务A，当接近服务瓶颈的时候记录一下服务的平均响应时间和对应的QPS，然后得出max_concurrency，以此作为服务A最大并发数设置到系统中。但是，看了[这个知乎文章](https://www.zhihu.com/question/65370268/answer/231801580)后，有一些新的疑问：
1. 上游服务A，下游服务B，为什么不直接去评估A的容量，而是需要通过B间接评估A的容量？
2. 有没有相关文档介绍一下，具体如何做到“一层层地迭代上去从而计算出复杂系统同时能处理的最大请求数”？

**Comment by jamesge** [comment]
1. 这个问题其实是有二义性的，比如A是http proxy，那么A自身的容量，也就是转发能力，多半是非常高的，但A后端的模块如果是复杂的业务系统，吞吐一般就会很有限。我们谈A的容量，大概率指的是A后面整个系统的容量，而不是单单它的转发能力。
2. 就是“串行相加，并行取min”。但这个计算方法的问题在于要求每个模块都有专门的接口来计算这个值，从而使得可以一层层迭代上去计算出系统的总容量，在实践中是有困难的，毕竟总是有legacy服务。所以压测更短平快一些。

**Comment by gydong** [comment]
1. 明白了。
2. 上游服务A，下游服务B，假设B是服务请求链上的最末端节点且B的容量已知为V(B)。那么，在评估V(A)的时候是保证V(B)足够（部署足够的服务器，不让B成为瓶颈）的情况下去压测A服务并评估V(A)吗？然后，V(B) + V(A) 就是A和B组成的系统的总容量，是这样吗？（之所以有这样的疑问，是感觉压测A服务时B服务成为瓶颈的话会影响到V(A)的评估值）

**Comment by jamesge** [comment]
和足够无关。注意容量不是QPS，而是系统中同时能处理的最大请求数。A和B是串行的话，不管足够与否，系统总容量都是V(A)+V(B)。A和B之间的关系很像流水线。这个计算方法的直觉理解是很简单的，就把容量理解为槽位，槽位越多可同时容纳的请求就越多，串行自然是槽位数想加，并行是槽位数取min（否则一个分支就槽位不够了）。

**Comment by gydong** [comment]
容量这个含义我倒是理解，QSP、latency和容量以及他们之间的关系也能在我脑中具象化。但我还是感觉，上游服务的容量评估，已经包含了其下游所有服务的评估。具体来讲，一个请求如果正在下游服务B中处理，那么一定在上游服务中也对应一个session。这一点和流水线不一样，流水线是有去无回，而服务间的请求是有去有回的。
