### ISSUE TITLE
cpu profiler 问题

### ISSUE THREAD

**Issue by machaelliu** [brpc/brpc#231]
你好，文档中说使用 cpu profiler需要链接 libtcmalloc_and_profiler.a，这是指在编译 brpc 源码时链接 libtcmalloc_and_profiler.a，还是使用brpc 库的程序中链接  libtcmalloc_and_profiler.a ？

**Comment by cxxcunow** [comment]
你的问题解决了吗？我试验了直接brpc连接，如果再编译example，运行就会报错释放两次内存。后来你怎么弄的？
