### ISSUE TITLE
基于brpc的全链路超时控制？

### ISSUE THREAD

**Issue by feng-y** [brpc/brpc#232]
请问下如何基于brpc实现全链路超时控制，一个rpc调用的超时时间不再是初始化时设置的值，而是全链路上这个调用剩余的最大时间。

**Comment by jamesge** [comment]
rpc之间一般还有业务逻辑，这部分代码占用的时间对rpc是不可知的，并不是一个通用问题。另一方不同机器上的wall-time即使开启了ntp，也可能由于人为调整而不同步，需要用户结合自己的服务特点来进行设计和容忍。
