### ISSUE TITLE
内置服务里的growth是什么含义

### ISSUE THREAD

**Issue by tjb1216** [brpc/brpc#234]
如题，文档里面关于内置服务唯独缺了growth的说明，求解惑

**Comment by gydong** [comment]
指示内存使用增长情况。

**Comment by jamesge** [comment]
只看malloc不管free。

**Comment by yuinm** [comment]
growth 是不是表示最大值啊？ 

比如：第一天我把内存分配的特别大，程序一直运行，第二天再次看一下growth的指标，并且做diff发现输出的是"no node print"。没明白growth的原理，如果只考虑malloc不管free,这个growth看到的内存应该是一直上涨的状况才对啊(一天比一天大)。  

看这个的起因是线上的服务内存突然暴涨 之后又降了回来， 用涨之前和涨之后的growth做了一下diff ，生成diff的图表示的意义没想明白，来这里请教一下..

@jamesge @gydong 有时间的时候麻烦解答一下,感谢。

**Comment by jamesge** [comment]
growth就是只考虑malloc不考虑free

**Comment by yuinm** [comment]
哦 , 明白了, 谢谢。

**Comment by jamesge** [comment]
FYI @yuinm https://github.com/gperftools/gperftools/blob/f47a52ce85c3d8d559aaae7b7a426c359fbca225/src/page_heap.cc#L644

**Comment by yuinm** [comment]
好的， 我去研究下..
