### ISSUE TITLE
lb支持wrr

### ISSUE THREAD

**Issue by tjb1216** [brpc/brpc#235]
lalb虽然很强大，但我们现在有需求需要手动控制权重，即服务注册的时候配上weight，客户端根据weight来访问下游服务。
看源码发现Naming_service里ServerNode的定义了除了addr还有一个tag，文档中有提到tag是给partition channel用的，如果我们确定不使用partition channel，我们能否用这个tag来实现wrr？或者有其他更好的建议？

**Comment by tjb1216** [comment]
也就是说我们可以基于tag实现一个wrr，对吧？

**Comment by jamesge** [comment]
整数倍的weight，不是通用的，且显然不能很大。
