### ISSUE TITLE
sh config_brpc.sh

### ISSUE THREAD

**Issue by wclin88** [brpc/brpc#237]
sh config_brpc.sh --headers=/usr/include --libs=/usr/lib64
能否让这个支持指定多个目录

**Comment by jamesge** [comment]
把参数用引号括起来，多路径用空格分隔。

**Comment by dreamingpig** [comment]
能给一个示例么？尝试了空格分隔的多路径，失败了

**Comment by jamesge** [comment]
--headers="PATH1 PATH2"

**Comment by alanxzj** [comment]
我也碰到这个问题了，所需要的库安装在不同目录上。
最后是直接翻看脚本才解决。
建议在脚本加上简单实用说明。
当然，加快完善cmake支持最有效：）
