### ISSUE TITLE
Centos7.2+CMake3.10.2构建失败

### ISSUE THREAD

**Issue by alanxzj** [brpc/brpc#240]
直接cmake失败，修改根目录的 CMakeLists.txt如下，可以cmake通过，但是make失败；
相同环境下直接用config_brpc.sh可以成功编译；
cmake出错的具体原因还在查，先mark一下

diff --git a/CMakeLists.txt b/CMakeLists.txt
index c80712d..317e167 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -269,7 +269,7 @@ file(GLOB PROTOS "${CMAKE_SOURCE_DIR}/src/*.proto")
 list(APPEND PROTO_FLAGS -I${CMAKE_CURRENT_BINARY_DIR})
 foreach(PROTO ${PROTOS})
     get_filename_component(PROTO_WE ${PROTO} NAME_WE)
--   list(APPEND PROTO_SRCS "${CMAKE_CURRENT_BINARY_DIR}/${PROTO_WE}.pb.cc")
++   list(APPEND PROTO_SRCS "${CMAKE_CURRENT_BINARY_DIR}/src/${PROTO_WE}.pb.cc")
     execute_process(
         COMMAND ${PROTOBUF_PROTOC_EXECUTABLE} ${PROTO_FLAGS} --cpp_out=${CMAKE_CURRENT_BINARY_DIR} --proto_path=${PROTOBUF_INCLUDE_DIR} --proto_path=${CMAKE_SOURCE_DIR}/src ${PROTO}
         WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
@@ -279,7 +279,7 @@ endforeach()
 file(GLOB BRPC_PROTOS "src/brpc/*.proto")
 foreach(PROTO ${BRPC_PROTOS})
     get_filename_component(PROTO_WE ${PROTO} NAME_WE)
--   list(APPEND PROTO_SRCS "${CMAKE_CURRENT_BINARY_DIR}/brpc/${PROTO_WE}.pb.cc")
++   list(APPEND PROTO_SRCS "${CMAKE_CURRENT_BINARY_DIR}/src/brpc/${PROTO_WE}.pb.cc")
     execute_process(
         COMMAND ${PROTOBUF_PROTOC_EXECUTABLE} ${PROTO_FLAGS} --cpp_out=${CMAKE_CURRENT_BINARY_DIR} --proto_path=${PROTOBUF_INCLUDE_DIR} --proto_path=${CMAKE_SOURCE_DIR}/src --proto_path=${CMAKE_SOURCE_DIR}/src/brpc/ ${PROTO}
         WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
@@ -289,7 +289,7 @@ endforeach()
 file(GLOB BRPC_POLICY_PROTOS "src/brpc/policy/*.proto")
 foreach(PROTO ${BRPC_POLICY_PROTOS})
     get_filename_component(PROTO_WE ${PROTO} NAME_WE)
--   list(APPEND PROTO_SRCS "${CMAKE_CURRENT_BINARY_DIR}/brpc/policy/${PROTO_WE}.pb.cc")
++   list(APPEND PROTO_SRCS "${CMAKE_CURRENT_BINARY_DIR}/src/brpc/policy/${PROTO_WE}.pb.cc")
     execute_process(
         COMMAND ${PROTOBUF_PROTOC_EXECUTABLE} ${PROTO_FLAGS} --cpp_out=${CMAKE_CURRENT_BINARY_DIR} --proto_path=${PROTOBUF_INCLUDE_DIR} --proto_path=${CMAKE_SOURCE_DIR}/src --proto_path=${CMAKE_SOURCE_DIR}/src/brpc/policy ${PROTO}
         WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
@@ -311,7 +311,7 @@ if(BUILD_UNIT_TESTS)
 endif()
 add_subdirectory(tools)

-file(COPY ${CMAKE_CURRENT_BINARY_DIR}/idl_options.pb.h
+file(COPY ${CMAKE_CURRENT_BINARY_DIR}/src/idl_options.pb.h
      DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/output/include)
 file(COPY ${CMAKE_CURRENT_BINARY_DIR}/brpc/
         DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/output/include/brpc/

**Comment by alanxzj** [comment]
补充： 
如顶楼帖子修改CMakeLists.txt后，cmake通过；
但是make失败的出错信息如下，应该是修改CMakeLists.txt路径后带来的问题：

/opt/thirdparty_src/brpc_cmake.git/src/brpc/nshead_meta.pb.cc: 在函数‘void protobuf_src_2fbrpc_2fnshead_5fmeta_2eproto::AddDescriptorsImpl()’中:
/opt/thirdparty_src/brpc_cmake.git/src/brpc/nshead_meta.pb.cc:121:5: 错误：‘::protobuf_brpc_2foptions_2eproto’尚未声明
   ::protobuf_brpc_2foptions_2eproto::AddDescriptors();
     ^

**Comment by zyearn** [comment]
cmake的生成的原始错误方便贴一下吗 @alanxzj

**Comment by alanxzj** [comment]
我在源码内根目录 /opt/thirdparty_src/brpc_cmake.git/ 执行cmake .   。
源码未改动全新clone时候的出错信息：
CMake Error at CMakeLists.txt:314 (file):
  file COPY cannot find
  "/opt/thirdparty_src/brpc_cmake.git/idl_options.pb.h".

我对根目录CMakeLists.txt做了如下改动，源码内编译CMAKE_CURRENT_BINARY_DIR此时应该指向根目录：
-file(COPY ${CMAKE_CURRENT_BINARY_DIR}/idl_options.pb.h
+file(COPY ${CMAKE_CURRENT_BINARY_DIR}/src/idl_options.pb.h
#################################
执行了上面改动后，接着执行cmake的出错：
CMake Error at src/CMakeLists.txt:13 (add_library):
  Cannot find source file:
    /opt/thirdparty_src/brpc_cmake.git/idl_options.pb.cc

我对根目录CMakeLists.txt做了如下改动后，单纯cmake可以通过，但是make出现2楼帖子的错误:
272行如下改动：
-- list(APPEND PROTO_SRCS "${CMAKE_CURRENT_BINARY_DIR}/${PROTO_WE}.pb.cc")
++ list(APPEND PROTO_SRCS "${CMAKE_CURRENT_BINARY_DIR}/src/${PROTO_WE}.pb.cc")
282行如下改动：
-- list(APPEND PROTO_SRCS "${CMAKE_CURRENT_BINARY_DIR}/brpc/${PROTO_WE}.pb.cc")
++ list(APPEND PROTO_SRCS "${CMAKE_CURRENT_BINARY_DIR}/src/brpc/${PROTO_WE}.pb.cc")
292行如下改动：
-- list(APPEND PROTO_SRCS "${CMAKE_CURRENT_BINARY_DIR}/brpc/policy/${PROTO_WE}.pb.cc")
++ list(APPEND PROTO_SRCS "${CMAKE_CURRENT_BINARY_DIR}/src/brpc/policy/${PROTO_WE}.pb.cc")

**Comment by wei7202839** [comment]
这个问题后来解决了吗  我也遇到了类似的问题
pb.cc文件编译一直失败  非常操蛋

**Comment by wei7202839** [comment]
我这边遇到的错误:
[ 88%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/brpc/serialized_request.cpp.o
[ 88%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/brpc/span.cpp.o
[ 89%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/brpc/channel.cpp.o
[ 89%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/brpc/http_header.cpp.o
[ 89%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/brpc/policy/mongo.pb.cc.o
/home/appweb/sources/brpc/src/brpc/policy/mongo.pb.cc: In function ‘void brpc::policy::protobuf_AddDesc_src_2fbrpc_2fpolicy_2fmongo_2eproto()’:
/home/appweb/sources/brpc/src/brpc/policy/mongo.pb.cc:138:3: error: ‘protobuf_AddDesc_brpc_2foptions_2eproto’ is not a member of ‘brpc’
   ::brpc::protobuf_AddDesc_brpc_2foptions_2eproto();
   ^~
make[2]: *** [src/CMakeFiles/OBJ_LIB.dir/brpc/policy/mongo.pb.cc.o] Error 1
make[1]: *** [src/CMakeFiles/OBJ_LIB.dir/all] Error 2
make: *** [all] Error 2

**Comment by alanxzj** [comment]
没有解决，我后来直接用 config_brpc.sh 编译了，后来一堆业务问题，就没时间跟进这个了。
如果你解决了请分享一下 @wei7202839
