### ISSUE TITLE
bthread_mutex_lock和bthread_mutex_unlock同步代码块修改的数据是不是对其他线程提供内存可见性

### ISSUE THREAD

**Issue by bozhbo** [brpc/brpc#241]
bthread_mutex_lock和bthread_mutex_unlock同步代码块修改的数据是不是对其他线程提供内存可见性
是否与pthread_mutex有一直的行为表现？

**Comment by jamesge** [comment]
是一致的，lock含acquire语意，unlock含release语意。这样当另一个线程成功地lock时，所带的acquire fence会和刚刚unlock的那个线程中的release fence配对，从而保证发生在unlock前的所有内存修改可见。
