### ISSUE TITLE
关于rdma

### ISSUE THREAD

**Issue by shangdehao1** [brpc/brpc#244]
想问一下，rdma大概什么时候可以开源。谢谢

**Comment by gydong** [comment]
搭车提问，RDMA需要特殊的网卡支持吗？

**Comment by jamesge** [comment]
rmda版本在内部使用中，是基于openucx的，但整体评估下来依赖比较多，不便于开源。基于ibverbs的新版在开发中，应该会开源，仍需要等一段时间。

**Comment by shangdehao1** [comment]
@gydong 需要特定的网卡来支持的，也可以用软件来搭rdma环境，比如soft-iwrap, sofa-roce, 不过很耗cpu

**Comment by Tuvie** [comment]
@lingji 新版本用了libibverbs和librdmacm。理论上ROCE和Infiniband的接口是一样的，主体部分代码应该是通用的。但我们目前只在ROCE网络上测试过，用的是Mellanox和Broadcom的卡。

**Comment by lingji** [comment]
@Tuvie 谢谢！听说IB 大约是2us左右。RoCE 相比通过Linux 协议栈，时延减少多少呢（当然肯定会比IB高）？对于数据库复制这种来说，RDMA的使用相对来说效果也会更好。

**Comment by Tuvie** [comment]
@lingji 现在ROCE的极限时延和IB差距已经不太大了（估计也就1-2个us）。ROCE和正常的TCP协议比起来，单报文极限时延可以减少15us以上。当然这个提升效果是和你的应用模式、流量大小、负载程度都有关系的。

**Comment by lingji** [comment]
测试linux 的协议栈大约是80us左右（以太网环境），RoCE 不知道平均多少（减少15us ?)？另外，RoCE 是不是对交换机有也要求，还是普遍的交换机就可以呢？

**Comment by Tuvie** [comment]
@lijing 80us不知道你是在什么样的情况下测试出来的，脱离场景绝对数值意义不大。RoCE一般要求交换机至少要支持PFC。当然，如果你只有两台机器互联互通，那么就无所谓了。

**Comment by lingji** [comment]
@Tuvie @jamesge @shangdehao1 #292 这个PR 的状态没变化。。
