### ISSUE TITLE
关于多线程使用channel的问题

### ISSUE THREAD

**Issue by bozhbo** [brpc/brpc#248]
brpc::Controller cntl;
redis_channel.CallMethod(NULL, &cntl, &request, &response, NULL/*done*/);

多线程同时同步调用对Redis服务器，当前的bthread应该是被挂起，等redis的响应消息回来再唤醒执行，想问一下响应消息是如果知道应该唤醒哪个bthread继续执行？

redis客户端应该只会和Redis服务器建立1条连接吧？

**Comment by gydong** [comment]
依据的是，pipeline中一个请求对应一个响应的原理。即先发送的请求，一定先接收到其响应。这样只要把bthread放到一个队列结构中即可，收到一个响应就从队首取一个bthread唤醒。
