### ISSUE TITLE
server端在ProcessRequest callback 抛出非预期signal

### ISSUE THREAD

**Issue by feng-y** [brpc/brpc#249]
使用baidu_std协议，client端在SerializeRequest中也会检查IsInitialized，如果失败的话不会发送到server端，请问下下面的调用栈是如何产生的？

Thread 17 (Thread 0x7ff62b5b3700 (LWP 29146)):
#0  0x00007ff72f2d4ef0 in base::internal::SpinLockDelay(int volatile*, int, int) () from /usr/lib64/libtcmalloc_and_profiler.so.4
#1  0x00007ff72f2d337c in SpinLock::SlowLock() () from /usr/lib64/libtcmalloc_and_profiler.so.4
#2  0x00007ff72f2c3be7 in tcmalloc::CentralFreeList::InsertRange(void*, void*, int) () from /usr/lib64/libtcmalloc_and_profiler.so.4
#3  0x00007ff72f2c7125 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned long, int) () from /usr/lib64/libtcmalloc_and_profiler.so.4
#4  0x00007ff72f2c7867 in tcmalloc::ThreadCache::Scavenge() () from /usr/lib64/libtcmalloc_and_profiler.so.4
#5  0x00007ff72f2d636f in tc_free () from /usr/lib64/libtcmalloc_and_profiler.so.4
#6  0x0000000000694b91 in bfd_elf64_slurp_symbol_table ()
#7  0x00000000006974db in _bfd_elf_canonicalize_symtab ()
#8  0x00000000006849a1 in FileLinePrinter(int, void*, char*, unsigned long, unsigned long) ()
#9  0x00000032b9215475 in google::SymbolizeAndDemangle(void*, char*, int) () from /usr/lib/libglog.so.0
#10 0x00000032b9215825 in google::(anonymous namespace)::DumpStackFrameInfo(char const*, void*) () from /usr/lib/libglog.so.0
#11 0x00000032b92162b2 in google::(anonymous namespace)::FailureSignalHandler(int, siginfo*, void*) () from /usr/lib/libglog.so.0
**#12 signal handler called
#13 0x00000000005b2d1d in tt_serving::tp_util::UserFrequencyRecordList::IsInitialized() const ()**
#14 0x0000000000542cd2 in tt_serving::tp_show::LeafRequest_UserInfo::IsInitialized() const ()
#15 0x0000000000542efd in tt_serving::tp_show::LeafRequest::IsInitialized() const ()
#16 0x00000032b82e89a1 in google::protobuf::MessageLite::ParseFromCodedStream(google::protobuf::io::CodedInputStream*) () from /usr/lib64/libprotobuf.so.11
#17 0x00007ff72dcde407 in brpc::ParsePbFromIOBuf(google::protobuf::Message*, butil::IOBuf const&) () from /usr/lib64/libbrpc.so.0.0.5
#18 0x00007ff72dcbedbb in brpc::ParseFromCompressedData(butil::IOBuf const&, google::protobuf::Message*, brpc::CompressType) () from /usr/lib64/libbrpc.so.0.0.5
#19 0x00007ff72dd7d455 in brpc::policy::ProcessRpcRequest(brpc::InputMessageBase*) () from /usr/lib64/libbrpc.so.0.0.5
#20 0x00007ff72dcce06a in brpc::ProcessInputMessage(void*) () from /usr/lib64/libbrpc.so.0.0.5
#21 0x00007ff72dccf1bf in brpc::InputMessenger::OnNewMessages(brpc::Socket*) () from /usr/lib64/libbrpc.so.0.0.5
#22 0x00007ff72dd13fdd in brpc::Socket::ProcessEvent(void*) () from /usr/lib64/libbrpc.so.0.0.5
#23 0x00007ff72dc22f25 in bthread::TaskGroup::task_runner(long) () from /usr/lib64/libbrpc.so.0.0.5
#24 0x00007ff72dc0af01 in bthread_make_fcontext () from /usr/lib64/libbrpc.so.0.0.5
#25 0x0000000000000000 in ?? ()

**Comment by jamesge** [comment]
看看是不是请求的生命周期有问题

**Comment by feng-y** [comment]
这部分调用栈还没有进入业务代码，请求的生命周期可以从哪些方面可以查看？

**Comment by jamesge** [comment]
就是提前被删除，多线程竞争之类的。
