### ISSUE TITLE
Funcation names, some are HasFun(), while others are has_fun()

### ISSUE THREAD

**Issue by luopeien** [brpc/brpc#25]
Why are some functions named CamelCase while others are camel_case?

example:
    // Whether the underlying channel is using SSL
    bool is_ssl() const;
    
    // Resets the Controller to its initial state so that it may be reused in
    // a new call.  Must NOT be called while an RPC is in progress.
void Reset() { InternalReset(false); }

**Comment by jamesge** [comment]
https://google.github.io/styleguide/cppguide.html#Function_Names
In short, foo_bar() means the function does very little things and being very quick (mostly getter and setter). CamelCases means the function is not trivial.
