### ISSUE TITLE
关于在bthread使用跨进程信号量、文件锁、pthread提供的信号量等

### ISSUE THREAD

**Issue by colaghost** [brpc/brpc#252]
如题，在bthread中使用这些是否可能有死锁问题，pthread提供的在bthread下都看到相关的替代函数，但是跨进程相关的我可以放心使用信号量跟文件锁这些吗？还有引入的第三方库本身支持多线程的话他们使用这些相关的同步机制在bthread中又可能会引起问题吗？如果会的话有没有方式去避免？

**Comment by jamesge** [comment]
这类问题存在于任何使用了有限线程（线程池）的rpc框架中，有概率但一般不用担心。

**Comment by colaghost** [comment]
bthread的切换时机是不是跟一般协程实现一样都是在发生网络IO的时候？

**Comment by jamesge** [comment]
bthread只有在调用了可能阻塞的bthread相关函数时才会主动发生切换，大部分情况下就是发起同步RPC时。
