### ISSUE TITLE
tools: rpc perf

### ISSUE THREAD

**Issue by yjhjstz** [brpc/brpc#254]
> https://svn.baidu.com/com-test/trunk/public/rpc-perf/

这个工具外部怎么获取？

**Comment by jamesge** [comment]
这是曾经做测试的内部代码，应该不会开源了。

**Comment by yjhjstz** [comment]
有替代的方案吗？

**Comment by jamesge** [comment]
你说的替代方案是指什么？这就是个性能测试，不是解决具体问题的方案。你可以结合自己的场景做一些有针对性的测试或比对，有问题再提出来。
