### ISSUE TITLE
IOBuf支持多种分配方式

### ISSUE THREAD

**Issue by gongweibao** [brpc/brpc#255]
## 事情的背景：
   -  paddle在实现parameter server的时候发现性能很差，进一步的分析发现是[数据copy导致的](https://github.com/PaddlePaddle/Paddle/issues/8638#issuecomment-370207803)
       
## 调研：
   - 我们调研了一下TensorFlow，发现他们裸写了一个[GRPC的数据格式](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/grpc_tensor_coding.cc#L54)， 直接引用数据，从而避免了数据拷贝。但是这种方式有点不好维护。

## 问题：
   - 不知道BRPC如何处理较大数据的发送问题？能否有较好的办法避免数据拷贝，以及Package的性能消耗等？。我们考虑改成BRPC的调用。

**Comment by E-HERO** [comment]
关于发送建议看看 https://github.com/brpc/brpc/blob/master/docs/en/io.md
代码可以看看 https://github.com/brpc/brpc/blob/master/src/brpc/socket.cpp 里面有一个StartWrite方法
我记得brpc好像也是用的数据引用，没有拷贝数据。大概流程是rpc发送数据先看这个fd是否在发送数据，如果在发送就把消息加到head直接返回，如果没有发送数据，本地会先发送一次，如果没有发完（即大消息）就起一个bthread来发送，发完后发现有新加入的数据，这个bthread还会发送，直到没有新加数据为止。
具体可以结合文档和代码看看，比较清楚

**Comment by jamesge** [comment]
用[附件](https://github.com/brpc/brpc/blob/master/docs/cn/client.md#attachment)传输数据。要完全绕过拷贝，注意在生成数据时就要直接写入[butil::IOBuf](https://github.com/brpc/brpc/blob/master/docs/cn/iobuf.md)，最后move入附件。数据的格式由用户自己搞定。
也可以通过定制protobuf的生成器也可以给pb增加零拷贝类型，不过那就是很大的改动了。

**Comment by gongweibao** [comment]
> 注意在生成数据时就要直接写入butil::IOBuf

感谢。我们的使用场景首先是把数据从GPU拷贝到内存，这个时候使用[页锁定内存](http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1gb65da58f444e7230d3322b6126bb4902)是[最快的](https://github.com/PaddlePaddle/Paddle/issues/8638#issuecomment-369912156)。我能直接引用这样的内存吗?

**Comment by TomorrowIsAnOtherDay** [comment]
赞这种讨论，厂里的氛围越来越好了

**Comment by jamesge** [comment]
包括对pinned memory和DIO(@ipconfigme)的支持

**Comment by yongs207** [comment]
关于pinned memory和DIO的支持是已经在进行吗？大概什么时候会开源？
