### ISSUE TITLE
CMake 构建 打开BRPC_WITH_GLOG 标签遇到问题

### ISSUE THREAD

**Issue by mfslog** [brpc/brpc#256]
1.[工程根目录下CMakeLists.txt](https://github.com/brpc/brpc/blob/master/CMakeLists.txt)中的选项是：BRPC_WITH_GLOG (line:18),但是在[src目录下中的CMakeLists.txt是：](https://github.com/brpc/brpc/blob/master/src/CMakeLists.txt) WITH_GLOG
2.[src 目录下CMakeLists.txt](https://github.com/brpc/brpc/blob/master/src/CMakeLists.txt)WITH_GLOG 判断的时候只对BRPC动态库进行了连接，没有对静态库连接
if(WITH_GLOG)
    target_link_libraries(brpc-shared ${GLOG_LIB})
endif()
3.打开BRPC_WITH_GLOG 后编译报错：
/home/mfs/hub/brpc/tools/rpc_press/rpc_press_impl.cpp: In member function ‘virtual void pbrpcframework::ImportErrorPrinter::AddError(const string&, int, int, const string&)’:
/home/mfs/hub/brpc/tools/rpc_press/rpc_press_impl.cpp:44:16: error: ‘ERROR’ was not declared in this scope
         LOG_AT(ERROR, filename.c_str(), line) << message;
                ^
/home/mfs/hub/brpc/tools/rpc_press/rpc_press_impl.cpp:44:16: note: suggested alternative:
In file included from /usr/local/include/glog/logging.h:512:0,
                 from /home/mfs/hub/brpc/src/butil/logging.h:34,
                 from /home/mfs/hub/brpc/src/bthread/types.h:24,
                 from /home/mfs/hub/brpc/src/bthread/bthread.h:24,
                 from /home/mfs/hub/brpc/tools/rpc_press/rpc_press_impl.cpp:22:
/usr/local/include/glog/log_severity.h:54:3: note:   ‘google::ERROR’
   ERROR = GLOG_ERROR, FATAL = GLOG_FATAL;
   ^
/home/mfs/hub/brpc/tools/rpc_press/rpc_press_impl.cpp:44:45: error: ‘LOG_AT’ was not declared in this scope
         LOG_AT(ERROR, filename.c_str(), line) << message;
                                             ^
tools/rpc_press/CMakeFiles/rpc_press.dir/build.make:158: recipe for target 'tools/rpc_press/CMakeFiles/rpc_press.dir/rpc_press_impl.cpp.o' failed
make[2]: *** [tools/rpc_press/CMakeFiles/rpc_press.dir/rpc_press_impl.cpp.o] Error 1
CMakeFiles/Makefile2:383: recipe for target 'tools/rpc_press/CMakeFiles/rpc_press.dir/all' failed
make[1]: *** [tools/rpc_press/CMakeFiles/rpc_press.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zyearn** [comment]
感谢反馈已修复。

关于2，静态库本来就是.o文件的打包，不需要在cmake里加上glog库，在链接executable的时候把glog加上去会更清楚一点
