### ISSUE TITLE
使用brpc的client端，若使用异步接口，则无返回，如果调试

### ISSUE THREAD

**Issue by mltrees** [brpc/brpc#262]
你好，我打算使用项目中的http client接口，目前使用example中的http_client没有问题，但该接口是阻塞的，我想增加一个回调函数，使用变成异步接口，但修改后无反应。增加的异步接口主要为：
增加了一个异步回调函数：void HandleEchoResponse(brpc::Controller* cntl,
        google::protobuf::Message* response )
在main中增加了异步函数的定义：
    google::protobuf::Message* response = NULL;
    google::protobuf::Closure* done = brpc::NewCallback(
        &HandleEchoResponse, cntl, response);
以及修改了channel的调用
channel.CallMethod(NULL, cntl, NULL, response, done);

但照此修改后，此接口无返回，无法进入回调函数

ps：若使用channel.CallMethod(NULL, cntl, NULL, response, NULL);，则函数会正常运行
请问这是什么问题

**Comment by mltrees** [comment]
附测试代码：

#include <gflags/gflags.h>
#include <brpc/channel.h>

DEFINE_string(d, "", "POST this data to the http server");
DEFINE_string(load_balancer, "", "The algorithm for load balancing");
DEFINE_int32(timeout_ms, 1000, "RPC timeout in milliseconds");
DEFINE_int32(max_retry, 3, "Max retries(not including the first RPC)");
DEFINE_string(protocol, "http", "http or h2c");

void HandleEchoResponse(
        brpc::Controller* cntl,
        google::protobuf::Message* response ) {
    // std::unique_ptr makes sure cntl/response will be deleted before returning.
    std::unique_ptr<brpc::Controller> cntl_guard(cntl);
    std::unique_ptr<google::protobuf::Message> response_guard(response);

    if (cntl->Failed()) {
        LOG(WARNING) << "Fail to send EchoRequest, " << cntl->ErrorText();
        return;
    }
    LOG(ERROR) << "Received response from " << cntl->remote_side() << " (attached="
        << cntl->response_attachment() << ")"
        << " latency=" << cntl->latency_us() << "us";
}


int main(int argc, char* argv[]) {
    google::ParseCommandLineFlags(&argc, &argv, true);
    if (argc != 2) {
        LOG(ERROR) << "Usage: ./http_client \"www.foo.com\"";
        return -1;
    }
    char* url = argv[1];
    brpc::Channel channel;

    brpc::ChannelOptions options;
    options.protocol = FLAGS_protocol;
    options.timeout_ms = FLAGS_timeout_ms/*milliseconds*/;
    options.max_retry = FLAGS_max_retry;

    // example::EchoResponse* response = new example::EchoResponse();

    // Initialize the channel, NULL means using default options.
    // options, see `brpc/channel.h'.
    if (channel.Init(url, FLAGS_load_balancer.c_str(), &options) != 0) {
        LOG(ERROR) << "Fail to initialize channel";
        return -1;
    }
    // We will receive response synchronously, safe to put variables
    // on stack.
    brpc::Controller* cntl = new brpc::Controller();

    cntl->http_request().uri() = url;
    if (!FLAGS_d.empty()) {
        cntl->http_request().set_method(brpc::HTTP_METHOD_POST);
        cntl->request_attachment().append(FLAGS_d);
    }
    google::protobuf::Message* response = NULL;
    google::protobuf::Closure* done = brpc::NewCallback(
        &HandleEchoResponse, cntl, response);

    // Because `done'(last parameter) is NULL, this function waits until
    // the response comes back or error occurs(including timedout).
    done = nullptr; // make this, the program work well, but comment this, there is no response
    channel.CallMethod(NULL, cntl, NULL, response, done);
    if (cntl->Failed()) {
        std::cerr << cntl->ErrorText() << std::endl;
        return -1;
    }
    return 0;
}

**Comment by mltrees** [comment]
Makefile：
TARGET=client_test
CXX=g++
CXXFLAGS=-std=c++0x -g -O0
SRC=test_client.cpp
OBJ=$(addsuffix .o, $(basename $(SRC)))
BRPC_PATH=/home/opensrc/brpc/build
HDRS=$(BRPC_PATH)/output/include
LIBS=$(BRPC_PATH)/output/lib
LIBS+=/home/zhangmaolin/usr/local/lib

HDRPATHS = $(addprefix -I, $(HDRS))
LIBPATHS = $(addprefix -L, $(LIBS))

STATIC_LINKINGS=-lbrpc -lprotobuf -lssl
#DYNAMIC_LINKINGS=-lpthread -lrt -lssl -lcrypto -ldl -lz -lgflags -lleveldb -ltcmalloc_and_profiler
DYNAMIC_LINKINGS=-lpthread -lrt -lssl -lcrypto -ldl -lz -lgflags -lleveldb


$(TARGET):$(OBJ)
	@echo "Linking $@"
	@echo "LIBPATHS=$(LIBPATHS)"
	$(CXX) $(LIBPATHS) -Xlinker "-(" $^ -Wl,-Bstatic $(STATIC_LINKINGS) -Wl,-Bdynamic -Xlinker "-)" $(DYNAMIC_LINKINGS) -o $@


%.o:%.cpp
	@echo "Compile $@"
	@$(CXX) -c $(HDRPATHS) $(CXXFLAGS) $< -o $@


%.o:%.cc
	@echo "Compile $@"
	@$(CXX) -c $(HDRPATHS) $(CXXFLAGS) $< -o $@

.PHONY:clean
clean:
	@echo "Cleaning"
	@rm -rf $(TARGET) $(OBJ)

**Comment by jamesge** [comment]
退出main函数就意味着程序退出了，rpc还来不及结束。

**Comment by mltrees** [comment]
是这个问题，多谢
