### ISSUE TITLE
brpc和调用链追踪的融合

### ISSUE THREAD

**Issue by dreamingpig** [brpc/brpc#264]
线程情况下，可以通过thread local的方式对业务隐藏调用追踪链追踪的细节。在brpc使用bthread的情况下，怎样实现可以达到对业务隐藏？

**Comment by jamesge** [comment]
用bthread local或者内置的rpcz

**Comment by tjb1216** [comment]
rpcz只能看到服务内部调用的一些细节，如果想要看到各个服务的调用链路，还是得自己实现。@dreamingpig 是想实现这么一个功能？
@jamesge rpcz的协议和数据都是可用的，需要做的只是把这些数据串起来，放到一个平台去分析展示？

**Comment by jamesge** [comment]
服务间的调用链路是有的，默认的rpcz实现会有链向目标服务的rpcz内置页面的链接，点击就跳过去了。方法论就是google dapper那套。但brpc并不提供把单机数据汇总起来的服务。

**Comment by dreamingpig** [comment]
@tjb1216 我们公司内部有调用链追踪的平台，也是类似google dapper那一套。我们自己在基础类库加了数据发送。现在想切换到brpc，所以支持类似的功能。

**Comment by tjb1216** [comment]
我们遇到的问题是，在切换brpc之前，我们用zipkin做了一套全链路监控系统，切换之后，brpc自带rpcz，但是缺少多个服务的调用链路，再使用zipkin感觉又有些重复，对服务性能也有影响，请问有什么好的建议？

**Comment by dreamingpig** [comment]
我们还没有开始对接brpc，现在还在看代码和内部测试。brpc代码里span的定义和我们的定义字段基本一致，感觉继承一下就好。

**Comment by tjb1216** [comment]
message EndPoint {
    // process name
    string serviceName = 1;
    string ipv4 = 2;
}

message Annotation {
    // unit: microsecond
    int64 timestamp = 1;
    // Should be one of: cs, cr, ss, sr, which stands for
    // client send, client receive, server send, server receive respectively.
    string value = 2;
    EndPoint endpoint = 3;
}

// Used to transfor custom data.
message BinaryAnnotation {
    string key = 1;
    string value = 2;
    EndPoint endpoint = 3;
}

message Span {
    string traceId = 1;
    // span id
    string id = 2;
    string parentId = 3;
    // method name
    string name = 4;
    // unit: microsecond
    int64 timestamp = 5;
    // unit: microsecond
    uint32 duration = 6;
    repeated Annotation annotations = 7;
    repeated BinaryAnnotation binaryAnnotations = 8;
}
以上是zipkin的格式spec，你的意思是从leveldb读出来，做一下格式转换，然后上传？
RpczSpan里面定义了三个Span，是可以由用户选择的吗，默认用的是哪一个？

**Comment by jamesge** [comment]
如果有相关的改造需求，可以在这里提出来。

**Comment by jamesge** [comment]
1. 采样有两个理解，一是出于性能角度只能采集一部分请求，这个本身就支持且是动态的。开启rpcz对cpu的影响非常小。二是用户可插入自定义数据，这个是通过TRACEPRINTF宏来完成的。
2. 这个可以扩展支持。

**Comment by tjb1216** [comment]
关于采样是性能方便的考虑，同时确实也没必要每次请求的数据都收集。
你说的采样是指这个吗？
DEFINE_int32(bvar_collector_expected_per_second, 1000,
             "Expected number of samples to be collected per second");
考虑到整个链路数据打通，采样要跟traceId关联，也就是说上游如果收集了该traceId的数据，下游才有收集的必要。

**Comment by tjb1216** [comment]
第2点支持有排期吗？大概什么时候能用？

**Comment by jamesge** [comment]
判断是否trace的逻辑见[IsTraceable](https://github.com/brpc/brpc/blob/30992d3a50d1d39d58f804a6311a726ad99dba37/src/brpc/span.h#L226)，只要上游被trace了，下游一定被trace，然后再会采样。第二点我看看代码再回复。

**Comment by tjb1216** [comment]
@jamesge ping

**Comment by billowqiu** [comment]
实现一套opentracing的api，用户自己根据内部tracing系统做上报(或者提供可选实现)，这样是不是更好一些？

**Comment by jamesge** [comment]
opentracing做的那些东西rpcz本来就做了，用户通过TRACEPRINTF嵌入自己的内容，似乎没有什么增量。如果是统一的数据格式，我觉得倒是有意义的。
