### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by xueyibing** [brpc/brpc#266]
环境：
centos
openssl：OpenSSL 1.0.2k-fips  26 Jan 2017

root@kook brpc]# grep OPENSSL_VERSION_NUMBER /usr/local/include/openssl/opensslv.h
# define OPENSSL_VERSION_NUMBER  0x10201000L

编译步骤：
完全按照readme方式编译

输出错误：
src/brpc/details/ssl_helper.cpp: 在函数‘DH* brpc::SSLGetDH1024()’中:
src/brpc/details/ssl_helper.cpp:542:31: 错误：‘DH_set0_pqg’在此作用域中尚未声明
     DH_set0_pqg(dh, p, NULL, g);
                               ^
src/brpc/details/ssl_helper.cpp: 在函数‘DH* brpc::SSLGetDH2048()’中:
src/brpc/details/ssl_helper.cpp:565:31: 错误：‘DH_set0_pqg’在此作用域中尚未声明
     DH_set0_pqg(dh, p, NULL, g);
                               ^
src/brpc/details/ssl_helper.cpp: 在函数‘DH* brpc::SSLGetDH4096()’中:
src/brpc/details/ssl_helper.cpp:588:31: 错误：‘DH_set0_pqg’在此作用域中尚未声明
     DH_set0_pqg(dh, p, NULL, g);
                               ^
src/brpc/details/ssl_helper.cpp: 在函数‘DH* brpc::SSLGetDH8192()’中:
src/brpc/details/ssl_helper.cpp:611:31: 错误：‘DH_set0_pqg’在此作用域中尚未声明
     DH_set0_pqg(dh, p, NULL, g);

**Comment by old-bear** [comment]
DH_set0_pqg这个函数在openssl 1.1后才有的，之前的版本需要用其他方式兼容下，这周会修复
着急的话可以先升级openssl版本，或者define OPENSSL_NO_DH关闭dh功能
谢谢
