### ISSUE TITLE
添加自定义协议问题

### ISSUE THREAD

**Issue by bozhbo** [brpc/brpc#268]
我参照PROTOCOL_BAIDU_STD添加了自己的协议，但是运行在消息发送成功后有崩溃
#0  0x00007ffff3d4957e in InsertBefore (e=0x7f24d4, this=0x7fffc405ce90) at ./src/butil/containers/linked_list.h:97
#1  Append (e=0x7fffc405ce90, this=<optimized out>) at ./src/butil/containers/linked_list.h:171
#2  get_or_create_tls_agent (this=<optimized out>) at ./src/bvar/detail/combiner.h:308
#3  bvar::IntRecorder::operator<< (this=this@entry=0x7f246c, sample=<optimized out>, sample@entry=2354) at ./src/bvar/recorder.h:256
#4  0x00007ffff3d44f6c in bvar::LatencyRecorder::operator<< (this=this@entry=0x7f246c, latency=2354) at src/bvar/latency_recorder.cpp:233
#5  0x00007ffff3f181e2 in OnResponded (latency=<optimized out>, success=<optimized out>, this=0x7f23e0) at ./src/brpc/details/method_status.h:99
#6  brpc::policy::SendXXXRpcResponse (correlation_id=<optimized out>, cntl=0x7fffc40448b0, req=0x7fffc4054b80, res=0x7fffc4054c40, socket_raw=0x7fffc401aec0, server=<optimized out>, method_status_raw=0x7f23e0, 
    start_parse_us=250484496916) at src/brpc/policy/xxxx_rpc_protocol.cpp:203
#7  0x00007ffff3f03dcf in brpc::internal::FunctionClosure8<long, brpc::Controller*, google::protobuf::Message const*, google::protobuf::Message const*, brpc::Socket*, brpc::Server const*, brpc::MethodStatus*, long>::Run (
    this=0x7fffc4054c80) at ./src/brpc/callback.h:506
#8  0x00007ffff608da7e in CRpcService::AddName(google::protobuf::RpcController*, AddNameRequest const*, AddNameResponse*, google::protobuf::Closure*) () from /project/cons/release64/./my.so
#9  0x00007ffff609cf52 in GlobalService::CallMethod(google::protobuf::MethodDescriptor const*, google::protobuf::RpcController*, google::protobuf::Message const*, google::protobuf::Message*, google::protobuf::Closure*) ()
   from /project/cons/release64/./my.so
#10 0x00007ffff3f1987f in brpc::policy::ProcessXXXRpcRequest (msg_base=0x7fffc403c860) at src/brpc/policy/xxxx_rpc_protocol.cpp:470
#11 0x00007ffff3e3d6aa in brpc::ProcessInputMessage (void_arg=void_arg@entry=0x7fffc403c860) at src/brpc/input_messenger.cpp:140
#12 0x00007ffff3e3ea79 in operator() (this=<optimized out>, last_msg=0x7fffc403c860) at src/brpc/input_messenger.cpp:146
#13 brpc::InputMessenger::OnNewMessages (m=0x7fffc401aec0) at /usr/include/c++/4.8.2/bits/unique_ptr.h:184
#14 0x00007ffff3e2271d in brpc::Socket::ProcessEvent (arg=0x7fffc401aec0) at src/brpc/socket.cpp:1051
#15 0x00007ffff3d7e4d4 in bthread::TaskGroup::task_runner (skip_remained=<optimized out>) at src/bthread/task_group.cpp:297
#16 0x00007ffff3d81a51 in bthread_make_fcontext () from /lib64/libbrpc.so

**Comment by jamesge** [comment]
没有代码无法知道你是如何实现你自己的协议，又是如何出错的。
