### ISSUE TITLE
brpc/src/butil/logging.cc:115: undefined reference to `google::FlagRegisterer::FlagRegisterer

### ISSUE THREAD

**Issue by dwroy** [brpc/brpc#270]
centos7
gcc 4.8.5

编译的时候遇到这个问题，请问能帮忙看下吗，谢谢了

Linking protoc-gen-mcpack
Copying to output/lib
libbrpc.a(logging.o): In function `_GLOBAL__sub_I_logging.cc':
/root/brpc/src/butil/logging.cc:115: undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'

**Comment by jamesge** [comment]
这个错误对应的位置是gflags的DEFINE_bool宏，检查你的gflags编译和产出lib是否正确。
