### ISSUE TITLE
cmake文件写的太随意了

### ISSUE THREAD

**Issue by wei7202839** [brpc/brpc#271]
getting_started.md里的这个脚本
mkdir build && cd build && cmake .. && make
完全是一个神坑, pb.cc目录和pb.h目录会被拷贝到build目录下编译  怎么可能成功？？？？
修改了里面的CMakeLists.txt文件以后  cmake成功make以后又会报以下错误
/home/appweb/sources/brpc/src/brpc/policy/mongo.pb.cc: In function ‘void brpc::policy::protobuf_AddDesc_src_2fbrpc_2fpolicy_2fmongo_2eproto()’:
/home/appweb/sources/brpc/src/brpc/policy/mongo.pb.cc:138:3: error: ‘protobuf_AddDesc_brpc_2foptions_2eproto’ is not a member of ‘brpc’
   ::brpc::protobuf_AddDesc_brpc_2foptions_2eproto();
   ^~
make[2]: *** [src/CMakeFiles/OBJ_LIB.dir/brpc/policy/mongo.pb.cc.o] Error 1
make[1]: *** [src/CMakeFiles/OBJ_LIB.dir/all] Error 2
make: *** [all] Error 2
请问下作者,brpc真的有在本地cmake编译成功过吗?

**Comment by yjhjstz** [comment]
> https://github.com/brpc/brpc/blob/master/CMakeLists.txt#L326

轻喷，我试过了，完全OK,  include build下的头文件了。

**Comment by zyearn** [comment]
把pb.cc pb.h生成到build下是为了不污染源代码文件，理论上你可以生成到任何地方，编译的时候指定对路径就可以了。把你原始的错误贴一下吧。

**Comment by RobitYadda** [comment]
这个可能要具体分析原因，直接攻击就不好了。我自己用cmake本地编译，没有遇到问题。

----------
该邮件从移动设备发送



--------------原始邮件--------------
发件人："Jiashun Zhu "<notifications@github.com>;
发送时间：2018年3月20日(星期二) 上午9:08
收件人："brpc/brpc" <brpc@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：Re: [brpc/brpc] 百度开源的太没节操(cmake文件写的太随意了) (#271)
-----------------------------------

把pb.cc pb.h生成到build下是为了不污染源代码文件，理论上你可以生成到任何地方，编译的时候指定对路径就可以了。把你原始的错误贴一下吧。

**Comment by NetWilliam** [comment]
@RobitYadda  梓祯你好帅
