### ISSUE TITLE
Nginx 1.13.10已经原生支持gRpc了，brpc有没有类似的计划？可行么

### ISSUE THREAD

**Issue by alanxzj** [brpc/brpc#272]
https://www.nginx.com/blog/nginx-1-13-10-grpc/

**Comment by alanxzj** [comment]
除了brpc client端的一些lb处理外，还可以借助nginx中间层成熟的lb处理机制

**Comment by gydong** [comment]
个人的理解是，grpc和brpc的主要应用场景不太一样，grpc的设计本来就着重考虑了互联网客户端的应用场景，所以会有来自互联网用户的grpc请求，所以在nginx中支持grpc较有意义。但brpc专注于打造一个强大的服务端框架，支持这个的意义不大。不过brpc也在协议方面做了非常多的工作，包括grpc（好像还没开源）。所以，未来可以在客户端用grpc，服务端依然保持brpc，这样中间层就可以用nginx。各取所长。

**Comment by chenzhangyi** [comment]
brpc可以支持http协议和[restful](https://github.com/brpc/brpc/blob/master/docs/cn/http_service.md#restful-url)， 可以不用修改就直接挂在nginx后面提供服务.

**Comment by gydong** [comment]
@chenzhangyi 在nginx和brpc之间使用HTTP这种通信协议还是比较低效的，按照题主的意思，估计是问是否会在nginx中支持baidu_std通信协议。

**Comment by jamesge** [comment]
支持baidu_std是没有必要的，这里指的可能主要还是h2和h2c。在brpc的实现中，(未加密的)h2c相比http在吞吐上基本近似，但对简单业务逻辑会明显节省CPU（复用连接减少了syscall），不过相比已有的其他二进制协议仍有明显劣势。nginx的实现不清楚，也许cpu都省不了多少。对于后端服务，h2间于http和更简单的二进制协议之间，定位有些尴尬，影响了它的推广速度。

**Comment by alanxzj** [comment]
我们的场景是异构的client非常多，也有qps压力，希望效率上能比当前http1 + restful 的模式有改善。
h2/h2c或者baidu_std这类二进制协议是更优的选择。

看 @jamesge 提到过会支持 h2/h2c以及grpc client，如果提供了的话，应该是可以直接用nginx原生支持gRpc这个特性，期待；
发这个issue确实是想看看能否在nginx直接支持baidu_std，不过第三方模块应该有一些制约，自己没有亲手弄过，所以有此一问
