### ISSUE TITLE
编译protoc-gen-mcpack时报错(跟leveldb相关)

### ISSUE THREAD

**Issue by wei7202839** [brpc/brpc#273]
编译到了最后一步报错了
[root@349923db7be8 brpc]# make install
[ 39%] Built target BUTIL_LIB
[ 95%] Built target OBJ_LIB
[ 95%] Built target brpc-shared
[ 95%] Built target brpc-static
Linking CXX executable ../output/bin/protoc-gen-mcpack
../output/lib/libbrpc.so: undefined reference to `_ZNK7leveldb6Status8ToStringB5cxx11Ev'
../output/lib/libbrpc.so: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
collect2: error: ld returned 1 exit status
make[2]: *** [output/bin/protoc-gen-mcpack] Error 1
make[1]: *** [src/CMakeFiles/protoc-gen-mcpack.dir/all] Error 2
make: *** [all] Error 2

**Comment by jamesge** [comment]
检查下leveldb是如何编译的，可以看下对应的leveldb库中有没有对应的符号(Open)，以及函数签名是否对得上。

**Comment by wei7202839** [comment]
跟leveldb的版本有关系吗  推荐什么版本我的是1.7

**Comment by jamesge** [comment]
和版本关系不大，这个函数1.7就有。可能leveldb是由早于5.0的gcc编译的，std::string的ABI和图中的std::__cxx11::basic_string不兼容了（后者支持了SSO）
