### ISSUE TITLE
在项目中用bazel编译，gzip_compress报错。

### ISSUE THREAD

**Issue by pdu** [brpc/brpc#275]
看起来像是brpc依赖的protobuf编译，没有把zlib的支持编进去。

用https://github.com/google/protobuf/issues/2365 这里面的建议，并没有解决。大家有什么建议吗？

`bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipCompress(google::protobuf::Message const&, butil::IOBuf*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::Options::Options()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipCompress(google::protobuf::Message const&, butil::IOBuf*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::GzipOutputStream(google::protobuf::io::ZeroCopyOutputStream*, google::protobuf::io::GzipOutputStream::Options const&)'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipCompress(google::protobuf::Message const&, butil::IOBuf*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::Close()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipCompress(google::protobuf::Message const&, butil::IOBuf*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::~GzipOutputStream()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipCompress(google::protobuf::Message const&, butil::IOBuf*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::~GzipOutputStream()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipDecompress(butil::IOBuf const&, google::protobuf::Message*): error: undefined reference to 'google::protobuf::io::GzipInputStream::GzipInputStream(google::protobuf::io::ZeroCopyInputStream*, google::protobuf::io::GzipInputStream::Format, int)'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipDecompress(butil::IOBuf const&, google::protobuf::Message*): error: undefined reference to 'google::protobuf::io::GzipInputStream::~GzipInputStream()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipDecompress(butil::IOBuf const&, google::protobuf::Message*): error: undefined reference to 'google::protobuf::io::GzipInputStream::~GzipInputStream()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipCompress(butil::IOBuf const&, butil::IOBuf*, google::protobuf::io::GzipOutputStream::Options const*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::Options::Options()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipCompress(butil::IOBuf const&, butil::IOBuf*, google::protobuf::io::GzipOutputStream::Options const*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::GzipOutputStream(google::protobuf::io::ZeroCopyOutputStream*, google::protobuf::io::GzipOutputStream::Options const&)'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipCompress(butil::IOBuf const&, butil::IOBuf*, google::protobuf::io::GzipOutputStream::Options const*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::Next(void**, int*)'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipCompress(butil::IOBuf const&, butil::IOBuf*, google::protobuf::io::GzipOutputStream::Options const*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::BackUp(int)'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipCompress(butil::IOBuf const&, butil::IOBuf*, google::protobuf::io::GzipOutputStream::Options const*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::Close()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipCompress(butil::IOBuf const&, butil::IOBuf*, google::protobuf::io::GzipOutputStream::Options const*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::~GzipOutputStream()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipCompress(butil::IOBuf const&, butil::IOBuf*, google::protobuf::io::GzipOutputStream::Options const*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::~GzipOutputStream()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::ZlibCompress(google::protobuf::Message const&, butil::IOBuf*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::Options::Options()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::ZlibCompress(google::protobuf::Message const&, butil::IOBuf*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::GzipOutputStream(google::protobuf::io::ZeroCopyOutputStream*, google::protobuf::io::GzipOutputStream::Options const&)'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::ZlibCompress(google::protobuf::Message const&, butil::IOBuf*): error: undefined reference to 'google::protobuf::io::GzipOutputStream::Close()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::ZlibDecompress(butil::IOBuf const&, google::protobuf::Message*): error: undefined reference to 'google::protobuf::io::GzipInputStream::GzipInputStream(google::protobuf::io::ZeroCopyInputStream*, google::protobuf::io::GzipInputStream::Format, int)'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::ZlibDecompress(butil::IOBuf const&, google::protobuf::Message*): error: undefined reference to 'google::protobuf::io::GzipInputStream::~GzipInputStream()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::ZlibDecompress(butil::IOBuf const&, google::protobuf::Message*): error: undefined reference to 'google::protobuf::io::GzipInputStream::~GzipInputStream()'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipDecompressBase(butil::IOBuf const&, butil::IOBuf*, google::protobuf::io::GzipInputStream::Format): error: undefined reference to 'google::protobuf::io::GzipInputStream::GzipInputStream(google::protobuf::io::ZeroCopyInputStream*, google::protobuf::io::GzipInputStream::Format, int)'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipDecompressBase(butil::IOBuf const&, butil::IOBuf*, google::protobuf::io::GzipInputStream::Format): error: undefined reference to 'google::protobuf::io::GzipInputStream::Next(void const**, int*)'
bazel-out/k8-fastbuild/bin/external/com_github_brpc_brpc/_objs/brpc/external/com_github_brpc_brpc/src/brpc/policy/gzip_compress.pic.o:gzip_compress.cpp:function brpc::policy::GzipDecompressBase(butil::IOBuf const&, butil::IOBuf*, google::protobuf::io::GzipInputStream::Format): error: undefined reference to 'google::protobuf::io::GzipInputStream::Next(void const**, int*)'`

**Comment by jamesge** [comment]
目前项目中的BUILD是由网友提供的，支持可能还未完善，你看看能否做一些修改使其通过，我再一起review一下。

**Comment by yjhjstz** [comment]
亲测：下载protobuf , 编译安装，注意` ./configure --with-zlib`

**Comment by pdu** [comment]
@yjhjstz 谢谢！自己编译的方式应该是可以的。
我想用bazel来build，protobuf自己是提供了bazel的编译的，但是里面没有包含zlib。

**Comment by pdu** [comment]
@jamesge 谢谢！我测试看看。

**Comment by pdu** [comment]
@jamesge brpc里面的编译是没有问题的，https://github.com/brpc/brpc/blob/master/tools/bazel.rc#L1 通过这个配置，默认在编译protobuf的时候加上了ZLIB的支持。

解决方法：
1. 在用brpc的时候，也需要加上类似的配置，或者bazel build --copt -DHAVE_ZLIB=1，不然就会有上面的link出错。
2. 在brpc里面编译protobuf的时候用new_http_archive，不通过tools/bazel.rc的方式设置build --copt -DHAVE_ZLIB=1，把protobuf的BUILD文件手动加上-DHAVE_ZLIB=1。在用brpc的时候就不需要特别配置了。

如果需要改成方法2的话，我可以提个PR。

**Comment by dhx1989** [comment]
bazel 编译默认会找 tools/bazel.rc 作为配置去编译，所以在根目录直接运行bazel build就可以不需要显示指定--copt -DHAVE_ZLIB=1， 如果显示指定编译选项也没有问题

**Comment by jamesge** [comment]
@dhx1989 要不要在[getting started](https://github.com/brpc/brpc/blob/master/docs/cn/getting_started.md)里加一段关于bazel编译的内容？

**Comment by pdu** [comment]
@dhx1989 是的，但是在第一次引用brpc的时候，很容易忽视这个编译选项。

**Comment by dhx1989** [comment]
@jamesge 好的，我整理下在getting started里添加bazel编译相关内容

**Comment by yockie** [comment]
补充一个问题的答案：
现象：先是跟出现跟lz相似的link错误，按楼上答案加了“设置build --copt -DHAVE_ZLIB=1”有一部分link错误解决，但还是有link错误：
bazel-out/k8-opt/bin/external/com_google_protobuf/_objs/protobuf/gzip_stream.o:gzip_stream.cc:function google::protobuf::io::GzipInputStream::~GzipInputStream(): error: undefined reference to 'inflateEnd'
bazel-out/k8-opt/bin/external/com_google_protobuf/_objs/protobuf/gzip_stream.o:gzip_stream.cc:function google::protobuf::io::GzipInputStream::Inflate(int): error: undefined reference to 'inflate'
bazel-out/k8-opt/bin/external/com_google_protobuf/_objs/protobuf/gzip_stream.o:gzip_stream.cc:function google::protobuf::io::GzipInputStream::Inflate(int): error: undefined reference to 'inflateInit2_'
bazel-out/k8-opt/bin/external/com_google_protobuf/_objs/protobuf/gzip_stream.o:gzip_stream.cc:function google::protobuf::io::GzipInputStream::Next(void const**, int*): error: undefined reference to 'inflateEnd'
bazel-out/k8-opt/bin/external/com_google_protobuf/_objs/protobuf/gzip_stream.o:gzip_stream.cc:function google::protobuf::io::GzipInputStream::Next(void const**, int*): error: undefined reference to 'inflateInit2_'
bazel-out/k8-opt/bin/external/com_google_protobuf/_objs/protobuf/gzip_stream.o:gzip_stream.cc:function google::protobuf::io::GzipOutputStream::Init(google::protobuf::io::ZeroCopyOutputStream*, google::protobuf::io::GzipOutputStream::Options const&): error: undefined reference to 'deflateInit2_'
bazel-out/k8-opt/bin/external/com_google_protobuf/_objs/protobuf/gzip_stream.o:gzip_stream.cc:function google::protobuf::io::GzipOutputStream::Deflate(int): error: undefined reference to 'deflate'
bazel-out/k8-opt/bin/external/com_google_protobuf/_objs/protobuf/gzip_stream.o:gzip_stream.cc:function google::protobuf::io::GzipOutputStream::Close(): error: undefined reference to 'deflateEnd'


调了半天，解决方法是：link加上-lz，例如：
cc_binary(                                                                                               
    name = "xxx",                                                                                   
    srcs = ["xxx.cc"],                                                                                  
    defines = [                                                                                          
    ],                                                                                                   
    linkopts = [                                                                                         
        "-lpthread",                                                                                     
        "-lz",                                                                                           
    ],                                                                                                                                                                                 
    deps = [                                                                                                                                                                                 
    ],                                                                                                   
)
