### ISSUE TITLE
libbprc.a 编译链接问题

### ISSUE THREAD

**Issue by yjhjstz** [brpc/brpc#276]
> /usr/bin/cmake -E cmake_link_script CMakeFiles/multi_threaded_echo_server.dir/link.txt --verbose=1
/usr/bin/c++   -DGFLAGS_NS=google -DNDEBUG -O2 -D__const__= -pipe -W -Wall -Wno-unused-parameter -fPIC -fno-omit-frame-pointer -DBRPC_ENABLE_CPU_PROFILER  -O0 -Wall -g -ggdb   CMakeFiles/multi_threaded_echo_server.dir/server.cpp.o  -o multi_threaded_echo_server -rdynamic brpc/build/output/lib/libbrpc.a -lpthread -lgflags /usr/local/lib/libprotobuf.so -lpthread -lleveldb -lssl -lcrypto -ldl core/libcore.a protos/libproto.a model_servers/libservice.a util/libutil.a -ltcmalloc_and_profiler -lgflags /usr/local/lib/libprotobuf.so -lleveldb -lssl -lcrypto -ldl -ltcmalloc_and_profiler -lprotobuf -Wl,-rpath,/usr/local/lib
core/libcore.a(scheduler.cc.o): In function `bthread::ConditionVariable::ConditionVariable()':
/home/luban/DDL-Serving/brpc/build/output/include/bthread/condition_variable.h:33: undefined reference to `bthread_cond_init'
core/libcore.a(scheduler.cc.o): In function `bthread::ConditionVariable::~ConditionVariable()':
/home/luban/DDL-Serving/brpc/build/output/include/bthread/condition_variable.h:36: undefined reference to `bthread_cond_destroy'
core/libcore.a(scheduler.cc.o): In function `bthread::ConditionVariable::wait(std::unique_lock<bthread::Mutex>&)':
/home/luban/DDL-Serving/brpc/build/output/include/bthread/condition_variable.h:42: undefined reference to `bthread_cond_wait'
core/libcore.a(scheduler.cc.o): In function `bthread::ConditionVariable::notify_one()':
/home/luban/DDL-Serving/brpc/build/output/include/bthread/condition_variable.h:76: undefined reference to `bthread_cond_signal'

@jamesge

**Comment by jamesge** [comment]
condition_variable.h里漏了一些函数声明，更新后应该好了。
