### ISSUE TITLE
brpc 需要结合什么组件实现分布式服务

### ISSUE THREAD

**Issue by wind-zhang** [brpc/brpc#277]
像 dubbo需要结合zookeeper来实现发现/注册中心,  brpc怎样实现，或依赖什么组件可以实现

**Comment by jamesge** [comment]
一般需要扩展NamingService，大致方法看[这个](https://github.com/brpc/brpc/blob/master/docs/cn/load_balancing.md), 
也可以看下[这个ppt](https://github.com/brpc/brpc/blob/master/docs/en/tutorial_on_building_services.pptx)

**Comment by wind-zhang** [comment]
好的谢谢，先研究下

**Comment by wind-zhang** [comment]
还有遇到一个问题，brpc 通过nameservice 实现分布式架构后，  braft 怎么进行整合，实现数据一致性

**Comment by jamesge** [comment]
brpc中的naming service是把多个server聚合起来，一般来说server是同构的（对同一个输入提供类似的输出），单独来说一般不称为“分布式架构”，只能算是“服务”或“大规模系统”。而braft的使用场景则是构建真的分布式系统，不同的server往往会承载不同的数据，具体来说就是一个server一般会承载多个raft node，多个raft node又构成raft group，master节点会知道所有的raft group/node在哪，并作为naming service角色让client知道，master也会做各种全局控制。可以结合raft的例子和外部资料了解一下。
