### ISSUE TITLE
使用bthread是否意味着不能使用临时变量? 所有变量都应存放在堆中?

### ISSUE THREAD

**Issue by Jiacheng-z** [brpc/brpc#278]
由于bthread使用相应API阻塞时, 有可能切换线程, 所以必须确保变量申请的空间都申请在堆中?
例如:
```
function() {
    var i = xxx;
    bthread_usleep(10000);
    std::cout << i << std::endl;
}
```
这种写法是否会导致在取变量`i`出现问题?  如另外一个线程找不到变量`i`对应的栈空间?

**Comment by jamesge** [comment]
不会，切换的是底层的pthread，但i是放在bthread的栈上的。如果变量都要分配在堆上，那代码基本没法写了:)

**Comment by Jiacheng-z** [comment]
有点晕... 我理解的是, 由于执行bthread的是pthread, 所以最终变量申请的地址还是在pthread上的. 是通过 ContextualStack 将 i 放在bthread栈上的吗?  不太明白其中的原理, 是怎样把变量放在 bthread上的... 通过 allocator 么?

**Comment by Jiacheng-z** [comment]
有点晕.. 我理解的是 bthread 最终还是在 pthread 执行的函数,  因此相对应的变量也应该是申请在 pthread栈上的,  是通过什么样的方法将变量i申请在bthread栈上的呢? 通过 ContextualStack ? allocator?

**Comment by jamesge** [comment]
严格地说是在[LWP](https://en.wikipedia.org/wiki/Light-weight_process)执行，只是由于linux下的pthread和LWP是一对一，所以说成“在pthread执行”。执行过程中SP寄存器会换成bthread的栈，所以和pthread无关。
