### ISSUE TITLE
does brpc currently have ROADMAP?

### ISSUE THREAD

**Issue by allencloud** [brpc/brpc#28]
Hi, All,

Thanks a lot for Baidu for opensourcing such a valuable project.

I wish to get know that if currently brpc has a ROADMAP?

Thanks a lot.

**Comment by jamesge** [comment]
We're still listening to different voices from public and will publish a roadmap when priorities are settled.

**Comment by allencloud** [comment]
Thanks a lot. Be waiting...
Closing this.
