### ISSUE TITLE
程序内使用不同版本的rapidjson会导致运行时crash

### ISSUE THREAD

**Issue by peiyuanzheng** [brpc/brpc#283]
使用brpc搭建在线服务模块，编译OK，运行时crash。
经过定位后发现，brpc/src/json2pb依赖的rapidjson版本是1.0.2，而模块依赖的另一个lib使用的rapidjson版本是1.1.0。

rapidjson是一个纯头文件的库，看了rapidjson.h中的文档，提到了：
“
    In order to avoid symbol clashes and/or "One Definition Rule" errors
    between multiple inclusions of (different versions of) RapidJSON in
    a single binary, users can customize the name of the main RapidJSON
    namespace.

    In case of a single nesting level, defining \c RAPIDJSON_NAMESPACE
    to a custom name (e.g. \c MyRapidJSON) is sufficient.
”

当前我的解决方案是：
1. 修改 brpc/src/json2pb 源码中的"rapidjson::" 为"RAPIDJSON_NAMESPACE::"。
2. brpc/CMakeLists.txt 中，加入预处理宏 -DRAPIDJSON_NAMESPACE=rapidjson_1_0_2。

不知道是否有其他人也遇到类似的情况，请分享下你们的解决方案。
如果我的描述有问题，请指正，谢谢。

**Comment by jamesge** [comment]
存在一个文件同时include了两个版本的rapidjson?

**Comment by peiyuanzheng** [comment]
brpc源码本身没有问题，单独编译和运行都是OK的。

我遇到的场景是：
brpc内部使用了A版本的rapidjson，我们的服务模块中使用了另外一个libXXX库，它使用了B版本的rapidjson。同时把brpc和libXXX编入一个binary，会导致同时存在两个版本的rapidjson，运行时crash。

我的解决方案可能不是最优的。
我的建议是：brpc/src/json2pb源码中的"radpidjson::" 换成宏定义，便于用户自定义。

**Comment by chenzhangyi** [comment]
这是ABI不兼容导致的，不同版本的rapidjson某些类的内存布局发生了变化， 解决方案除了改变namespace其实也没什么特别好的.

**Comment by jamesge** [comment]
should be solved in #291
