### ISSUE TITLE
protobuf 3 的syntax="proto3"支持情况

### ISSUE THREAD

**Issue by yjhjstz** [brpc/brpc#288]
> Be compatible with pb 3.x and pb 2.x with the same file: Don't use new types in proto3 and start the proto file with syntax="proto2"; tools/add_syntax_equal_proto2_to_all.shcan add syntax="proto2" to all proto files without it.

Arena in pb 3.x is not supported yet.

求解为什么？

**Comment by jamesge** [comment]
arena是另外一套接口，需要额外传入arena对象，需要给rpc增加编译时开关，所以目前并未支持。

**Comment by yjhjstz** [comment]
什么时候开放支持呢？

**Comment by jamesge** [comment]
目前没有计划，如果你有兴趣可以提pr

**Comment by alanxzj** [comment]
@yjhjstz 你的场景是什么样的？性能要求需要Arena...

**Comment by yjhjstz** [comment]
> https://github.com/tensorflow/serving

这里面用到的都是 pb3.
