### ISSUE TITLE
sofa和brpc探活协议不兼容

### ISSUE THREAD

**Issue by scottzzq** [brpc/brpc#289]
如题，问下百度内部是怎么解决的？多谢了

**Comment by jamesge** [comment]
brpc的探活只是连一下，是兼容sofa-pbrpc的。

**Comment by scottzzq** [comment]
https://github.com/baidu/sofa-pbrpc/blob/master/src/sofa/pbrpc/dynamic_rpc_channel_impl.cc#L588 
https://github.com/baidu/sofa-pbrpc/blob/master/src/sofa/pbrpc/builtin_service.proto#L123
这个是sofa库使用的探活协议

https://github.com/brpc/brpc/blob/master/src/brpc/builtin_service.proto#L18
这个是brpc的探活协议

两个pb结构不在一个package中，导致使用sofa库的client检查brpc搭建的server失败。

**Comment by jamesge** [comment]
brpc那个链接自身是不用的，只是tcp连一下。如果你要让brpc支持sofa-pbrpc的探活，可以提pr。
