### ISSUE TITLE
是否考虑支持CMake

### ISSUE THREAD

**Issue by q96456** [brpc/brpc#29]
希望支持CMake

**Comment by NeverCheng** [comment]
建议添加上CMake

**Comment by jamesge** [comment]
会加的，之前是想省得用户多装一个cmake。

**Comment by Donald-Chun** [comment]
另外到时候加上打包(bin, devel)的相关脚本，比如打rpm, deb等包。

**Comment by fr0zenrain** [comment]
gnu getopt 真蛋疼

**Comment by liu946** [comment]
能否给一个官方的CMakeList配置示例？自己写Makefile的话不好在IDE上开发啊。希望能脱敏一个CMake的项目示例加在Example里。

**Comment by guangqianpeng** [comment]
同求. 没有CMakeList很难在IDE上阅读和执行源码

**Comment by jamesge** [comment]
主干已支持cmake
