### ISSUE TITLE
怎么使用bvar统计每天的请求数

### ISSUE THREAD

**Issue by zhengshf** [brpc/brpc#295]
bvar::Window最大时间窗为3600s，如果设置一天的秒数86400会超过窗大小限制，那么怎么能统计每天的请求数呢？

**Comment by jamesge** [comment]
天级别的数据最好是通过全局监控系统汇总展示，bvar中即使允许计算，目前的展示方式也很难很好地展示例如”昨天下午5点30分左右的数据“

**Comment by zhengshf** [comment]
我的想法是统计单台brpc服务的流量之后再将单台服务的流量数据发送到汇总服务器上，汇总服务器再做累加显示即可，所以如果能够按天统计，每台brpc服务每天只需要发送一次即可。

**Comment by jamesge** [comment]
那粒度就是天粒度了，这个一般是不够的，在百度的应用中，bvar的单机数据是10秒-60秒汇总一次。

**Comment by zhengshf** [comment]
或者我把时间窗设成分钟或小时来统计，最后把一天的这些数据做累加当成单台服务器一天的量，这个误差会很大么？我们这个是临时方案，希望能快速的获得一天的流量。
