### ISSUE TITLE
Elimit, 错误码2004，如何解决？

### ISSUE THREAD

**Issue by xiaohei520321** [brpc/brpc#298]
线上有brpc的server，跑的一直好好的，已经出现过2次，某台server突然没法接收请求了。
client发请求的时候，该server端一直报2004错误。
还有些server，每分钟收到的请求断崖式下跌，latency并没有什么变化，client端访问的时候，大部分也是报2004。
查了错误码的解释是”同时处理的请求数超过ServerOptions.max_concurrency了”， 但是这个值我设的是0，应该没有限制。

感觉像是brpc server端会有哪里被死锁了的样子，不知道你们有碰到过这样的问题么？

**Comment by xiaohei520321** [comment]
server端内存，cpu，磁盘等都没有问题的

**Comment by gydong** [comment]
这个现象听起来怪异，可以把你们服务的status页面各个曲线截图出来看看吗？

**Comment by xiaohei520321** [comment]
@gydong 发现问题后，已经重启服务了。现在都正常的。当时试图看过那台完全没法收流量的server的status，连brpc内置服务都没法访问了。对于那些收请求断崖下跌的server，brpc 的qps上可以看到，在某个时间点，一下子qps少了，latency并没有变化

**Comment by xiaohei520321** [comment]
@gydong 没法复现，使用了几个月，出现过2次这样的情况

**Comment by jamesge** [comment]
这种情况发生时可以看下栈的情况(pstack)。一种常见的原因是一些分支忘记调用done了。

**Comment by RuhigSoda** [comment]
使用的方式是：服务端处理完必要逻辑，填写response之后，手动调用done->Run()之后，服务端再做一些日志打印的相关的事情。。。这样应该不会"忘记调用done"

**Comment by jamesge** [comment]
在调用done->Run()之前由于错误跳出的话就没有调了，这是推荐使用ClosureGuard的主要原因

**Comment by RuhigSoda** [comment]
"在调用done->Run()之前由于错误跳出的话就没有调了",不知道您所谓的由于错误跳出，是brpc的某些错误还是我自己的业务错误？如果是业务逻辑上出现错误的情况会goto到一个点，这个点还是会调用done->Run()的

**Comment by zyearn** [comment]
"连brpc内置服务都没法访问了"
看看是不是某个bthread占着锁然后被调度出去了（调用bthread_sleep等），如果其它的任务都要抢这把锁，会把所有的worker thread变成一个等锁的状态。这里需要注意的是，如果相同的pthread跑着另外一个需要抢锁的bthread，而且锁还不是recursive的，这个线程就永远在等锁了 @xiaohei520321
