### ISSUE TITLE
compile error: google has not been declared

### ISSUE THREAD

**Issue by liudf0716** [brpc/brpc#3]
following this article:
https://github.com/brpc/brpc/blob/master/docs/cn/getting_started.md
I encounter the following compiling error:

![image](https://user-images.githubusercontent.com/1182593/30475208-a1755afa-9a38-11e7-8330-3b5657c72f4d.png)

**Comment by chenzhangyi** [comment]
It seems that gflags has modified its namespace from google to gflags (see https://github.com/gflags/gflags/issues/145). 
We will find resolve this in the future, right now you'd better use an old version of gflags(before 2.2) to compile brpc.
Sorry for the inconvenience.

**Comment by Donald-Chun** [comment]
需要将错误的地方google::xxx替换成GFLAGS_NAMESPACE::xxx.

**Comment by jamesge** [comment]
This issue should be solved at HEAD, need to be confirmed by @liudf0716

**Comment by liudf0716** [comment]
in my centos7 platform
```
git pull
sh config_brpc.sh --headers=/usr/include --libs=/usr/lib64
Fail to find google/profiler.h from --headers
```
it's my recent report.

**Comment by jamesge** [comment]
gperftools changes its dir and namespace from google to gperftools in newer versions, try to manually change google to gperftools in source code temporarily. We'll verify this problem.

**Comment by jamesge** [comment]
@liudf0716 check again

**Comment by liudf0716** [comment]
@jamesge  It's ok now.　:+1:

**Comment by liudf0716** [comment]
I have a suggestion:
how about support cmake way to compile brpc?

**Comment by jamesge** [comment]
will support
