### ISSUE TITLE
协程支持吗

### ISSUE THREAD

**Issue by NeverCheng** [brpc/brpc#31]
rpc调用， 即使是多线程， 也比较消耗资源， 如果使用协程切换，就比较有优势了

**Comment by txsniper** [comment]
你先看文档吧，bthread那段

**Comment by txsniper** [comment]
楼主先看文档吧，bthread那段

**Comment by jamesge** [comment]
https://github.com/brpc/brpc/blob/master/docs/cn/bthread.md
