### ISSUE TITLE
用的tcmalloc和brpc, heap profile统计到的内存和RES差别较大

### ISSUE THREAD

**Issue by dl239** [brpc/brpc#313]
使用的tcmalloc和brpc，偶发性的会出现内存增长，用tcmalloc自带的heap profile统计到的内存和rss不一致，brpc内部会有绕过tcmalloc申请内存的地方吗

**Comment by jamesge** [comment]
主要是bthread的栈，如果bthread特别多，会明显占用rss。不过一般由于复用和os按需分配page，不会特别多。

**Comment by chenzhangyi** [comment]
heap profiler统计的内存不会包括tcmalloc freelist的内存， 但是这部分会算在rss中。

**Comment by dl239** [comment]
------------------------------------------------
MALLOC:       15227040 (   14.5 MiB) Bytes in use by application
MALLOC: +            0 (    0.0 MiB) Bytes in page heap freelist
MALLOC: +    929693728 (  886.6 MiB) Bytes in central cache freelist
MALLOC: +      4997120 (    4.8 MiB) Bytes in transfer cache freelist
MALLOC: +      3540800 (    3.4 MiB) Bytes in thread cache freelists
MALLOC: +    195342528 (  186.3 MiB) Bytes in malloc metadata
MALLOC:   ------------
MALLOC: =   1148801216 ( 1095.6 MiB) Actual memory used (physical + swap)
MALLOC: +  37190074368 (35467.2 MiB) Bytes released to OS (aka unmapped)
MALLOC:   ------------
MALLOC: =  38338875584 (36562.8 MiB) Virtual address space used
MALLOC:
MALLOC:         204029              Spans in use
MALLOC:             30              Thread heaps in use
MALLOC:           8192              Tcmalloc page size
------------------------------------------------
tcmalloc统计的在1G左右，但是看实际内存占用好几G, 而且还会不断上升(这种情况是偶发性的不一定每次都复现)

**Comment by jamesge** [comment]
看下/vars/bthread_count和/vars/bthread_stack_count是多少，另外如果是线下测试系统，且没有定期调用过tcmalloc的ReleaseFreeMemory可以设置-free_memory_to_system_interval=10看看（在一些配置下有crash风险，所以未验证不要直接在线上使用）

**Comment by dl239** [comment]
bthread_count : 4
bthread_group_status : "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 "
bthread_key_count : 1
bthread_keytable_count : 4
bthread_keytable_memory : 3072
bthread_signal_second : 2
bthread_stack_count : 23
bthread_switch_second : 4
bthread_timer_scheduled_second : 2
bthread_timer_triggered_second : 2
bthread_timer_usage : 1.43985e-05
bthread_worker_count : 20
bthread_worker_usage : 0.000506187
bvar_dump_interval : 10
bvar_sampler_collector_usage : 0.00124097
gcc_version : "4.8.5"
iobuf_block_count : 56
iobuf_block_count_hit_tls_threshold : 0
iobuf_block_memory : 458752

恩，我设置下试试
