### ISSUE TITLE
message_loop_proxy.h 缺失

### ISSUE THREAD

**Issue by yjhjstz** [brpc/brpc#321]
>butil/files/file_path_watcher.h:15:51: fatal error: butil/message_loop/message_loop_proxy.h: No such file or directory
 #include "butil/message_loop/message_loop_proxy.h"

**Comment by jamesge** [comment]
which platform?

**Comment by yjhjstz** [comment]
linux

**Comment by yjhjstz** [comment]
其实项目下都没有这个文件。
