### ISSUE TITLE
brpc 为什么没有实现读写锁 ？ 在读多写少的时候 读写锁比互斥锁有更好的性能

### ISSUE THREAD

**Issue by chenguangpeng1** [brpc/brpc#334]

**Comment by chenguangpeng1** [comment]
bthread 是用户和内核线程中间层，多个taskgroup 中的 btread “读多写少” 同一资源时，互斥锁对临界区的操作会很耗费性能

**Comment by chenguangpeng1** [comment]
thanks

**Comment by chenguangpeng1** [comment]
@jamesge  您好 jamesge ，有时间的时候帮忙看看，谢谢

**Comment by jamesge** [comment]
读写锁一般会用到引用计数，每次读还是会竞争同一个cacheline，所以性能相比不加锁还是有差距的，一般会尝试读尽量无锁的方案，比如内核中的[RCU](https://www.ibm.com/developerworks/cn/linux/l-rcu/index.html)，brpc中的[DBD](https://github.com/brpc/brpc/blob/master/docs/cn/lalb.md#doublybuffereddata). 所以brpz并没有用到读写锁，就一直没有实现了。
