### ISSUE TITLE
请教一个请求串行执行的问题

### ISSUE THREAD

**Issue by slatp** [brpc/brpc#343]
brpc假设不同请求之间是无关的，但是某些业务场景需要对一些请求串行处理，比如server同时收到多个修改同一用户数据的请求，如果并行处理则写存储的时候可能会冲突。目前我们的解决方案是将请求按用户id取模到对应线程的处理队列，以此保证不可能有多个线程同时处理同一个用户的请求。不知道brpc对于这类场景有什么好的解决方案没，谢谢。

**Comment by jamesge** [comment]
这个问题分几个层面：
1. 要求从接受请求开始就保证有序，这点除了[streaming rpc](https://github.com/brpc/brpc/blob/master/docs/en/streaming_rpc.md)都是保证不了的，包括来自同一个连接的请求。
2. 不关心请求顺序，但要让对某一类请求的处理互斥。这一般是通过[Execution Queue](https://github.com/brpc/brpc/blob/master/docs/cn/execution_queue.md)来做到的，可以理解为对message passing或actor模式的一种实现。
