### ISSUE TITLE
logging CharArrayStreamBuf overflow 导致内存增长问题

### ISSUE THREAD

**Issue by milesfei** [brpc/brpc#344]
![image](https://user-images.githubusercontent.com/7608113/40524373-ced4a0ba-600c-11e8-92ee-9a29c33cadca.png)
导致内存增长位置如图所示，16小时已增长2G，调试代码发现在代码中的表现是 _channel->CallMethod() 引起的内存增长，请问哪里会触发 logging CharArrayStreamBuf overflow？

**Comment by jamesge** [comment]
这是日志路径上的，有特大的单条日志么？另外为了确认调用关系是完整的，检查下你自己的代码编译是否加了-fno-omit-frame-pointer，或是链接的tcmalloc使用了libunwind

**Comment by milesfei** [comment]
发现comlog的配置中写了日志最大长度限制，改大之后的确不截断了，但是还会有 overflow 的现象，请问如果想打印这种大log，应该怎么用？这里的overflow是bug？还是我的使用方法有问题？

**Comment by milesfei** [comment]
现在发现了一个奇怪的现象，通过 heap profiler 看到的内存只有 50M，但是memory_resident为1.3G，看到之前的issue里说，freelist占用的内存没有被统计，但是我尝试使用ReleaseFreeMemory，内存也没有下降（server的回调函数中加入ReleaseFreeMemory或者通过参数-free_memory_to_system_interval=10都没有效果），请问heap profiler还有哪部分内存没有统计到？还是ReleaseFreeMemory使用方法问题？谢谢

**Comment by milesfei** [comment]
还有另一个问题，我做了一个实验，使用rpc作为服务收请求，该服务同时还会作为client请求其他服务，中间的处理逻辑只有解析包和组装包，发现内存也会增长，如下图（横轴：时间h，纵轴：内存M）：
![line_8011](https://user-images.githubusercontent.com/7608113/40593515-8b2335ba-625b-11e8-8d84-d1b6d53e5592.jpg)
通过log发现有大量的：baidu/base/baidu-rpc/src/baidu/rpc/input_messenger.cpp:214] Fail to read from fd=72 SocketId=320748157666720@xxx@xxx: Connection reset by peer
请问是否是这个原因导致内存增长？谢谢

**Comment by milesfei** [comment]
bthread_count : 372
bthread_group_status : "1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 "
bthread_key_count : 1
bthread_keytable_count : 3225
bthread_keytable_memory : 2476800
bthread_revision : "20bf1e1d44dea68386c8cccd67237c5614ff8590"
bthread_signal_second : 1069
bthread_stack_count : 3488
bthread_switch_second : 20456
bthread_timer_scheduled_second : 4069
bthread_timer_triggered_second : 4
bthread_timer_usage : 0.0021024
bthread_worker_count : 41
bthread_worker_usage : 2.15443
bvar_dump_interval : 10
bvar_revision : "993ab7adddcd30c5a1778c5642c246e35a7fbf3e"
bvar_sampler_collector_usage : 0.00291719
gcc_version : "4.8.2"
iobuf_block_count : 517
iobuf_block_count_hit_tls_threshold : 4209989
iobuf_block_memory : 4235264
iobuf_newbigview_second : 253

**Comment by jamesge** [comment]
bthread还是比较多，那点内存增长是正常的。看起来这个服务的延时是比较长的？可以考虑使用异步接口。

**Comment by milesfei** [comment]
嗯，目前的测试数据会导致服务延时较长，所以在这种情况下，如果一直发大压力，内存会持续增长？还是会有增长上限？（异步接口我一会儿试一下）
目前仍然存在的一个问题是，如何在打印大log的同时控制内存不增长（有些request和response会比较大，log限长问题已经解决，需要解决内存增长问题）？

**Comment by jamesge** [comment]
如果超时率很高或者平均延时显著高于正常值，那么服务就出于拥塞状态，这个其实不算是正常的状态。如果是这种情况，可以考虑让压力工具同步访问，或者限制server端的并发。

**Comment by milesfei** [comment]
使用 valgrind 得到：
![image](https://user-images.githubusercontent.com/7608113/40658719-b48e9830-637e-11e8-828f-3a96935e389d.png)
请问是不是我使用的 client 有问题，或者使用方法有问题？
使用的库文件：
#include <baidu/rpc/ub_call.h>                                                                       
#include <baidu/rpc/channel.h>

我能想到的可能有问题的情况是：
baidu::rpc::RawBuffer req_buf(RPC_BUF_SIZE);                                                     
baidu::rpc::RawBuffer res_buf(RPC_BUF_SIZE);                                                                                                          
baidu::rpc::UBRawMcpackRequest request(&req_buf);                                                
baidu::rpc::UBRawMcpackResponse response(&res_buf);
是放在栈里的，response比较大，而且请求很频繁，谢谢

**Comment by milesfei** [comment]
valgrind，用低qps压测，发现 reachable 很大，而且不释放，是为什么呢？
![val_leak_summary](https://user-images.githubusercontent.com/7608113/40695511-120f2bee-63f4-11e8-80ad-7031bf8ed6fd.jpg)
![val_leak_reachable](https://user-images.githubusercontent.com/7608113/40695527-2a22deb0-63f4-11e8-9c72-5d3e9fae3ff0.jpg)

**Comment by milesfei** [comment]
今天使用 valgrind 分别压测 一小时 和 一天，低压力，下面是两次的结果对比：
![heap_summary](https://user-images.githubusercontent.com/7608113/40718242-ef150b4c-6441-11e8-81e8-ac75f8c7ae2b.jpg)
![leak_summary](https://user-images.githubusercontent.com/7608113/40718590-2eca881a-6443-11e8-83a4-26c222bd9bd2.jpg)

现在的现象是，低压力下100qps，内存也是持续增长，涨幅并不下降（纵轴：内存M，横轴：时间h）：
![line_8011](https://user-images.githubusercontent.com/7608113/40718416-75f7ef44-6442-11e8-9e83-cfa4996cc04e.jpg)

在大压力下1000qps，内存增长现象：

求大神指点

**Comment by ike47** [comment]
> 使用rpc作为服务收请求，该服务同时还会作为client请求其他服务，中间的处理逻辑只有解析包和组装包，发现内存也会增长，1000qps持续压测，如下图（横轴：时间h，纵轴：内存M）：

我也遇到了服务端作为client请求其他服务内存增长的问题。
