### ISSUE TITLE
 brpc/src/butil/sys_byteorder.h 的实现能否修改下

### ISSUE THREAD

**Issue by gtlbupt** [brpc/brpc#346]
问题背景
在编译 mac 版本的braft时 master，编译src/braft/protobuf_file.cpp 出错。对应头文件
#include <butil/iobuf.h>
#include <butil/sys_byteorder.h>
#include "braft/protobuf_file.h"

出错原因: 
protobuf_file.h 依赖的brpc/butil/time/time.h, 
                             time.h 里面包含了 <CoreFoundation/CoreFoundation.h>
butil/sys_byteorder.h 里面包含了 
name butil {
#include <libkern/OSByteOder.h> 
}
sys_byteorder.h 导致了#include <libkern/OSByteOder.h>  里面的函数和宏定义
命名空间从全局到 butil:: 里面了。

当存在如下#include 顺序时
#include <butil/sys_byteorder.h>
#include "braft/protobuf_file.h"
protobuf_file.h 里面的<CoreFoundation/CoreFoundation.h> 依赖的宏定义就会找不到。

希望能改成sys_byteorder.h 文件
把对应的#include 放到 namespace util 外面。类似
#include <libkern/OSByteOder.h> 
namespace butil {
}
这样的我理解就不会有问题了。或者其他解决方案都可以。

编译 braft 的临时解决方案: 把  protobuf_file.cpp 依赖的 protobuf_file.h 调整到#include 的最前面

编译 braft 时具体错误信息如下: 
In file included from github/braft/src/braft/protobuf_file.cpp:20:
In file included from github/braft/src/braft/protobuf_file.h:22:
In file included from github/braft/src/braft/file_system_adaptor.h:21:
In file included from github/brpc/build_mac/output/include/butil/file_util.h:28:
In file included from github/brpc/build_mac/output/include/butil/files/file.h:23:
In file included from github/brpc/build_mac/output/include/butil/time/time.h:33:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:48:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFByteOrder.h:33:10: error: use of undeclared identifier
      'OSBigEndian'; did you mean 'butil::OSBigEndian'?
    case OSBigEndian: return CFByteOrderBigEndian;
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libkern/OSByteOrder.h:61:5: note: 'butil::OSBigEndian' declared here
    OSBigEndian

**Comment by zyearn** [comment]
嗯，这个我改一下。之前编raft也遇到了同样的问题，调整了一下顺序可以暂时编过

**Comment by jamesge** [comment]
直接提pr也行。

**Comment by jamesge** [comment]
this issue was not fixed yet.
