### ISSUE TITLE
http持续下载是否支持下载限速？

### ISSUE THREAD

**Issue by NedyWang** [brpc/brpc#347]
llibcurl有下载限速的功能，请问使用brpc http持续下载的是否支持下载限速？

**Comment by jamesge** [comment]
这个不用brpc来提供吧，用户自己做更灵活。

**Comment by NedyWang** [comment]
谢谢回复。 自己做限速确定可以，现在也是这么做的，我觉得如果brpc支持的话，代码就不用分散在2块了。
