### ISSUE TITLE
 channel无法剔除故障节点，疑似bug

### ISSUE THREAD

**Issue by TousakaRin** [brpc/brpc#348]
- client使用连接池方式发起rpc时，名字服务的某一个节点挂掉了(ping不通),channel没有正确的剔除该节点并开启健康检查线程。controller的错误一直是timeout

- 看了一下源码似乎是因为rpc设置的超时时间比channel的tcp连接超时时间要短，导致socket发现network unreachable之后，controller已经在执行超时的逻辑，并没有看到Socket返回的unreachable的错误码。

- 将rpc超时时间从200ms设置成1000ms之后，能够正确剔除挂掉的节点。controller的错误也从timeout变成network unreachable(前两次timeout，第三次unreachable)

- 将Connection_type从pooled改成长连接也能够正常的启动健康检查线程

- 复现的时候使用的example里的echo_c++，连接方式使用连接池，名字服务用的list://wrong_ip，0.0.0.0:8000，lb用的rr。其他都是默认值。

以上的情况属于bug还是说在设置参数的时候本来就应该确保连接超时小于rpc超时呢

**Comment by jamesge** [comment]
感谢报告问题，已在本地复现。我解释一下这个问题的原因：pooled中加在load balancer中的是主socket，它其中不会有tcp连接，但会包含一个SocketPool，每次rpc使用的是socket都是从这个pool取的。这种父子结构的好处有个固定的socket代表对端，可以加到各种结构中去，而不用频繁删改；但缺点是子socket出错时要判断对应的错误是不是意味着主socket也可能挂了，像超时的话可能是子socket个例也可能是主socket问题，所以目前是没有认为主socket挂掉的。这个case的话，连续错误多次就认为主socket挂掉能解决，但从通用的角度是熔断功能的一部分，brpc在这块还系统排查一下。个别LB（如LA）会对错误做惩罚，对这个问题倒是免疫的。

**Comment by soul-tuan-z** [comment]
我看[代码](https://github.com/brpc/brpc/blob/6d153dd7ff00f960ae6895c9c5fff0ce9f07aff2/src/brpc/socket.cpp#L1371)里是有在判断连续超时次数，并试图将多次超时的错误作为Network unreachable来返回的。
文档里也说明了连接断开的节点会被剔除：

> 连接断开的server会被暂时隔离而不会被负载均衡算法选中，brpc会定期连接被隔离的server，以检查他们是否恢复正常，间隔由参数-health_check_interval控制:

希望能够尽快排查一下。

**Comment by jamesge** [comment]
#413
