### ISSUE TITLE
ubuntu下编译报错

### ISSUE THREAD

**Issue by wuzhidefeng** [brpc/brpc#349]
1、未定义的uint32，此处是不是uint32_t错写成uint32了？见下图
./src/butil/third_party/snappy/snappy-internal.h: In function ‘int butil::snappy::internal::FindMatchLength(const char*, const char*, const char*)’:
./src/butil/third_party/snappy/snappy-internal.h:135:9: error: ‘uint32’ was not declared in this scope
         uint32 x = UNALIGNED_LOAD32(s2) ^ UNALIGNED_LOAD32(s1 + matched);
         ^
./src/butil/third_party/snappy/snappy-internal.h:135:16: error: expected ‘;’ before ‘x’
         uint32 x = UNALIGNED_LOAD32(s2) ^ UNALIGNED_LOAD32(s1 + matched);
                ^
./src/butil/third_party/snappy/snappy-internal.h:136:53: error: ‘x’ was not declared in this scope
         int matching_bits = Bits::FindLSBSetNonZero(x);
2、静态断言错误
src/butil/files/file_posix.cc: In member function ‘int64_t butil::File::Seek(butil::File::Whence, int64_t)’:
./src/butil/macros.h:173:34: error: static assertion failed: off_t_64_bit
 #define BAIDU_CASSERT(expr, msg) static_assert(expr, #msg)
                                  ^
./src/butil/macros.h:218:36: note: in expansion of macro ‘BAIDU_CASSERT’
 #define COMPILE_ASSERT(expr, msg)  BAIDU_CASSERT(expr, msg)
                                    ^
src/butil/files/file_posix.cc:286:3: note: in expansion of macro ‘COMPILE_ASSERT’
   COMPILE_ASSERT(sizeof(int64_t) == sizeof(off_t), off_t_64_bit);
   ^
make: *** [src/butil/files/file_posix.o] 错误 1

**Comment by jamesge** [comment]
ubuntu什么版本？
