### ISSUE TITLE
timer_thread.cpp中schedule的问题。

### ISSUE THREAD

**Issue by cotyb** [brpc/brpc#351]
@jamesge 
TimerThread::schedule()首先调用Bucket::schedule()，Bucket::schedule()中对_nearest_run_time 进行了更新。
`    {
        BAIDU_SCOPED_LOCK(_mutex);
        task->next = _task_head;
        _task_head = task;
        if (task->run_time < _nearest_run_time) {
            _nearest_run_time = task->run_time;
            earlier = true;
        }
    }`
TimerThread::schedule()之后再根据earlier判断是否futex_wake_private()。
`    if (result.earlier) {
        bool earlier = false;
        const int64_t run_time = butil::timespec_to_microseconds(abstime);
        {
            BAIDU_SCOPED_LOCK(_mutex);
            if (run_time < _nearest_run_time) {
                _nearest_run_time = run_time;
                ++_nsignals;
                earlier = true;
            }
        }
        if (earlier) {
            futex_wake_private(&_nsignals, 1);
        }
    }`
既然Bucket::schedule()中更新_nearest_run_time 为abstime，TimerThread::schedule()中再去判断run_time是否小于_nearest_run_time，这样是不是会出现run_time永远小于_nearest_run_time的情况？Bucket::schedule()中_nearest_run_time = task->run_time;这句是不是应该删除掉？

**Comment by jamesge** [comment]
Bucket::_nearest_run_time和TimerThread::_nearest_run_time是两个东西，是不是有误解？
