### ISSUE TITLE
最大并发数与排队理论

### ISSUE THREAD

**Issue by iqiyiadsrv** [brpc/brpc#352]
文档中说最大并发度的设置根据排队理论得来：最大并发度 = 极限QPS * 平均延时 (little's law)
但是内置服务中有一个叫processing的bvar表示服务正在处理的请求数，我们完全可以通过压测到极限QPS的时候观察processing的大小，将其设为最大并发度即可，好像用不到排队理论。

**Comment by jamesge** [comment]
processing只能管到server内部用户态的部分，像epoll通知的延时，读取延时，写出延时等等都是感知不到的，而基于little's law的话会更加通用一些。
