### ISSUE TITLE
同时建立2个组合Channel

### ISSUE THREAD

**Issue by NedyWang** [brpc/brpc#355]
A 和(B1,B2,B3..... Bn)建立了连接（使用组合Channel)，  A和(B1,B2,B3..... Bn)能不能使用组合Channel再次建立连接，也就是2个组合channel ？  （因为我希望B有更新的时候【比如新增了个Bn+1】，使用新的Channel，并且不影响正在使用的旧的Channel派发任务）

**Comment by jamesge** [comment]
可以，不同的Channel对象之间是没有直接的影响的，但底层可能会共享或复用连接。

**Comment by NedyWang** [comment]
底层共享或者复用连接的时候会不会有竞争？  我看round roubin channel里面使用了DoublyBuffer？

**Comment by jamesge** [comment]
你是担心性能么？这个影响很小的

**Comment by NedyWang** [comment]
因为我在项目中遇到了问题。 所以想请教下方案的合理性。

A 和(B1,B2,B3..... Bn)建立了1组ParallelChannell连接，因为B集合有变化，所以我又新建了1组ParallelChannell，希望后面的任务使用新建的ParallelChannell，不影响原先的ParallelChannell任务下发。

自测过程中，是没有问题的，上线后却出现了问题。  1个是doubly_buffer_data里面报的phtread_create_key: ResourceTemporarilyUnavaiable.   还有1个就是subcall的时候报E12错误。

**Comment by jamesge** [comment]
channel太多了把

**Comment by NedyWang** [comment]
subchannel加起来应该有4800个了， 请问channel太多为什么会导致这个问题呢？

**Comment by jamesge** [comment]
pthread_key有个数限制的。为什么要同时访问这么多channel？这里是不是本身有改进空间

**Comment by NedyWang** [comment]
谢谢前辈解惑，线上的点太多了，所以会有这么多channel， 后面我会改进下方案。
