### ISSUE TITLE
有计划支持opentracing吗？

### ISSUE THREAD

**Issue by billowqiu** [brpc/brpc#356]
现在微服务中必不可少的tracing也有opentracing标准了，有计划加入这个么？

**Comment by jamesge** [comment]
我理解opentracing只是规范了API，并没有规范存储和传输格式（ABI)，由于brpc中的tracing其实并不需要用户来创建和终结span，所以我不是特别明白适配opentracing的作用，你的理解是？

**Comment by billowqiu** [comment]
我说的opentracing可能比较容易引起误解，其实是说实现opentracing的api，从而在用户使用brpc的时候，可以根据自己内部的需要，将数据上报到实现了opentracing的[supported-tracers](http://opentracing.io/documentation/pages/supported-tracers)

**Comment by billowqiu** [comment]
span.proto里面的SpanAnnotation和TracingSpan好像在代码中没有使用到？
