### ISSUE TITLE
关于bthread_id_t的疑问

### ISSUE THREAD

**Issue by iillydan** [brpc/brpc#357]
bthread_id_t的高32位为ResourcePool生成的slot，但ResourcePool最多支持65536个group，每个group支持1<<16个block，每个block支持BLOCK_NITEM个item，这样slot理论上是可能超出32个bit的吧？

**Comment by jamesge** [comment]
是的，这里是假定bthread_id_t不太可能超过40亿的

**Comment by iillydan** [comment]
Alright~
