### ISSUE TITLE
Tools build failed for incorrect Makefile.

### ISSUE THREAD

**Issue by applee** [brpc/brpc#36]
Build failed for missing appending $(CPPFLAGS) to CXXFLAGS variable in toos/rpc_*/Makefile, e.g. [here](https://github.com/brpc/brpc/blob/8ed718087241af9eaccf8ab3aecb194d7a04559b/tools/rpc_press/Makefile#L3)

**Comment by jamesge** [comment]
@applee  fixed, thanks for reporting
