### ISSUE TITLE
macos 10.12.6 make出错

### ISSUE THREAD

**Issue by houjincheng1992** [brpc/brpc#360]
编译的出错的信息如下：
Compiling src/brpc/policy/streaming_rpc_protocol.o
Compiling src/brpc/policy/ubrpc2pb_protocol.o
Compiling src/brpc/policy/weighted_round_robin_load_balancer.o
Packing libbrpc.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbrpc.a(atomicops_internals_x86_gcc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbrpc.a(asan_invalid_access.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbrpc.a(thread_restrictions.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbrpc.a(baidu_naming_service.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbrpc.a(giano_authenticator.o) has no symbols
Linking protoc-gen-mcpack
Linking libbrpc.dylib
Undefined symbols for architecture x86_64:
  "_CRYPTO_THREADID_set_callback", referenced from:
      brpc::SSLThreadInit() in ssl_helper.o
  "_CRYPTO_THREADID_set_numeric", referenced from:
      brpc::SSLGetThreadId(crypto_threadid_st*) in ssl_helper.o
  "_EVP_PKEY_base_id", referenced from:
      brpc::SSLGetDHCallback(ssl_st*, int, int) in ssl_helper.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libbrpc.dylib] Error 1
麻烦相关人帮忙看看原因～～

**Comment by zyearn** [comment]
brew装一下openssl，然后手动软连接到系统lib

**Comment by houjincheng1992** [comment]
@zyearn hi,我是在使用make时候出现的这个问题，是因为我没有安装openssl吗?

**Comment by houjincheng1992** [comment]
找到make时候的问题了，我的brew install将openssl 安装在了/usr/local/opt/openssl/位置下，使用/usr/local/ 这样的路径就不太合适了
