### ISSUE TITLE
bthread读写锁

### ISSUE THREAD

**Issue by NedyWang** [brpc/brpc#363]
在bthread.h中有对bthread_rwlock_XXX的声明，但是没有找到对应的实现，请问这个是没有实现么？

**Comment by yichenluan** [comment]
没有实现，我认为实际问题在于，你必须证明你的场景下使用读写锁性能会比互斥锁好，如果是，你其实应该使用别的并发结构而不是读写锁。

**Comment by NedyWang** [comment]
谢谢，现在采用的其他的实现方式。  “其实应该使用别的并发结构而不是读写锁”， 这个是为啥呢？

**Comment by yichenluan** [comment]
我说我的理解哈，读写锁的实现没什么特别的，通过额外一个 Mutex 来管理一个 counter，RWMutex 性能好于 Mutex 的情况往往意味着临界区非常大。那么你的场景是要求性能吗，如果不是，直接用 Mutex 即可，简单不容易搞错；如果是，那么你要么要想办法优化临界区的大小，要么换其他并发数据结构来提高并发性能。

**Comment by NedyWang** [comment]
厉害了，学习了，确实，如果单从性能和底层实现角度来说，确实是像你说的这样的。
