### ISSUE TITLE
example 运行无法找到第三方库

### ISSUE THREAD

**Issue by renzhong** [brpc/brpc#365]
因为不想依赖系统库，我使用源码编译了 gflags、glog、leveldb、protobuf 库，放在一个独立的目录下，这种情况下编译 example 的例子，会如下图的问题。

![image](https://user-images.githubusercontent.com/1164327/41229166-9ee82f30-6dad-11e8-9da3-8915a05fb13a.png)

测试发现是 example/echo_c++/Makefile 中可能有问题
![image](https://user-images.githubusercontent.com/1164327/41229284-03915bd2-6dae-11e8-8580-67e56007a814.png)
上图中56行，没有添加` SOPATHS `变量，添加后可以解决问题，但我不确定这样修改是否符合这里 makefile 的预期，比如是不是56行，是不是故意不想依赖动态库？
感谢帮忙确认一下这个问题。

**Comment by zyearn** [comment]
为什么要close，有什么结论？@renzhong

**Comment by renzhong** [comment]
56行加上 `SOPATHS` 不行，运行时会报错，提示 gflags 同时被静态和动态依赖，我觉得我改错了，所以就关了。
我理解56行的意图是把`STATIC_LINKINGS`定义的库，用静态链接，所以不需要`SOPATHS`定义的路径了，对吗？
我后来还是使用了系统安装的 leveldb、gflags，使用58行的编译方式，`ldd echo_client` 只提示 glog 库找不到，自己通过 LD_PRELOAD 解决了。
