### ISSUE TITLE
有支持client端https的计划吗

### ISSUE THREAD

**Issue by machunleilei** [brpc/brpc#37]

**Comment by jamesge** [comment]
Duplicate of #5
server端支持https.

**Comment by machunleilei** [comment]
我看server端是支持，client端能支持吗？

**Comment by jamesge** [comment]
@old-bear

**Comment by old-bear** [comment]
有，年底应该会加上，基本思路都有了

**Comment by machunleilei** [comment]
@old-bear @jamesge 挺好的，期待

**Comment by liuxyc** [comment]
server 端可以先用HAProxy的ssl  termination应付一下 :)

**Comment by machunleilei** [comment]
@old-bear 目前client支持https定了上的日期了吗？期待好久了。谢谢

**Comment by jamesge** [comment]
春节前会进行开发 @old-bear

**Comment by jamesge** [comment]
这个已经开发结束了，在内部测试调整中。

**Comment by jamesge** [comment]
Already supported, the remaining issue was stated in #325
