### ISSUE TITLE
mac下cmake编译失败

### ISSUE THREAD

**Issue by hawkingrei** [brpc/brpc#371]
### 环境

macos high Sierra 10.13.5
xcode 9.3

$ uname -a
Darwin o0o.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64 i386 Macmini7,1 Darwin

$ brew list --versions
ack 2.22
apr 1.6.3
apr-util 1.6.1_1
autoconf 2.69
autojump 22.5.1
automake 1.16.1
awscli 1.15.40
bazel 0.14.1
cmake 3.11.4
coreutils 8.29
ctags 5.8_1
eigen 3.3.4
ffmpeg 4.0.1
freeimage 3.17.0_1
freetype 2.9.1
fzf 0.17.4
gcc 8.1.0
gdbm 1.15
gettext 0.19.8.1
gflags 2.2.1
gifsicle 1.91
gifski 0.8.3
gmp 6.1.2_2
gnu-getopt 1.1.6
gnu-sed 4.5
gnu-tar 1.30
go 1.10.3
golangci-lint 1.7 1.7.2
gotags 1.4.1
gperftools 2.7
hh 1.25
htop 2.2.0
ilmbase 2.2.1
imagemagick 7.0.8-2
isl 0.19
jpeg 9c
jq 1.5_3
lame 3.100
leptonica 1.76.0
leveldb 1.20_2
libevent 2.1.8
libffi 3.2.1
libidn2 2.0.5
libmpc 1.1.0
libpng 1.6.34
libssh2 1.8.0
libtiff 4.0.9_3
libtool 2.4.6_1
libunistring 0.9.10
libyaml 0.1.7
llvm 6.0.0
lz4 1.8.2
maven 3.5.3
mercurial 4.6.1
mpfr 4.0.1
mycli 1.16.0
mysql 8.0.11
numpy 1.14.5
oniguruma 6.8.2
opencv 3.4.1_5
opencv@2 2.4.13.6_2
openexr 2.2.0_1
openssl 1.0.2o_2
openssl@1.1 1.1.0h
pcre 8.42
perl 5.26.2
pkg-config 0.29.2
protobuf 3.5.1_1
python 3.6.5_1
python@2 2.7.15_1
readline 7.0.3_1
reattach-to-user-namespace 2.6
rename 1.600
rocksdb 5.13.3 5.13.4
ruby 2.5.1
rustup-init 1.11.0
snappy 1.1.7_1
sphinx-doc 1.7.5_1
sqlite 3.24.0
subversion 1.10.0_1
tbb 2018_U4
tesseract 3.05.01 3.05.02
thefuck 3.27
tig 2.3.3
tmux 2.7
tree 1.7.0
ttygif 1.4.0
ttyrec 1.0.8_1
urlview 0.9-20
utf8proc 2.1.1
wget 1.19.5
x264 r2854
xclip 0.13
xvid 1.3.5
xz 5.2.4
zsh 5.5.1

### 环境变量
export CPLUS_INCLUDE_PATH=/usr/local/opt/openssl/include
export CPATH=/usr/local/opt/openssl/include
export LIBRARY_PATH=/usr/local/opt/openssl/lib

### 步骤

$mkdir testbuild
$cd testbuild
$cmake -DBUILD_UNIT_TESTS=ON ..
$cd ..
$make -j4

### 报错信息
/Users/bilibili/myresearch/brpc/test/flat_map_unittest.cpp:1188:20: error: no member named 'clear' in 'butil::PooledMap<unsigned
      long long, long, 512, std::__1::less<unsigned long long> >'
        pooled_map.clear();
        ~~~~~~~~~~ ^
/Users/bilibili/myresearch/brpc/test/flat_map_unittest.cpp:1248:5: note: in instantiation of function template specialization
      '(anonymous namespace)::perf_seek<long>' requested here
    perf_seek<long>(100);
    ^
/Users/bilibili/myresearch/brpc/test/flat_map_unittest.cpp:1190:13: error: type 'butil::PooledMap<uint64_t, long>' (aka
      'PooledMap<unsigned long long, long>') does not provide a subscript operator
            pooled_map[keys[i]] = value;
            ^~~~~~~~~~ ~~~~~~~
/Users/bilibili/myresearch/brpc/test/flat_map_unittest.cpp:1215:38: error: no member named 'find' in 'butil::PooledMap<unsigned
      long long, long, 512, std::__1::less<unsigned long long> >'
            sum += (long&)pooled_map.find(keys[i])->second;
                          ~~~~~~~~~~ ^
/Users/bilibili/myresearch/brpc/test/flat_map_unittest.cpp:1188:20: error: no member named 'clear' in 'butil::PooledMap<unsigned
      long long, (anonymous namespace)::Dummy1, 512, std::__1::less<unsigned long long> >'
        pooled_map.clear();
        ~~~~~~~~~~ ^
/Users/bilibili/myresearch/brpc/test/flat_map_unittest.cpp:1249:5: note: in instantiation of function template specialization
      '(anonymous namespace)::perf_seek<(anonymous namespace)::Dummy1>' requested here
    perf_seek<Dummy1>(Dummy1());
    ^
/Users/bilibili/myresearch/brpc/test/flat_map_unittest.cpp:1190:13: error: type 'butil::PooledMap<uint64_t, Dummy1>' (aka
      'PooledMap<unsigned long long, (anonymous namespace)::Dummy1>') does not provide a subscript operator
            pooled_map[keys[i]] = value;
            ^~~~~~~~~~ ~~~~~~~
/Users/bilibili/myresearch/brpc/test/flat_map_unittest.cpp:1215:38: error: no member named 'find' in 'butil::PooledMap<unsigned
      long long, (anonymous namespace)::Dummy1, 512, std::__1::less<unsigned long long> >'
            sum += (long&)pooled_map.find(keys[i])->second;
                          ~~~~~~~~~~ ^
/Users/bilibili/myresearch/brpc/test/flat_map_unittest.cpp:1188:20: error: no member named 'clear' in 'butil::PooledMap<unsigned
      long long, (anonymous namespace)::Dummy2, 512, std::__1::less<unsigned long long> >'
        pooled_map.clear();
        ~~~~~~~~~~ ^
/Users/bilibili/myresearch/brpc/test/flat_map_unittest.cpp:1250:5: note: in instantiation of function template specialization
      '(anonymous namespace)::perf_seek<(anonymous namespace)::Dummy2>' requested here
    perf_seek<Dummy2>(Dummy2());
    ^
/Users/bilibili/myresearch/brpc/test/flat_map_unittest.cpp:1190:13: error: type 'butil::PooledMap<uint64_t, Dummy2>' (aka
      'PooledMap<unsigned long long, (anonymous namespace)::Dummy2>') does not provide a subscript operator
            pooled_map[keys[i]] = value;
            ^~~~~~~~~~ ~~~~~~~
/Users/bilibili/myresearch/brpc/test/flat_map_unittest.cpp:1215:38: error: no member named 'find' in 'butil::PooledMap<unsigned
      long long, (anonymous namespace)::Dummy2, 512, std::__1::less<unsigned long long> >'
            sum += (long&)pooled_map.find(keys[i])->second;
                          ~~~~~~~~~~ ^

**Comment by zyearn** [comment]
cmake -DBUILD_UNIT_TESTS=ON .. 后为什么要cd到上一层目录？上一层是brpc的make系统

**Comment by hawkingrei** [comment]
上面是我的问题，但是我把过程改成
$cmake -DBUILD_UNIT_TESTS=ON .
$make -j4
依旧报错

**Comment by zyearn** [comment]
按照[这里](https://github.com/brpc/brpc/blob/master/docs/cn/getting_started.md)的步骤试一下吧，先看看能不能不加UT编正确. mkdir build_cmake && cd build_camke && cmake .. && make

**Comment by zyearn** [comment]
编译器用的是clang么

**Comment by hawkingrei** [comment]
编译器用的clang（xcode），gcc我直接卸载了，然后我分别运行 cmake .. 和 cmake cmake -DBUILD_UNIT_TESTS=ON ..

前者成功，后者失败

**Comment by zyearn** [comment]
最新master修复这个问题了，再试一下

**Comment by hawkingrei** [comment]
这个问题已经修复了，之前有问题的地方已经可以编译了
