### ISSUE TITLE
TX2上编译出现错误

### ISSUE THREAD

**Issue by UBTNAVI** [brpc/brpc#375]
c++: error: unrecognized command line option ‘-msse4’
c++: error: unrecognized command line option ‘-msse4.2’
src/CMakeFiles/BUTIL_LIB.dir/build.make:62: recipe for target 'src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/dmg_fp/g_fmt.cc.o' failed
make[2]: *** [src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/dmg_fp/g_fmt.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
c++: error: unrecognized command line option ‘-msse4’
c++: error: unrecognized command line option ‘-msse4.2’
src/CMakeFiles/BUTIL_LIB.dir/build.make:86: recipe for target 'src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/dmg_fp/dtoa_wrapper.cc.o' failed
make[2]: *** [src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/dmg_fp/dtoa_wrapper.cc.o] Error 1
CMakeFiles/Makefile2:243: recipe for target 'src/CMakeFiles/BUTIL_LIB.dir/all' failed
make[1]: *** [src/CMakeFiles/BUTIL_LIB.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target OBJ_LIB
[  1%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/detail/sampler.cpp.o
[  1%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/detail/percentile.cpp.o
[  1%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/default_variables.cpp.o
c++: error: unrecognized command line option ‘-msse4’
c++: error: unrecognized command line option ‘-msse4’
c++: error: unrecognized command line option ‘-msse4.2’
c++: error: unrecognized command line option ‘-msse4.2’
src/CMakeFiles/OBJ_LIB.dir/build.make:62: recipe for target 'src/CMakeFiles/OBJ_LIB.dir/bvar/detail/sampler.cpp.o' failed
make[2]: *** [src/CMakeFiles/OBJ_LIB.dir/bvar/detail/sampler.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/CMakeFiles/OBJ_LIB.dir/build.make:86: recipe for target 'src/CMakeFiles/OBJ_LIB.dir/bvar/detail/percentile.cpp.o' failed
make[2]: *** [src/CMakeFiles/OBJ_LIB.dir/bvar/detail/percentile.cpp.o] Error 1
c++: error: unrecognized command line option ‘-msse4’
c++: error: unrecognized command line option ‘-msse4.2’
src/CMakeFiles/OBJ_LIB.dir/build.make:110: recipe for target 'src/CMakeFiles/OBJ_LIB.dir/bvar/default_variables.cpp.o' failed
make[2]: *** [src/CMakeFiles/OBJ_LIB.dir/bvar/default_variables.cpp.o] Error 1
CMakeFiles/Makefile2:93: recipe for target 'src/CMakeFiles/OBJ_LIB.dir/all' failed
make[1]: *** [src/CMakeFiles/OBJ_LIB.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jamesge** [comment]
这是arm平台？先去掉-msse4和-msse4.2看看其他错误
