### ISSUE TITLE
持续下载中断后OnEndOfMessage没有调用

### ISSUE THREAD

**Issue by NedyWang** [brpc/brpc#385]
如题，实现了ProgressiveReader进行持续下载，如果因为网络原因或者服务器中断的话，OnEndOfMessage是一直没有调用的。 请问这个情况是啥原因？ 怎么知道连接是中断了？

**Comment by jamesge** [comment]
这是会调用的，如果是tcp丢失了FIN包要在下次读写或心跳时才能发现。

**Comment by NedyWang** [comment]
谢谢大神～  我进行了压力测试，部分是没有调用的，目前来看，应该是server中断的流传输，连接应该还在，所以OnEnfOfMessage就一直不会调用，似乎也没有超时机制去验证连接一段时间没有读写就关闭的功能？ 所以得应用层自己去判断。
