### ISSUE TITLE
使用VIP形式访问Redis只有单一连接的问题

### ISSUE THREAD

**Issue by whutaihejin** [brpc/brpc#386]
1. 使用方法：
   采用brpc访问redis，列表中写了多个相同的VIP，并采用pooled方式进行连接。
2. 具体问题
   期望能过建立多个TCP以连接所有VIP后面的真实IP，但从具体netstat结果看仅有一个连接，这样导致VIP后面的实体机器无法流量均衡(流量只打到一台实体机器上).

**Comment by jamesge** [comment]
假定你现在是用形如"list://vip1, vip2, ... "的方式来做服务发现的，在ip或域名后加上不同的tag就会被认为是不同的下游，比如"list://vip1 tag1, vip2 tag2", 对"file://..."也是类似的。

**Comment by whutaihejin** [comment]
1. 使用方法
  地址模式：list://vip:port tag1,vip:port tag2,...,vip:port tag10
  连接方式：pooled
  负载算法：rr
2. 具体问题
2.1 连接不均衡问题：首先从机制上来说，当创建一个面向VIP的TCP连接后，后面的RS即确定了，并且这个RS不会再变更，这个是目前VIP普遍采用的机制。如此，当一个client与某个vip建立了三条连接a,b,c，并且vip后面也恰有3个rs，就可能会出现a->rs1, b->rs1, c->rs3，rs2空闲的情况。这个应该是VIP机制问题，没有根本的解决版本，只能从创建大量连接来稀释或者减缓该问题。尚且称该问题为连接不均衡问题。
2.2 请求不均衡问题：我们尚且假设连接是均衡的，另一个问题是我们利用每个连接来发送请求是否是均衡的。比如我们建立的10条连接来发送100条请求，如果每个连接发送的请求数期望值是10那么可以认为请求是均衡的；如果用第一个连接发送了55条请求，其余连接每个发送了5条请求，那么这种情况即为请求不均衡问题。
3. 实验求证
利用上面1中的方式，通用tcpdump抓包，具体数据如下：
  13095 *.*.*.*.10244 > *.*.*.*.3110
  22464 *.*.*.*.12815 > *.*.*.*.3110
  25275 *.*.*.*.13122 > *.*.*.*.3110
  15657 *.*.*.*.13124 > *.*.*.*.3110
  19054 *.*.*.*.13125 > *.*.*.*.3110
  29771 *.*.*.*.13126 > *.*.*.*.3110
  20606 *.*.*.*.13293 > *.*.*.*.3110
  25933 *.*.*.*.13300 > *.*.*.*.3110
  30066 *.*.*.*.13301 > *.*.*.*.3110
   7506 *.*.*.*.15092 > *.*.*.*.3110
  21658 *.*.*.*.15093 > *.*.*.*.3110
  26229 *.*.*.*.15094 > *.*.*.*.3110
  20669 *.*.*.*.15095 > *.*.*.*.3110
   8095 *.*.*.*.15096 > *.*.*.*.3110
  27461 *.*.*.*.15097 > *.*.*.*.3110
  30261 *.*.*.*.16475 > *.*.*.*.3110
  21358 *.*.*.*.16476 > *.*.*.*.3110
  21645 *.*.*.*.16477 > *.*.*.*.3110
  24230 *.*.*.*.17779 > *.*.*.*.3110
  22582 *.*.*.*.18159 > *.*.*.*.3110
  12872 *.*.*.*.18306 > *.*.*.*.3110
   7495 *.*.*.*.22082 > *.*.*.*.3110
  21097 *.*.*.*.22968 > *.*.*.*.3110
  22148 *.*.*.*.22969 > *.*.*.*.3110
  21643 *.*.*.*.22972 > *.*.*.*.3110
  34249 *.*.*.*.24913 > *.*.*.*.3110
  27070 *.*.*.*.26858 > *.*.*.*.3110
   6717 *.*.*.*.27114 > *.*.*.*.3110
  13013 *.*.*.*.27645 > *.*.*.*.3110
   2760 *.*.*.*.27646 > *.*.*.*.3110
  13177 *.*.*.*.27647 > *.*.*.*.3110
  10613 *.*.*.*.27648 > *.*.*.*.3110
   4758 *.*.*.*.27649 > *.*.*.*.3110
  10532 *.*.*.*.27650 > *.*.*.*.3110
   9701 *.*.*.*.27651 > *.*.*.*.3110
  29977 *.*.*.*.38599 > *.*.*.*.3110
  28281 *.*.*.*.38602 > *.*.*.*.3110
  25796 *.*.*.*.44066 > *.*.*.*.3110
  31952 *.*.*.*.44140 > *.*.*.*.3110
  30290 *.*.*.*.46191 > *.*.*.*.3110
  23674 *.*.*.*.46612 > *.*.*.*.3110
  17692 *.*.*.*.51581 > *.*.*.*.3110
  30486 *.*.*.*.51597 > *.*.*.*.3110
  19934 *.*.*.*.53362 > *.*.*.*.3110
  17216 *.*.*.*.53364 > *.*.*.*.3110
  24614 *.*.*.*.53670 > *.*.*.*.3110
  21939 *.*.*.*.53671 > *.*.*.*.3110
  23015 *.*.*.*.53672 > *.*.*.*.3110
  14259 *.*.*.*.53673 > *.*.*.*.3110
  28183 *.*.*.*.53676 > *.*.*.*.3110
   1848 *.*.*.*.53677 > *.*.*.*.3110
  14234 *.*.*.*.53678 > *.*.*.*.3110
   9365 *.*.*.*.53679 > *.*.*.*.3110
  27114 *.*.*.*.53681 > *.*.*.*.3110
  22647 *.*.*.*.53682 > *.*.*.*.3110
  15874 *.*.*.*.53684 > *.*.*.*.3110
   8847 *.*.*.*.63670 > *.*.*.*.3110
  23984 *.*.*.*.64390 > *.*.*.*.3110
其中3110为VIP端口，可以发现每个连接所发包的数量确实是不均衡的。在用brpc作为client访问redis的时候发现连接数是不确定的，那么具体发送的请求的时候是如何做均衡的呢？还请作者给予答疑。
ps：另一个简单粗暴的方法是就是每个end_point建立一定数量的连接比如10或者100，然后rr利用这些连接发送请求。
