### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by 7zkeeper** [brpc/brpc#39]
Makefile:2: config.mk: 没有那个文件或目录
/bin/sh: 第 0 行:test: -ge: 期待一元表达式
/bin/sh: 第 0 行:test: -ge: 期待一元表达式
make: *** 没有规则可以创建目标“config.mk”。 停止。

**Comment by jamesge** [comment]
https://github.com/brpc/brpc/blob/master/docs/cn/getting_started.md

**Comment by chenzhangyi** [comment]
reopen this issue if something is wrong when you follow the guide.
