### ISSUE TITLE
brpc streaming发送数据问题

### ISSUE THREAD

**Issue by dl239** [brpc/brpc#392]
用brpc streaming发送数据有时候报错
src/brpc/input_messenger.cpp:88] Fail to parse response from xxxx:9991 by streaming_rpc at client-side
src/brpc/input_messenger.cpp:249] Close fd=18 SocketId=1243@xxxx:9991@39948: absolutely wrong message

建立stream时和example一样，用的BAIDU_STD, options.protocol = brpc::PROTOCOL_BAIDU_STD
求教这是什么问题

**Comment by dl239** [comment]
A给B发RPC请求的时候，A给B发送streaming数据 有问题
A给B发RPC请求的时候，B给A发送streaming数据 正常
从log看是接受包给搞混了？

**Comment by chenzhangyi** [comment]
上下文有更多日志吗，或者贴下可以复现的代码?

**Comment by dl239** [comment]
@jamesge @chenzhangyi 辛苦看下哈

**Comment by unlimitlearning** [comment]
我现在也遇到了这个问题，请问楼主找到解决方案了吗

**Comment by cstarc** [comment]
也遇到了类似问题，当A在给B发送普通rpc请求是，同时发送stream，同一个端口，同一个service，会出现此错误， 分开端口就没问题，是不能同一个端口？

**Comment by wwbmmm** [comment]
好像是普通rpc和streaming rpc不能混用一个连接，可以考虑把普通rpc的connection_type设置成pooled试试

**Comment by reachfish** [comment]
我也遇到这种报错了

**Comment by CodeTrek** [comment]
这个问题没有解决方案吗？

**Comment by zhuxinlong** [comment]
这个问题原因是什么，感觉不好理解啊

**Comment by zhuxinlong** [comment]
定位到原因了，stream rpc 建流是特殊的rpc ,请求是PRPC,但是回包是STRM,所以建流和流传输都是回的STRM,如果夹杂普通的PRPC,就会回PRPC包，就会客户端解析失败

**Comment by ahnselina** [comment]
> 定位到原因了，stream rpc 建流是特殊的rpc ,请求是PRPC,但是回包是STRM,所以建流和流传输都是回的STRM,如果夹杂普通的PRPC,就会回PRPC包，就会客户端解析失败

你好，我也遇到这个问题了，我这边是偶现的，启动的时候有时会报这个错误，有时又不会，看你的解释，意思是普通的rpc和那种stream的rpc必须分开用不同的接口吗，我这边目前是混用的

**Comment by unlimitlearning** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
