### ISSUE TITLE
使用brpc加载so，在so中创建pthread并使用bthread_usleep，会导致主程序中的bthread不被调度

### ISSUE THREAD

**Issue by ch541819** [brpc/brpc#395]
如题。
so中的创建pthread代码如下：
pthread_create(&_monitor_tid, NULL, _monitor, this)
...
static void* _monitor(void *param) {
    ...
    bthread_usleep(bufs->_monitor_interval * 1000000);
}

**Comment by jamesge** [comment]
不被调度是什么意思

**Comment by ch541819** [comment]
不被调度的现象，就是主线程中，A函数调用B函数，B函数返回后，不会继续执行A的剩余部分代码，而是必需等到so的sleep唤醒后才会继续执行
