### ISSUE TITLE
使用glog 会导致 ./test_bvar 测试失败

### ISSUE THREAD

**Issue by qxiang88** [brpc/brpc#40]
在编译时如果使用glog(--with-log),  会导致test/test_bvar 测试失败；原因好像是框架代码里面使用了 LOG(FATAL) 直接terminate了(test/bvar_variable_unittest.cpp: 69行 对应 bvar/variable.cpp:177行).

**Comment by chunyang-wen** [comment]
贴出具体错误信息，大家才好分析。

**Comment by chenzhangyi** [comment]
It's likely fixed at HEAD, please try pull and recompile the test. Reopen this issue if not.
