### ISSUE TITLE
brpc如何实现一来多回，也就是推送？

### ISSUE THREAD

**Issue by xueyibing** [brpc/brpc#400]
看到brpc的服务都是一个请求一个回包，那么怎么实现推送呢，订阅之后，持续推送给客户端，有没有例子啊？

**Comment by xueyibing** [comment]
服务端异步调用done->Run()，把done保存起来，是可以调用多次吗？谢谢

**Comment by jamesge** [comment]
一次性的，每次通知都需要client先注册，long polling就是这么工作的。如果server给client的是数据流，且client也是brpc，可以用[streaming rpc](https://github.com/brpc/brpc/blob/master/docs/cn/streaming_rpc.md)协议；如果client不是brpc，可以用[持续发送 ](https://github.com/brpc/brpc/blob/master/docs/cn/http_service.md#%E6%8C%81%E7%BB%AD%E5%8F%91%E9%80%81)或websocket(不支持)。

**Comment by zhengshf** [comment]
@jamesge 有支持websocket的计划么？

**Comment by kevinmgyu** [comment]
websocket 现在支持吗
