### ISSUE TITLE
对外服务支持 http+protobuf 么

### ISSUE THREAD

**Issue by iamlcx** [brpc/brpc#406]
如题，看到jsontopb那里说 http+json是对外服务的常见方式，那支持http+protobuf么，我试了下好像不行。。。。

**Comment by jamesge** [comment]
https://github.com/brpc/brpc/blob/1b865a890584ab13a3a16b12c8b29298ae273473/docs/cn/server.md#%E8%A2%ABhttp-client%E8%AE%BF%E9%97%AE
