### ISSUE TITLE
traceprint 打印不全

### ISSUE THREAD

**Issue by gtarcoder** [brpc/brpc#407]
在 BRPC server中，请求经过的函数中调用了 TRACEPRRINT() 函数 多次，但是在 enable 了 rpcz 之后，查看到的trace 只有两条。

**Comment by jamesge** [comment]
跨线程了么

**Comment by gtarcoder** [comment]
在 BRPC server的接口处理函数中 xxServiceImpl::xxx () ，依次调用了多个函数，其中的某个函数会开启多个 bthread 执行任务。整个过程类似：
1. 入口， xxServiceImpl::xxx ()
1.1 调用--> A()
1.2 调用--> B()
1.3 调用--> C()
                    1.3.1 bthread 并行调用 --> X()
                    1.3.2 bthread 并行调用 --> Y()
                     wait bthreads finish
1.3 调用 -->D()
 
在函数A， B, C, D中都 调用  TRACEPRINT 打印，但是只有两条被打印出来。（每个请求都这样）

**Comment by gtarcoder** [comment]
@jamesge

**Comment by gtarcoder** [comment]
@jamesge 
在 BRPC server的接口处理函数中 xxServiceImpl::xxx () ，依次调用了多个函数，其中的某个函数会开启多个 bthread 执行任务。整个过程类似：

入口， xxServiceImpl::xxx ()
1.1 调用--> A()
1.2 调用--> B()
1.3 调用--> C()
1.3.1 bthread 并行调用 --> X()
1.3.2 bthread 并行调用 --> Y()
wait bthreads finish
1.3 调用 -->D()
在函数A， B, C, D中都 调用 TRACEPRINT 打印，但是只有两条被打印出来。（每个请求都这样）

**Comment by jamesge** [comment]
已复现问题和初步定位，会尽快修复，感谢反馈。

**Comment by jamesge** [comment]
已修复。

**Comment by gtarcoder** [comment]
@jamesge  赞！！
