### ISSUE TITLE
ProgressiveReader 能主动释放连接和对象吗？

### ISSUE THREAD

**Issue by cdjingit** [brpc/brpc#408]
看注释，只能数据读写完成，或者连接错误了。调用OnEndOfMessage。
能有方法主动释放这个连接和这个对象吗？

**Comment by jamesge** [comment]
注意OnReadOnePart的注释，返回的错误被视作永久性的，也会导致结束。

**Comment by cdjingit** [comment]
那就是我只能这么释放：
设置一个flag，当下次有数据读写的时候，OnReadOnePart检查如果设置了该flag，直接返回错误，然后触发调用OnEndOfMessage
如果很长时间没有新的数据，那么只能保持这个连接。

**Comment by NedyWang** [comment]
可是如果长时间保持这个连接的话，那么就会导致这部分的内存长时间无法释放的。

**Comment by NedyWang** [comment]
如果OnNewMessage里面出错的话，会怎么样？  我这里是OnReadOnPart和OnEndOfMessage都是没有被调用的。

**Comment by NedyWang** [comment]
如果连接没有断，但是长时间没有读写，client端怎样才能主动的关闭这个连接呢？

**Comment by cdjingit** [comment]
好像没有其他方法，只有设置一个flag 等待下次有数据时 直接返回失败

**Comment by cdjingit** [comment]
好像没有其他方法，只有设置一个flag 等待下次有数据时 直接返回失败

**Comment by zyearn** [comment]
这个可以用TCP的SO_KEEPALIVE选项解决，不过目前还在测试中
