### ISSUE TITLE
DoublyBufferedData 写后为什么还要再改一遍新后台？

### ISSUE THREAD

**Issue by xiaohei520321** [brpc/brpc#410]
看描述和代码，里面有这样几句话
```
1. 检索线程只读前台
2. 同时只有一个写：修改后台数据，切换前后台，挨个获得所有thread-local锁并立刻释放，结束后再改一遍新后台（老前台）
```
既然读只读前台，写的时候是先写后台，然后把后台再切换到前台，最后为什么还要再改一遍新后台？
感觉最后改的这个后台没有意义啊？求解惑？是有什么应用场景需要新老后台一致？

**Comment by cdjingit** [comment]
增量修改的情况。基于后台现在的数据修改

**Comment by xiaohei520321** [comment]
@cdjingit 能说具体点吗？感觉Modify最后那次修改后台的数据没什么意义啊，线程读的都是前台。

**Comment by xiaohei520321** [comment]
看了round_robin_load_balancer.cpp里的使用，我明白了

**Comment by fezho** [comment]
@xiaohei520321 请问是什么原因也需要修改老的后台数据？

**Comment by lorinlee** [comment]
> @xiaohei520321 请问是什么原因也需要修改老的后台数据？

前台数据和后台数据是会交替切换的，修改一次就切换一次，所以修改操作要在两个数据都执行的
