### ISSUE TITLE
服务端的逻辑使用线程池的疑问

### ISSUE THREAD

**Issue by renzhong** [brpc/brpc#411]
我 server 的逻辑是切分以后放到DelegateSimpleThreadPool中执行的，参考DelegateSimpleThreadPool的例子，server 端 bthread 会通过 WaitableEvent 等待所有的任务结束，再继续执行。
我有点想不明白，担心这样的实现会不会导致 server 端的这个 bthread 阻塞，无法处理其他的请求？感觉应该做个类似异步的逻辑，把任务放到线程池后，自己就把 bthread 交回系统，等所有的任务结束，再把当前的请求唤醒。
我的担心有必要吗？后面这个思路在 brpc 里容易实现吗？需要用哪些组件？

**Comment by jamesge** [comment]
DelegateSimpleThreadPool那些是一些开源时的legacy code，只在UT里用到，建议不使用。server中要并发直接启动bthread就行了。
