### ISSUE TITLE
brpc 服务程序假死

### ISSUE THREAD

**Issue by gtarcoder** [brpc/brpc#412]
已经两次遇到过这种情况，brpc 服务存活着，机器内存，cpu，网络负载都正常，但是BRPC web 页面无法打开。且所有到该服务的请求，均失败。
这种情况是什么原因呢？

**Comment by gtarcoder** [comment]
@jamesge  戈大能给看下不？

**Comment by jamesge** [comment]
https://github.com/brpc/brpc/blob/master/docs/cn/server_debugging.md

**Comment by gtarcoder** [comment]
@jamesge  我遇到的问题是，进程还在，但是curl 不通， brpc server的web 页面也打不开（所以没法通过 server_debugging中的各种手段来看）。从机器本身看，CPU，内存使用情况没有异常。

**Comment by jamesge** [comment]
看pstack或gdb attach上去

**Comment by gtarcoder** [comment]
@jamesge  gdb attach 上去了，发现程序死锁。通过高QPS 压力测试，发现情况可以复现：
程序相关线程情况：
（1）后台线程 (pthread)
timer thread 1， 读取mysql，写入 DoublyBufferedData-1
timer thread 2,  读取mysql，写入 DoublyBufferedData-2
timer thread 3,  读取mysql，写入 DoublyBufferedData-3
timer thread 4,  读取mysql，写入 DoublyBufferedData-4
timer thread 5,  读取mysql，写入 DoublyBufferedData-5
timer thread 6,  读取redis，写入 DoublyBufferedData-6
timer thread 定时5秒执行一次回调函数

（2）任务处理线程(bthread) (高QPS的场景下，会开很多):
读取 DoublyBufferedData-1
读取 DoublyBufferedData-6
处理请求

测试场景：
max_concurrency 设置为200； 在 QPS > 500 的压力下测试，发生死锁。死锁发生时候的栈：
（1）timer thread 1--6, 停在 bthread/timer_thread.cpp:431 futex_wait_private(&_nsignals, expected_signals, timeout)

（2）任务处理线程，停在 butil/containers/doubly_bufferd_data.h:222 BeginRead() 

我发现不了为啥会死锁，是因为QPS x latency 远远大于 max_concurrency ？ 如果是这样，那BRPC 框架不应该这样处理高QPS场景。死锁的时候，curl 不通，我感觉这也很不合理。

**Comment by jamesge** [comment]
1. 为什么有这么多timer thread，是你自己的开的么？timer thread的callback一旦阻塞会阻塞整个timer thread，所以一般是要额外启动bthread去运行复杂逻辑的。
2. 为什么要用DoublyBufferedData？直觉上用到mysql的场景对qps要求应该不高，不需要用到这个东西。
3. concurrency等于qps * latency(单位秒），计算一下200是否合理。

**Comment by gtarcoder** [comment]
Hi 戈大，@jamesge   
1. timer thread 是自己开的。 timer thread的callback 就是读取mysql，然后将数据写入 DoublyBufferedData, 逻辑并不复杂。

2. 我们的场景，QPS 很高，在处理请求的时候，会用到mysql中的数据，所以采用 doublybuffereddata 读写分离，防止每次都从mysql读取。写线程（timer thread）定时读取 mysql，并写入 doublybuffereddata，读线程处理用户请求的时候，从doublybuffereddata中读取数据。

3. qps * latency 有时候会超过 max_concurency.  那么，如果 qps * latency 超过了 max_concurrency, 理论上会出现什么情况呢？ 如果可以确定死锁是由于 qps * latency > concurrency 导致的，那我可以增加机器，但我现在没法确定是由于 qps * latency > concurrency 导致的

**Comment by yjhjstz** [comment]
最好写个最小化可重现程序。

**Comment by gethinzhang** [comment]
应该是ScopedPtr的范围太大了，之前我们也碰到类似问题了，ScopedPtr及时释放就好了，不要等到函数结束再释放

**Comment by gtarcoder** [comment]
@solrex  是这个问题。

**Comment by ccy4fun** [comment]
@gtarcoder 我们也遇到了死锁情况，你是怎么解决的？有伪代码解释吗？

**Comment by gtarcoder** [comment]
@ccy4fun  不确定你遇到的问题是否和我们是相同的原因。我之前死锁的原因是： 使用了 brpc里面的 doublybuffereddata，bthread A （位于pthread X上）使用 ScopedPtr 去读取 doublybuffereddata 里面的数据时候(此时获取 pthread local lock)，Scope的范围内部 执行了一个 IO 操作，IO 操作导致 bthread 线程切换； 此时 bthread B （也位于 pthread X上），执行同样的 读取 doublybuffereddata 操作，也获取 pthread local lock, 这样就导致 一个pthread 上，两次获取 thread local lock，从而死锁。

当时的解决方案就是，在 ScopedPtr 内部不要进行 IO 操作（以及其他一些可能导致bthread 发生切换的操作）

**Comment by muziandmuzi** [comment]
我这也遇到了好几次，还不清楚是啥原因造成的
