### ISSUE TITLE
butil::Timer 计时失真问题

### ISSUE THREAD

**Issue by machaelliu** [brpc/brpc#414]
`#include <iostream>
#include <butil/time.h>
#include <unistd.h>

int main(int argc, char* argv[]) {
  struct timeval tv, tv1;
  gettimeofday(&tv,NULL);
  butil::Timer timer(butil::Timer::STARTED);
  sleep(5);
  timer.stop();
  gettimeofday(&tv1,NULL);
  std::cout << "butil timer cost: " << timer.m_elapsed() << "ms"  << std::endl;
  std::cout << "gettimeofday cost: " <<  (tv1.tv_sec - tv.tv_sec)*1000.0 + 
    (tv1.tv_usec - tv.tv_usec)/1000.0<< "ms" << std::endl;
                                                         
  return 0;
}`

---- 输出 -----
butil timer cost: 4374ms
gettimeofday cost: 5000.12ms

环境： Centos 7.3.1611
CPU: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt

**Comment by jamesge** [comment]
我的机器上同样的代码结果是
```
butil timer cost: 5000ms
gettimeofday cost: 5000.54ms
```
cpuinfo也包含了constant_tsc(the TSC runs at constant frequency irrespective of P/T- states)和nonstop_tsc(TSC does not stop in deep C-states)，说明tsc是可用作wall-time的。
2620也是百度比较常见的cpu型号，之前似乎也不记得有相关的问题，要么和os有关系？

**Comment by machaelliu** [comment]
我把能拿到的所有环境都试过了，腾讯云上的 ubuntu、阿里云上的 centos7.0, 7.4 都没有问题，只有部分实体机上的 centos7.1  和 centos 7.3 有失真问题。
有两台实体机的 cpu 完全一样，一个装的是 centos 6 没有问题，有相同cpu 的另外一台安装了 centos7.1 的就失真了，我也怀疑是操作系统本身的问题。

有操作系统参数会影响 rdtsc 指令的精确性吗？

**Comment by jamesge** [comment]
也有可能是cpuinfo不准确

**Comment by hairet** [comment]
这个问题我们使用的时候也遇到过，brpc里是否考虑把rdtsc换掉，比如用clock_gettime？
因为不少文章说过rdtsc在x86多核体系下不准，主要原因貌似有每个核的TSC不同步，以及cpu降频和乱序执行等原因。

**Comment by jamesge** [comment]
brpc只有在cpu支持constant_tsc和nonstop_tsc时才使用rdtsc，这是符合rdtsc正确的使用方式的。
