### ISSUE TITLE
支持lz4压缩

### ISSUE THREAD

**Issue by scottzzq** [brpc/brpc#415]
option.proto中定义了lz4压缩，但是代码没有实现，有计划支持lz4压缩吗？

**Comment by jamesge** [comment]
目前没有计划，如果你有兴趣的话可以集成进来。在rpc的场景下，lz4只需要一个lz4.c和lz4.h文件就行了，可以放src/butil/third_party/lz4下。集成是继承CompressHandler，尽量避免内存拷贝。

**Comment by HappenLee** [comment]
集成该部分代码时，添加lz4.c和lz.h之后，test编译出错，需要修改哪部分代码？
