### ISSUE TITLE
sofa client升级到brpc client机器网络带宽翻倍？

### ISSUE THREAD

**Issue by scottzzq** [brpc/brpc#417]
从应用层监控到response的字节数没有明显变化，统计方法是计算response的ByteSize 1分钟内的和。这个可能是什么原因造成的呢？

**Comment by jamesge** [comment]
qps也没有变化么

**Comment by scottzzq** [comment]
@jamesge  没有变化

**Comment by scottzzq** [comment]
今天一直以为是压缩算法导致的，结果后来发现用同样的压缩算法，带宽还是不一样，所以最终确定了和压缩算法没关系，和用brpc client有关系。

**Comment by jamesge** [comment]
brpc用的也是sofa-pbrpc协议么？

**Comment by scottzzq** [comment]
Server是sofa协议，这次是给client端升级，所以是用了brpc的client，但是协议还是sofa协议

**Comment by jamesge** [comment]
那你可能需要检查一下累加ByteSize的代码是不是有问题了。
