### ISSUE TITLE
Iobuf中movable的使用场景

### ISSUE THREAD

**Issue by leonwu327** [brpc/brpc#418]
Iobuf在append(iobuf.movable())方法中，moveable()的使用场景是什么？

**Comment by jamesge** [comment]
就是append(std::move(iobuf))在C++03中的一种实现

**Comment by leonwu327** [comment]
在跨线程调用append(iobuf)时，会出现内存泄漏，但是调用append(iobuf.movable())时就不会泄露，这个可能是什么原因呢？

**Comment by jamesge** [comment]
跨线程什么意思，如果a.append(b)中a,b分别在被不同的线程操作，那么就是错的。
