### ISSUE TITLE
bthread_mutex_unlock的实现疑似有bug?

### ISSUE THREAD

**Issue by hairet** [brpc/brpc#419]
最近在看bthread的协程锁的代码，看到bthread_mutex_unlock发现有点问题。bthread_mutex_unlock里面const unsigned prev = whole->exchange(0, butil::memory_order_release);
    // CAUTION: the mutex may be destroyed, check comments before butex_create
    if (prev == BTHREAD_MUTEX_LOCKED) {
        return 0;
    }
这里合理的做法应该是互斥状态下判断prev==BTHREAD_MUTEX_LOCKED才执行whole->exchange(0, butil::memory_order_release);并retrun返回，此时表示无竞争者，直接放锁。
如果prev!=BTHREAD_MUTEX_LOCKED,不能直接exchange然后再去butex_wake调度waiters(因为一旦exchange放锁，此时有其他线程或者bthread来竞争此锁，就会导致其他线程或者bthread和waiter同时占锁)？
麻烦作者帮忙解答一下，看libgo的co_mutex实现，有考虑此问题，不会在有waiter的时候，直接放锁。

**Comment by hairet** [comment]
补充一下，上面提到的prev==BTHREAD_MUTEX_LOCKED加执行whole->exchange(0, butil::memory_order_release);2步操作也是需要被另外一把锁或者spinlock来保护。

**Comment by hairet** [comment]
上面有疑问的代码在https://github.com/brpc/brpc/blob/master/src/bthread/mutex.cpp的790~805行，完整函数代码如下：
`int bthread_mutex_unlock(bthread_mutex_t* m) {
    butil::atomic<unsigned>* whole = (butil::atomic<unsigned>*)m->butex;
    bthread_contention_site_t saved_csite = {0, 0};
    if (bthread::is_contention_site_valid(m->csite)) {
        saved_csite = m->csite;
        bthread::make_contention_site_invalid(&m->csite);
    }
    const unsigned prev = whole->exchange(0, butil::memory_order_release);
    // CAUTION: the mutex may be destroyed, check comments before butex_create
    if (prev == BTHREAD_MUTEX_LOCKED) {
        return 0;
    }
    // Wakeup one waiter
    if (!bthread::is_contention_site_valid(saved_csite)) {
        bthread::butex_wake(whole);
        return 0;
    }
    const int64_t unlock_start_ns = butil::cpuwide_time_ns();
    bthread::butex_wake(whole);
    const int64_t unlock_end_ns = butil::cpuwide_time_ns();
    saved_csite.duration_ns += unlock_end_ns - unlock_start_ns;
    bthread::submit_contention(saved_csite, unlock_end_ns);
    return 0;
}`

**Comment by jamesge** [comment]
没什么关系，如果有”其他bthread“和waiter同时抢锁，它们仍然会在lock处互斥。

**Comment by hairet** [comment]
看到了，原来mutex_lock_contended里面的
while (whole->exchange(BTHREAD_MUTEX_CONTENDED) & BTHREAD_MUTEX_LOCKED) {
        if (bthread::butex_wait(whole, BTHREAD_MUTEX_CONTENDED, NULL) < 0 &&
            errno != EWOULDBLOCK && errno != EINTR/*note*/) {
            // a mutex lock should ignore interrruptions in general since
            // user code is unlikely to check the return value.
            return errno;
        }
    }
这里exchange是个while,之前没注意。看到有waiter,就下意识默认以为是排队锁，以为像libgo那样被唤醒的waiter直接从前一个锁主转移锁的所有权。那就没疑问了，感谢作者同学^_^
