### ISSUE TITLE
客户端异步访问回调函数可以使用lambda表达式吗~

### ISSUE THREAD

**Issue by xueyibing** [brpc/brpc#420]
https://github.com/brpc/brpc/blob/master/docs/cn/client.md#%E5%BC%82%E6%AD%A5%E8%AE%BF%E9%97%AE

**Comment by jamesge** [comment]
`brpc::NewCallback([](){ .... })`

**Comment by xueyibing** [comment]
auto b = brpc::NewCallback([](int a){});
不可以带参数吗，加上int a 参数编译报错：
 错误：invalid user-defined conversion from ‘CnsServerSession::ProcessSyncMsgConversationInfo(ClientSession*, const HEADER&, const char*, int)::__lambda0’ to ‘void (*)()’ [-fpermissive]
     auto b = brpc::NewCallback([](int a){});

**Comment by xueyibing** [comment]
难道只可以用 brpc::NewCallback([](){ .... })这种不带参数的函数类型吗？只要加了参数或者捕获值就会编译报错
