### ISSUE TITLE
brpc异步调用应用场景的疑问

### ISSUE THREAD

**Issue by scottzzq** [brpc/brpc#423]
既然brpc的同步调用只会阻塞bthread，不会阻塞pthread, 那什么场景需要用异步调用？只针对单次rpc调用。

**Comment by jamesge** [comment]
1. brpc的接口既可以在pthread中也可以在bthread中调用，在pthread中发起同步调用阻塞的是pthread，此时异步调用就不会阻塞pthread。
2. 异步调用的内存开销最小，而一个阻塞的bthread会占用一个栈。
