### ISSUE TITLE
brpc服务端写成异步,退出时调用Join阻塞

### ISSUE THREAD

**Issue by mahbgit** [brpc/brpc#429]
我的服务端是这样写的:
先按配置文件数量启动若干pthread线程.这些线程会从一个任务队列竞争取task.开始时任务队列是空的
然后启动brpc server.接口响应时,在接口回调中把几个参数包装成task传给任务队列,由任务线程来处理请求并回复.done参数在回调中最后调用了release,任务线程处理任务时每个任务的处理函数开头调用done_guard.
退出时,调用server.stop,server.join退出
状况是处理请求时都正常,但是最后退出时join会阻塞.
请帮忙看看这样有什么问题吗?

**Comment by jamesge** [comment]
Join卡住就说明还有done没有被调用。

**Comment by mahbgit** [comment]
请问有什么办法能跟踪done没有被调用的情况吗,我代码过了好几次觉得应该都调用了啊.
任务处理函数开头调用done_guard之后就不用管了吧.

**Comment by mahbgit** [comment]
加了日志,发现确实是这样.任务线程先结束了,但是回调仍然在收请求,最后的done没处理.
谢谢指点
