### ISSUE TITLE
不是说支持java吗

### ISSUE THREAD

**Issue by quanjj008** [brpc/brpc#43]
不是说支持java吗？戈君：brpc于2014年创建，在百度内部称为“baidu-rpc”。到目前为止，brpc一共进行了3000次左右的改动，现在仍在持续优化中，百度内的wiki上可以查询到每次改动的描述。brpc的主要语言是C++和Java，对其他语言的支持主要是通过包装C++版本，比如brpc的Python版包含C++版的大部分功能。

**Comment by hemooooed** [comment]
hi alllll

**Comment by chenzhangyi** [comment]
duplicated with #2

**Comment by hemooooed** [comment]
hi
