### ISSUE TITLE
work_stealing_queue的原子屏障疑问？

### ISSUE THREAD

**Issue by spch2008** [brpc/brpc#432]
bool steal(T* val) {
      size_t t = _top.load(butil::memory_order_acquire);
      size_t b = _bottom.load(butil::memory_order_acquire);
      if (t >= b) {
          return false;
      }
  
      do {
          butil::atomic_thread_fence(butil::memory_order_seq_cst);
          b = _bottom.load(butil::memory_order_acquire);
          if (t >= b) {
              return false;
          }
          *val = _buffer[t & (_capacity - 1)];
      } while (!_top.compare_exchange_strong(t, t + 1,
                                             butil::memory_order_seq_cst,
                                             butil::memory_order_relaxed));
      return true;
    }

  上面代码来自bhtread/work_stealing_queue.h中，一直没有明白`butil::atomic_thread_fence(butil::memory_order_seq_cst)` 这句代码是为了保护哪个变量？对于_top变量的写入，下面compare_exchange_strong中已经指定seq_cst，而steal函数中，无其他store操作。如果仅是读，我理解acquire足矣。困惑许久，望指点，谢谢。

**Comment by gydong** [comment]
为什么会说“而**steal函数中**，无其他store操作”，我理解这个fence的作用不限于streal函数中，也可能与pop,push等函数同步？

**Comment by spch2008** [comment]
我觉得不是，这里除了_top，没有其他store操作，用acquire能解决现在的问题，我觉得这句代码是多余的。

**Comment by seafeawea** [comment]
同疑问这里

**Comment by spch2008** [comment]
@jamesge 戈大神能否答疑下，跪谢。

**Comment by jamesge** [comment]
这是和[94行](https://github.com/brpc/brpc/blob/ef4eddde8b861780ab3ccc3abda3e806e0ea3f09/src/bthread/work_stealing_queue.h#L94)的seq_cst配对，确保steal线程能看到新的_bottom，如果没有的话，第一次cas失败的steal线程还是看不到更新后的_bottom，就不会被[124行](https://github.com/brpc/brpc/blob/ef4eddde8b861780ab3ccc3abda3e806e0ea3f09/src/bthread/work_stealing_queue.h#L124)的判定拒绝，而会去更新t，最终导致pop误判。一个例子是pop走到95行时，t=newb+1=b+2，且正好有两个steal线程在争抢cas，失败的那个steal线程回到do while开头看到的还是没变化的b，从而会继续更新t，最后让t=b，而pop也会由于t != newb这个判定同样成功，从而导致问题。

**Comment by spch2008** [comment]
@jamesge 感谢戈神解答，有一点还是不清楚。如果是与94行的seq_cst配对使用，为什么不采用在pop中：_bottom.store(seq_cst)，而在steal中：_bottom.load(seq_cst)。各个编译器在不同平台对store/load的seq_cst实现是不一致，对于x86/gcc，store是mfence+mov，load就是mov。而如果采用atomic_thread_fence，则默认会添加mfence，即load的时候也会有mfence，这个指令是耗时的，而且我觉得是没有必要的，求戈神解答是否有其它原因？

**Comment by jamesge** [comment]
这个和atomic的实现有一定关联，b.store(seq_cst)可能也只会带release语意(acquire对store没意义），b.load(seq_cst)也可能只会带acquire，写成atomic_thread_fence更明确一些。

**Comment by spch2008** [comment]
感谢戈神！

**Comment by icylord** [comment]
work_stealing_queue 跟两个消费者使用 SPMC有什么区别不？
