### ISSUE TITLE
ParallelChannel 如何支持 http client 并发请求

### ISSUE THREAD

**Issue by AoZhang** [brpc/brpc#435]
使用brpc实现http客户端，并发向多个 server 发送不同的 request，改如何实现 CallMapper 呢？

**Comment by pklim101** [comment]
> http方式是支持ParallelChannel的，但是只能支持不同Server发送相同的请求。这是由于http只能使用CallMethod设置request和response为NULL的方式调用，没法在CallMapper和ResponseMerger中对不同的Server构造不同的请求并Merge应答。如果需要向不同的http server发送不同的请求，最简单的方式就是使用半同步的方式来实现ParallelChannel，也可以通过CountDownEvent和bthread_start_backgroud实现，或者是定制CallMethod的Done来实现。

ParallelChannel里response不能设置为NULL。
"we don't support http whose response is NULL"
