### ISSUE TITLE
请问，E2004这个错误要怎么解决？

### ISSUE THREAD

**Issue by xiaohei520321** [brpc/brpc#436]
brpc访问下游服务，返回的错误如下：
[E2004]Too many user code to run when -usercode_in_pthread is on

看了下游服务的cpu，内存都没到瓶颈，是有什么option配的不对？

**Comment by ipconfigme** [comment]
在开启usercode_in_pthread之后，服务端service callback运行在pthread中，服务支持的最大并发跟程序配置的线程数有关，这个日志说明当前请求太多，服务端处理不过来了。在pthread模式下如果有同步阻塞任务可能会导致worker线程全部占满从而导致死锁，因此brpc内部增加了一个额外的backup线程池用于worker线程不够之后把任务跑在额外的线程池上。backup线程池支持的最大任务并发也是有限的，通过FLAGS_usercode_backup_threads * FLAGS_pending_in_each_backup_thread配置进行控制。出现这个日志之后，可以通过ServerOptions.num_threads/bthread_concurrency来调大worker线程数来满足部分需求，同时也需要通过ServerOptions.max_concurrency进行请求限流（不能大于bthread_concurrency）。

**Comment by xiaohei520321** [comment]
@ipconfigme 那如果没有开启usercode_in_pthread，运行在bthread，处理不过来的时候, server会动态增加bthread?

**Comment by ipconfigme** [comment]
这个说法有点问题啊，一个method跑在一个bthread上，并发来了就跑在多个bthread上，M个bthread跑在N个pthread上
