### ISSUE TITLE
bthread stack debug的问题

### ISSUE THREAD

**Issue by gethinzhang** [brpc/brpc#439]
最近在项目中使用brpc，work没什么问题。但是我们提供的框架代码，有时候写算法同学可能会误用一些持锁调度，导致整个服务被卡死。
目前整个coredump，使用gdb基本上没有有价值的信息（因为持锁调度，持锁的bthread可能已经到栈里了），这个时候如果能像golang那样，dump bthread的stack信息就完美了。请问官方最近有支持的计划嘛？我最近打算撸一个，但是如果官方有计划我就不写了。另外作者对这个工具有没有什么额外的建议？

**Comment by chenzhangyi** [comment]
当时做了一下实验，打出了几个地址之后，gdb并没有展开栈信息.  这个可能和百度编译环境是交叉编译的有关, 也可能和boost stack的实现有关。 另外golang这个方式只能针对运行中的进程进行，不能用于分析core dump.

**Comment by yjhjstz** [comment]
强烈建议出个 gdb 插件以展开bthread 调用栈。
