### ISSUE TITLE
从sofa-pbrpc改造brpc之后，server端统计自己处理tp99耗时值出现明显上涨

### ISSUE THREAD

**Issue by scottzzq** [brpc/brpc#442]
如题，已有的一个服务，从sofa-pbrpc框架升级为brpc框架，耗时出现明显上涨，业务流程复杂，server端接收到一个请求，需要发起调用10+次rpc调用，cpu有空闲，机器配置一样,可能的原因是啥？

**Comment by scottzzq** [comment]
用同样的qps压测，用brpc改造后的版本，报大量rpc超时错误，用原来sofa-pbrpc版本不会报超时错误。

**Comment by chenzhangyi** [comment]
参考 https://github.com/brpc/brpc/blob/master/docs/cn/server_debugging.md 排查下， 先看下是不是线程数或者锁的因素.
