### ISSUE TITLE
brpc_redis处理字符串的一个问题

### ISSUE THREAD

**Issue by RuhigSoda** [brpc/brpc#453]
发现利用brpc::RedisRequest发送类似hmset k1 v1 "1234\\"56\\""这样命令，最后读取hmget k1 v1的结果是"123456"；相同的我存储一个json数据结构，拿出来就不是一个json了，这是个bug？

**Comment by RuhigSoda** [comment]
我发现RedisCommandNoFormat函数中有这么一段代码
`    for (const char* c = cmd.data(); c != cmd.data() + cmd.size(); ++c) {
        if (*c == ' ') {
            if (quote_char) {
                compbuf.push_back(*c);
            } else if (!compbuf.empty() || is_empty_component) {
                is_empty_component = false;
                AppendHeader(nocount_buf, '$', compbuf.size());
                compbuf.append("\r\n", 2);
                nocount_buf.append(compbuf);
                compbuf.clear();
                ++ncomponent;
            }
        } else if (*c == '"' || *c == '\'') {  // Check quotation.
            if (!quote_char) {  // begin quote
                quote_char = *c;
                quote_pos = c;
            } else if (quote_char == *c) {  // end quote
                is_empty_component = (c - quote_pos == 1) ? true : false; // for empty string
                quote_char = 0;
            } else {
                compbuf.push_back(*c);
            }
        } else {
            compbuf.push_back(*c);
        }
    }`
把双引号和单引号全部去掉了，不知道原因？
若是想去掉首尾，是不是要加个判断？
`  for (const char* c = cmd.data(); c != cmd.data() + cmd.size(); ++c) {
        if (*c == ' ') {
            if (quote_char) {
                compbuf.push_back(*c);
            } else if (!compbuf.empty() || is_empty_component) {
                is_empty_component = false;
                AppendHeader(nocount_buf, '$', compbuf.size());
                compbuf.append("\r\n", 2);
                nocount_buf.append(compbuf);
                compbuf.clear();
                ++ncomponent;
            }
        } else if (*c == '"' || *c == '\'' && (is_begin || is_end)) {  // Check quotation.
            if (!quote_char) {  // begin quote
                quote_char = *c;
                quote_pos = c;
            } else if (quote_char == *c) {  // end quote
                is_empty_component = (c - quote_pos == 1) ? true : false; // for empty string
                quote_char = 0;
            } else {
                compbuf.push_back(*c);
            }
        } else {
            compbuf.push_back(*c);
        }
        is_begin = false;
        if (c == cmd.data() + cmd.size() - 2) {
          is_end = true;
        }
    }`

**Comment by 2012-wangjiaqi** [comment]
方便的话，也给下测试环境json错误的case吧；我来具体看下

**Comment by RuhigSoda** [comment]
任意一段json数据就可以呀

**Comment by jamesge** [comment]
确实是这么处理的，引号会被忽略。这里可以改成和hiredis行为完全一致。

**Comment by jamesge** [comment]
你可以只在format string里用%s，而把json放对应的变量里来规避这个问题。

**Comment by RuhigSoda** [comment]
嗯嗯，谢谢。。
测试AddCommandByComponents这个函数对发生的转义是免疫的

**Comment by jamesge** [comment]
这块改进了一下 #457

**Comment by RuhigSoda** [comment]
这个改进好像有问题。。。后面我给一下我的测试case
