### ISSUE TITLE
多线程请求 redis 会不会请求和应答对应不上

### ISSUE THREAD

**Issue by renzhong** [brpc/brpc#454]
看了 #248  的讨论，目前我们项目里碰到了请求和应答对应不上的情况，比如 a 线程发送 lpush，b 线程发送 ltrim ，两个线程的请求发送到同一个 redis ip，但是两个线程操作的 redis key 不一样。收到的应答会出现对应错误，a 线程收到的response 类型是 status， b 线程收到的 response 类型是 int。

这是因为出现了 a 线程请求先发出去了，但是 b 线程的 response 先回来了导致的吗？这块如何能验证，或者避免这种问题呢？

**Comment by jamesge** [comment]
redis的response返回顺序是和request严格一致的，不管成功还是失败都要按序返回response，除非redis server出问题了。

**Comment by renzhong** [comment]
后来发现是公司运维系统的 redis 有 proxy，把 redis 的连接方式改成连接池方式，解决了。

**Comment by jamesge** [comment]
proxy保证不了response和request的顺序严格对应么?

**Comment by renzhong** [comment]
我理解这个 proxy 不是 hash 形式和后端对应的。用单连接的方式，发送两个请求，分别是不同的 key，通过 proxy，会对应到两个不同的 redis server 上，两台机器的延时不一样，会导致数据顺序不一致。

**Comment by jamesge** [comment]
可能和proxy的配置有关系，这个proxy其实就是不支持redis的“pipeline”模式了。
