### ISSUE TITLE
请问有支持限流和熔断吗？

### ISSUE THREAD

**Issue by xhzh** [brpc/brpc#46]
我看了一下文档和ppt，没有发现限流和熔断功能的相关信息。
如果有的话，有相关资料吗？ 
如果没有，则你们的考虑是什么？

**Comment by jamesge** [comment]
Server可以[限制最大并发](https://github.com/brpc/brpc/blob/master/docs/cn/server.md#限制最大并发)  这里会谈到[雪崩的原因及对策](https://github.com/brpc/brpc/blob/master/docs/cn/avalanche.md) 限制最大并发是我们认为足够有效又足够简单的保护server的方案。

**Comment by xhzh** [comment]
感谢，其实我认为这就跟线程池的原理类似，我有多少个并发能力，我有个带边界的任务队列。正如你所说，足够简单并且有效。
