### ISSUE TITLE
使用brpc访问http服务，为何这么设计？

### ISSUE THREAD

**Issue by RuhigSoda** [brpc/brpc#461]
使用brpc访问http服务，初始化一个全局的channel，如下：

```cpp
brpc::Channel channel;
brpc::ChannelOptions options;
options.protocol = brpc::PROTOCOL_HTTP;
options.timeout_ms = 100;
std::string url = "http://test111.com";
if (channel.Init(url.c_str(), &options)) {
    LOG_ERR("failed to init channel");
    return -1;
}
```

发现一个问题，再我没有指定lb的情况下，channel会通过gethostbyname()这个系统调用获取该url映射的ip列表，但是它只取第一个ip，以后每次访问都是这个ip，而且后端扩容下线都感知不到，我理解后端如果映射的是一个虚拟ip，应该无关，若不是。。。不理解为何这么设计？ @jamesge

**Comment by jamesge** [comment]
这种模式下的channel就是这样的，会在Init时做一次dns查找，之后就再也不更新了。如果要更新的话，就要指明lb。
