### ISSUE TITLE
bthread调度问题

### ISSUE THREAD

**Issue by xueyibing** [brpc/brpc#463]
在bthread中等待下游服务的回包时候，bthread应该会暂停，当下游回包来的时候，brpc怎么知道要恢复刚刚暂停的bthread，是通过某种ID来调度的吗，那这个ID又存储在哪里呢？Thanks♪(･ω･)ﾉ

**Comment by zyearn** [comment]
如果是异步rpc，bthread不会暂停，如果是同步rpc，bthread会等在一个bthread_id_t上，等到res返回的时候，通过保存的cid（本质上是通过epoll_data来传递同一个socket上的数据/指针），获得当时的上下文cntl，然后调用户回调。文档 https://github.com/brpc/brpc/blob/master/docs/cn/bthread_id.md

**Comment by xueyibing** [comment]
如果多个bthread中同时调用的一个下游客户端请求，即同时用一个socket发送请求，那么多个bthread必然同时等待这一个socket回包，那么此时回来的包如何唤醒，又是如何区分该唤醒哪个bthread呢？
因为我们自己用协程的时候在包体里加了id，所以会知道哪个回包对应哪个协程，
那么bthread又是如何知道哪个回包对应哪个bthread的呢？Thanks♪(･ω･)ﾉ
