### ISSUE TITLE
请问brpc的http功能支持双向认证吗？

### ISSUE THREAD

**Issue by zhouxiangling** [brpc/brpc#464]
请问brpc的http功能支持双向认证吗？有没有例子可供参考

**Comment by zhouxiangling** [comment]
我是指SSL证书双向认证，客户端也要提供ssl证书给服务器，服务器用来验证客户端身份的，主要是用来跟其他企业对接。我看到最新版本的源码中的 ChannelOptions 是有 ChannelSSLOptions  ssl_options 成员变量的，该结构中可以开启 ssl 验证，并且有成员变量  CertInfo client_cert，可以配置 证书和秘钥文件路径。所以想确认一下是否是为了支持https双向证书认证的。[ssl_option.h](https://github.com/brpc/brpc/blob/master/src/brpc/ssl_option.h)

**Comment by jysonet** [comment]
支持了吧，内部好像正在push

**Comment by zhouxiangling** [comment]
好的，我测试一下，非常感谢告知
