### ISSUE TITLE
是不是写上支持哪些版本的dep比较好

### ISSUE THREAD

**Issue by qinhunter** [brpc/brpc#474]
按说明yum装，像gflag，protobuf，都是比较新的版本。但是这样再编译brpc会报错，比如gflag的namespace问题。是不是在INTSTALL写上对不同的deps支持到哪个版本比较好？

**Comment by jamesge** [comment]
https://github.com/brpc/brpc/blob/master/docs/cn/getting_started.md#supported-deps

**Comment by qinhunter** [comment]
之前没注意下面还有内容，多谢
btw，可以考虑把这个标题也写到开头目录里
