### ISSUE TITLE
brpc在macos上make的问题

### ISSUE THREAD

**Issue by xfpg21421** [brpc/brpc#475]
sh config_brpc.sh --headers="/usr/local/include /usr/local/Cellar" --libs="/usr/local/lib /usr/local/Cellar" --cc=clang --cxx clang++

之后执行make，出现如下问题：
（问题发生在MacOS，High Sierra Version 10.13.6）

Compiling src/brpc/policy/weighted_round_robin_load_balancer.o
Packing libbrpc.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libbrpc.a(atomicops_internals_x86_gcc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libbrpc.a(asan_invalid_access.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libbrpc.a(thread_restrictions.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libbrpc.a(baidu_naming_service.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libbrpc.a(giano_authenticator.o) has no symbols
Linking protoc-gen-mcpack
In file included from src/idl_options.pb.cc:4:
In file included from ./src/idl_options.pb.h:25:
In file included from /usr/local/include/google/protobuf/generated_message_table_driven.h:34:
In file included from /usr/local/include/google/protobuf/map.h:49:
In file included from /usr/local/include/google/protobuf/map_type_handler.h:35:
In file included from /usr/local/include/google/protobuf/wire_format_lite_inl.h:43:
/usr/local/include/google/protobuf/message_lite.h:117:3: error: unknown type name 'constexpr'
  constexpr const T& get() const { return reinterpret_cast<const T&>(union_); }
  ^
/usr/local/include/google/protobuf/message_lite.h:117:13: error: expected member name or ';' after declaration specifiers
  constexpr const T& get() const { return reinterpret_cast<const T&>(union_); }
  ~~~~~~~~~ ^
/usr/local/include/google/protobuf/message_lite.h:110:11: error: use of undeclared identifier 'union_'
    new (&union_) T();
          ^
/usr/local/include/google/protobuf/message_lite.h:114:5: error: use of undeclared identifier 'get_mutable'
    get_mutable()->~T();
    ^
/usr/local/include/google/protobuf/message_lite.h:131:48: error: found '<::' after a template name which forms the digraph '<:' (aka '[') and a ':', did you mean '< ::'?
LIBPROTOBUF_EXPORT extern ExplicitlyConstructed<::std::string> fixed_address_empty_string;
                                               ^
/usr/local/include/google/protobuf/message_lite.h:137:37: error: no member named 'get' in 'google::protobuf::internal::ExplicitlyConstructed<std::__1::basic_string<char> >'
  return fixed_address_empty_string.get();
         ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
In file included from src/idl_options.pb.cc:4:
In file included from ./src/idl_options.pb.h:25:
In file included from /usr/local/include/google/protobuf/generated_message_table_driven.h:34:
In file included from /usr/local/include/google/protobuf/map.h:49:
In file included from /usr/local/include/google/protobuf/map_type_handler.h:35:
In file included from /usr/local/include/google/protobuf/wire_format_lite_inl.h:44:
/usr/local/include/google/protobuf/repeated_field.h:123:39: error: expected ';' at end of declaration list
  RepeatedField(RepeatedField&& other) noexcept;
                                      ^
/usr/local/include/google/protobuf/repeated_field.h:124:50: error: expected ';' at end of declaration list
  RepeatedField& operator=(RepeatedField&& other) noexcept;
                                                 ^
/usr/local/include/google/protobuf/repeated_field.h:778:45: error: expected ';' at end of declaration list
  RepeatedPtrField(RepeatedPtrField&& other) noexcept;
                                            ^
/usr/local/include/google/protobuf/repeated_field.h:779:56: error: expected ';' at end of declaration list
  RepeatedPtrField& operator=(RepeatedPtrField&& other) noexcept;
                                                       ^
/usr/local/include/google/protobuf/repeated_field.h:1090:68: error: expected ';' at end of declaration
inline RepeatedField<Element>::RepeatedField(RepeatedField&& other) noexcept
                                                                   ^
/usr/local/include/google/protobuf/repeated_field.h:1090:69: error: unknown type name 'noexcept'
inline RepeatedField<Element>::RepeatedField(RepeatedField&& other) noexcept
                                                                    ^
/usr/local/include/google/protobuf/repeated_field.h:1091:5: error: expected unqualified-id
    : RepeatedField() {
    ^
/usr/local/include/google/protobuf/repeated_field.h:1103:27: error: expected ';' at end of declaration
    RepeatedField&& other) noexcept {
                          ^
/usr/local/include/google/protobuf/repeated_field.h:1103:28: error: C++ requires a type specifier for all declarations
    RepeatedField&& other) noexcept {
                           ^
/usr/local/include/google/protobuf/repeated_field.h:1103:36: error: expected ';' after top level declarator
    RepeatedField&& other) noexcept {
                                   ^
/usr/local/include/google/protobuf/repeated_field.h:1928:30: error: expected ';' at end of declaration
    RepeatedPtrField&& other) noexcept
                             ^
/usr/local/include/google/protobuf/repeated_field.h:1928:31: error: unknown type name 'noexcept'
    RepeatedPtrField&& other) noexcept
                              ^
/usr/local/include/google/protobuf/repeated_field.h:1929:5: error: expected unqualified-id
    : RepeatedPtrField() {
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [protoc-gen-mcpack] Error 1

**Comment by zyearn** [comment]
看看你的clang是不是支持c++11

**Comment by xfpg21421** [comment]
clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

然后在.bashrc里加上下面三行：
alias g++='g++ -std=c++11'
alias gcc='gcc -std=c++11'
alias clang='clang -std=c++11'

再make还是一样的问题。

**Comment by jamesge** [comment]
贴一下brpc根目录下的config.mk内容

**Comment by xfpg21421** [comment]
# Generated by config_brpc.sh, don't modify manually
SYSTEM=Darwin
HDRS=/usr/local/Cellar/openssl/1.0.2p/include/ /usr/local/include/
LIBS=/usr/local/lib
PROTOC=/usr/local/bin/protoc
PROTOBUF_HDR=/usr/local/include/
CC=clang
CXX=clang++
GCC_VERSION=40800
STATIC_LINKINGS= /usr/local/lib/libprotobuf.a /usr/local/lib/libleveldb.a /usr/local/lib/libsnappy.a
DYNAMIC_LINKINGS=-lpthread -lssl -lcrypto -ldl -lz -framework CoreFoundation -framework CoreGraphics -framework CoreData -framework CoreText -framework Security -framework Foundation -Wl,-U,_MallocExtension_ReleaseFreeMemory -Wl,-U,_ProfilerStart -Wl,-U,_ProfilerStop -Wl,-U,_RegisterThriftProtocol -lgflags
CPPFLAGS=-DBRPC_WITH_GLOG=0 -DGFLAGS_NS=google -g -Wno-deprecated-declarations
ifeq ($(NEED_LIBPROTOC), 1)
    STATIC_LINKINGS+=/usr/local/lib/libprotoc.a
endif
ifeq ($(NEED_GPERFTOOLS), 1)
    DYNAMIC_LINKINGS+=-ltcmalloc_and_profiler
endif
ifeq ($(NEED_GTEST), 1)
    $(error "Fail to find gtest")
endif

**Comment by zyearn** [comment]
我本地High Sierra Version 10.13.5，clang版本和你一样，没有复现相同的问题。看你的错误表象是编译器C++11相关的问题
