### ISSUE TITLE
Fail to write into fd=96 SocketId=180388634468@11.7.147.134:35422@8801: Unknown error 1014 [1014]

### ISSUE THREAD

**Issue by LeonWlw** [brpc/brpc#479]
brpc作为http server在处理50并发请求时会出现这个报错，请问一般会是什么原因

**Comment by gydong** [comment]
https://github.com/brpc/brpc/blob/master/docs/cn/server.md#q-fail-to-write-into-fd1865-socketid89051020824543547428230-got-eof%E6%98%AF%E4%BB%80%E4%B9%88%E6%84%8F%E6%80%9D

**Comment by LeonWlw** [comment]
多谢

**Comment by eric-buaa-cn** [comment]
Does "Unknown error 1014"  and "got eof" have the same meaning?

**Comment by chenjianyu** [comment]
同问

**Comment by gydong** [comment]
> Does "Unknown error 1014" and "got eof" have the same meaning?

yes.
