### ISSUE TITLE
Does or will protobuf RPC protocol support encrypted transmission / SSL?

### ISSUE THREAD

**Issue by jasonszang** [brpc/brpc#48]
What should I do if I want to use baidu-std rpc protocol through the public Internet and stay safe, apart from workarounds like encrypting protos and wrap them up in another proto message myself? Are or will there be a better option?

**Comment by jamesge** [comment]
the impl. of SSL in brpc is at socket-layer, which means any protocol provided by brpc can be encrypted by SSL, provided [ServerOptions.ssl_options](https://github.com/brpc/brpc/blob/master/src/brpc/server.h#L264) is properly configured. However SSL client is not provided yet, check #37 for more.

**Comment by jasonszang** [comment]
Thank you very much for your reply. I'll look into that ssl_options. And I look forward to your SSL client.
