### ISSUE TITLE
请问有没有推荐的第三方 protobuf rpc Go 客户端？

### ISSUE THREAD

**Issue by choleraehyq** [brpc/brpc#481]
希望用 Go 调用 C++ 的 brpc service，既然 brpc 支持 protobuf 序列化，那么理论上来说支持 protobuf 的客户端都可以用，有没有推荐的？

另外，看到百度还开源了一个 Go 的基于 protobuf 的 rpc 框架 https://github.com/baidu-golang/pbrpc，可否直接用这个客户端去连 brpc？

**Comment by gydong** [comment]
go 可以用[HTTP协议](https://github.com/brpc/brpc/blob/master/docs/cn/http_service.md)来访问 C++ 的 brpc service。

**Comment by jamesge** [comment]
合入#471 后可以和grpc-go互通，不过仍然需要1-2周时间。

**Comment by jamesge** [comment]
pr更新为 #510

**Comment by jamesge** [comment]
主干已支持grpc, client端协议设置为"h2:grpc"即可，server端无需设置。
