### ISSUE TITLE
brpc的snappy与sofa的不兼容

### ISSUE THREAD

**Issue by guoliushui** [brpc/brpc#486]
brpc的snappy与sofa的不兼容，在echo里protoco设置为sofa-broc,对request设置为snappy压缩，sofa服务端解析不出来，zlib试了一下是可以的

**Comment by jamesge** [comment]
压缩这部分的代码brpc基本上是统一处理的，不知道是不是sofa-pbrpc对这块的理解有所不同，有更多细节么？
