### ISSUE TITLE
多个依赖包路径指定失败

### ISSUE THREAD

**Issue by XiaoxiaoxiaoCoder** [brpc/brpc#49]
当依赖包存在于多个路径，安装文档指定路径的时候，会报错，提示 readlink: extra operand `/usr/include'
Try `readlink --help' for more information. 请问如何处理

**Comment by jamesge** [comment]
什么系统？

**Comment by XiaoxiaoxiaoCoder** [comment]
centos6.9   操作和错误如下：sh config_brpc.sh --headers='/usr/local/protobuf/include /usr/local/include' --libs='/usr/local/protobuf/lib' 
readlink: extra operand `/usr/local/include'
Try `readlink --help' for more information.

**Comment by jamesge** [comment]
再试一下

**Comment by XiaoxiaoxiaoCoder** [comment]
我发现在我系统下，realpath 这个命令不存在，我在config_brpc.sh 脚本中实现了一个realpath () { [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}" ;}
，然后传多个路径的时候，需要将参数用""包含起来--headers ) HDRS_IN="$(realpath "$2")"; shift 2 ;;

**Comment by jamesge** [comment]
看看realpath是不是一个包，fedora下默认是带的，ubuntu下是一个包。
