### ISSUE TITLE
压测时 Enter rpc 的耗时比较长 

### ISSUE THREAD

**Issue by renzhong** [brpc/brpc#496]
![image](https://user-images.githubusercontent.com/1164327/45409253-434e6080-b6a1-11e8-8eea-0f3da5c92364.png)

如图，rpc 内部的处理逻辑比较简单，输入大概是1000条结果，截断成10条，然后返回。输入输出都是 pb 格式。但是通过 rpcz 观察 Enter 方法前花费了3ms，这个主要是处理什么？是不是我的服务器哪里没配置对。压测工具使用的是 brpc 的 do_press

**Comment by chenzhangyi** [comment]
参考https://github.com/brpc/brpc/blob/master/docs/cn/server_debugging.md排查下问题

**Comment by gethinzhang** [comment]
建议先看下 #492 先确认是不是计时有问题
