### ISSUE TITLE
是否支持TLS？

### ISSUE THREAD

**Issue by jiangplus** [brpc/brpc#5]
brpc是否支持TLS或其它加密传输层协议？
如何保证传输的安全性呢？

**Comment by jamesge** [comment]
server端支持[https](https://github.com/brpc/brpc/blob/master/docs/cn/http_service.md#开启https), 另外从实现角度，任何协议都可以开启SSL。

**Comment by loveyacper** [comment]
看到ssl和鉴权好像都支持，还有streaming RPC；
这代码质量、恍惚以为是谷歌开源，真心挺赞。
