### ISSUE TITLE
Is the brpc suitable for the "IPC" ?

### ISSUE THREAD

**Issue by thincal** [brpc/brpc#50]
Hi,

If using the brpc for the IPC mechanism to provide the service to other client inside the device, is there any suggestion ? 

Thanks,
Song

**Comment by jamesge** [comment]
Someone inside baidu may separate ranking policies from engineering framework in the same process by using RPC. The pros: policies are easier to be pluged in or out, much safer than loading shared libs. The cons: have to pay the cost of serialization and context switches.

**Comment by thincal** [comment]
thanks
