### ISSUE TITLE
brpc方法并发为啥不允许运行时修改，而Server级别可以修改

### ISSUE THREAD

**Issue by imotai** [brpc/brpc#500]
rt

**Comment by jamesge** [comment]
老版本是可以修改的，因为那时只支持一种并发控制方式。
在支持通用的ConcurrencyLimiter后，由于其中的"auto"并发控制可以覆盖大部分动态修改的场景，且并不是所有的CL实现都支持动态修改，动态修改就去掉了。
你可以测试下你的动态修改需求是不是直接用auto就行了。

**Comment by jamesge** [comment]
能更细地描述一下这个需要动态修改的场景和需求么

**Comment by TousakaRin** [comment]
@imotai 多谢反馈，我们后续会调整接口，让server启动之后依旧能够动态修改最大并发。

**Comment by imotai** [comment]
> @imotai 多谢反馈，当时之所以去掉这个功能一方面是认为auto可以替代手动修改最大并发的能力，一方面是考虑到加入auto限流之后，再支持server启动之后的手动修改可能会和auto相冲突并引入线程安全问题。我们后续会调整接口，让server启动之后依旧能够动态修改最大并发。

多谢@TousakaRin 能否关注一下https://github.com/brpc/brpc/issues/507
