### ISSUE TITLE
mem bvar统计有错

### ISSUE THREAD

**Issue by hairet** [brpc/brpc#520]
统计mem相关的bavr里，lrs和drs疑似搞反了，代码在
https://github.com/brpc/brpc/blob/master/src/bvar/default_variables.cpp

![image](https://user-images.githubusercontent.com/7167017/46255275-b0e5f380-c4cd-11e8-8bb6-45006ffc22f9.png)

实践了一把，貌似在lrs和drs应该反过来才对

**Comment by jamesge** [comment]
确实有误，感谢汇报。master已修复，同时删除了基本无用的process_memory_library/dirty
