### ISSUE TITLE
bthread_cond_timedwait里为什么需要一个bthread_mutex_t

### ISSUE THREAD

**Issue by hairet** [brpc/brpc#539]
代码如下：
![image](https://user-images.githubusercontent.com/7167017/47344344-d20bbf80-d6da-11e8-9f11-dad670effcc6.png)

bthread_cond_timedwait里面会由外部传入一个bthread_mutex_t，没太明白这里的bthread_mutex_t在cond_wait和signal的配套语义里起到什么作用？

**Comment by jamesge** [comment]
所有的condition都是这么工作的，mutex确保（非原子的）条件失败时等待，这个过程是原子的
