### ISSUE TITLE
A selection runs too long!

### ISSUE THREAD

**Issue by cool-colo** [brpc/brpc#542]
F0606 05:15:44.489768 33520 locality_aware_load_balancer.cpp:285] A selection runs too long!
*** Check failure stack trace: ***
F0606 05:15:44.489774 33530 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489804 33528 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489878 33519 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490068 33521 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490216 33525 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490069 33523 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490301 33526 locality_aware_load_balancer.cpp:285] A selection runs too long!
*** Check failure stack trace: ***
F0606 05:15:44.489774 33530 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489804 33528 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489878 33519 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490068 33521 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490216 33525 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490069 33523 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490301 33526 locality_aware_load_balancer.cpp:285] A selection runs too long!
*** Check failure stack trace: ***
F0606 05:15:44.489774 33530 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489804 33528 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489878 33519 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490068 33521 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490216 33525 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490069 33523 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490301 33526 locality_aware_load_balancer.cpp:285] A selection runs too long!
*** Check failure stack trace: ***
F0606 05:15:44.489774 33530 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489804 33528 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489878 33519 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490068 33521 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490216 33525 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490069 33523 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490301 33526 locality_aware_load_balancer.cpp:285] A selection runs too long!
*** Check failure stack trace: ***
    @          0x1136d2a  google::LogMessage::Fail()
    @          0x1136d2a  google::LogMessage::Fail()
    @          0x1136d2a  google::LogMessage::Fail()
    @          0x1136d2a  google::LogMessage::Fail()
    @          0x1138ae7  google::LogMessage::SendToLog()
    @          0x1138ae7  google::LogMessage::SendToLog()
    @          0x1138ae7  google::LogMessage::SendToLog()
    @          0x1138ae7  google::LogMessage::SendToLog()
F0606 05:15:44.489774 33530 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489804 33528 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489878 33519 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490068 33521 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490216 33525 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490069 33523 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490301 33526 locality_aware_load_balancer.cpp:285] A selection runs too long!
*** Check failure stack trace: ***
F0606 05:15:44.489774 33530 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489804 33528 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489878 33519 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490068 33521 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490216 33525 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490069 33523 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490301 33526 locality_aware_load_balancer.cpp:285] A selection runs too long!
*** Check failure stack trace: ***
    @          0x1136947  google::LogMessage::Flush()
    @          0x1136947  google::LogMessage::Flush()
    @          0x1136947  google::LogMessage::Flush()
    @          0x1136947  google::LogMessage::Flush()
    @          0x1139469  google::LogMessageFatal::~LogMessageFatal()
    @          0x1139469  google::LogMessageFatal::~LogMessageFatal()
    @          0x1139469  google::LogMessageFatal::~LogMessageFatal()
    @          0x1136d2a  google::LogMessage::Fail()
    @          0x1136d2a  google::LogMessage::Fail()
F0606 05:15:44.489774 33530 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489804 33528 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.489878 33519 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490068 33521 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490216 33525 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490069 33523 locality_aware_load_balancer.cpp:285] A selection runs too long!F0606 05:15:44.490301 33526 locality_aware_load_balancer.cpp:285] A selection runs too long!
*** Check failure stack trace: ***
    @          0x1139469  google::LogMessageFatal::~LogMessageFatal()
    @          0x1138ae7  google::LogMessage::SendToLog()
    @          0x1136d2a  google::LogMessage::Fail()
    @           0xfb89cb  brpc::policy::LocalityAwareLoadBalancer::SelectServer()
    @          0x1136d2a  google::LogMessage::Fail()
    @           0xfb89cb  brpc::policy::LocalityAwareLoadBalancer::SelectServer()
    @          0x1138ae7  google::LogMessage::SendToLog()
    @          0x1138ae7  google::LogMessage::SendToLog()
    @           0xfb89cb  brpc::policy::LocalityAwareLoadBalancer::SelectServer()
    @          0x1138ae7  google::LogMessage::SendToLog()
    @          0x1136947  google::LogMessage::Flush()
    @           0xf117b6  brpc::Controller::IssueRPC()
    @           0xf117b6  brpc::Controller::IssueRPC()
    @          0x1139469  google::LogMessageFatal::~LogMessageFatal()
    @          0x1136947  google::LogMessage::Flush()
    @           0xf0ad1d  brpc::Channel::CallMethod()
    @           0xf0ad1d  brpc::Channel::CallMethod()
    @           0xf117b6  brpc::Controller::IssueRPC()
    @          0x1139469  google::LogMessageFatal::~LogMessageFatal()
    @           0xba8625  _ZZN11HttpHandler7PrepareEON8parallel4cpp216ComboHttpRequestEENKUlvE_clEv
    @           0xba8625  _ZZN11HttpHandler7PrepareEON8parallel4cpp216ComboHttpRequestEENKUlvE_clEv
    @          0x1136947  google::LogMessage::Flush()
    @           0xfb89cb  brpc::policy::LocalityAwareLoadBalancer::SelectServer()
    @           0xba8c3c  _ZNSt17_Function_handlerIFN8parallel4cpp212HttpResponseEvESt12_Bind_resultIS2_FZN11HttpHandler7PrepareEONS1_16ComboHttpRequestEEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @           0xf0ad1d  brpc::Channel::CallMethod()
    @          0x1136947  google::LogMessage::Flush()
    @           0xba8c3c  _ZNSt17_Function_handlerIFN8parallel4cpp212HttpResponseEvESt12_Bind_resultIS2_FZN11HttpHandler7PrepareEONS1_16ComboHttpRequestEEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @           0xb9b6a4  _ZN5folly11makeTryWithIZZN3poi16ParallelExecutorIN8parallel4cpp212HttpResponseEE12AsyncExecuteEOSt8functionIFS5_vEEENUlvE_clEvEUlvE_EENSt9enable_ifIXntsrSt7is_sameINSt9result_ofIFT_vEE4typeEvE5valueENS_3TryISJ_EEE4typeEOSG_
    @           0xb9b6a4  _ZN5folly11makeTryWithIZZN3poi16ParallelExecutorIN8parallel4cpp212HttpResponseEE12AsyncExecuteEOSt8functionIFS5_vEEENUlvE_clEvEUlvE_EENSt9enable_ifIXntsrSt7is_sameINSt9result_ofIFT_vEE4typeEvE5valueENS_3TryISJ_EEE4typeEOSG_
    @           0xba8625  _ZZN11HttpHandler7PrepareEON8parallel4cpp216ComboHttpRequestEENKUlvE_clEv
    @           0xfb89cb  brpc::policy::LocalityAwareLoadBalancer::SelectServer()
    @           0xba0f5d  _ZNSt17_Function_handlerIFvvESt12_Bind_resultIvFZN3poi16ParallelExecutorIN8parallel4cpp212HttpResponseEE12AsyncExecuteEOSt8functionIFS6_vEEEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @          0x1139469  google::LogMessageFatal::~LogMessageFatal()
    @           0xb979fc  poi::FunctionWrapper::ThreadFunc()
    @           0xfb89cb  brpc::policy::LocalityAwareLoadBalancer::SelectServer()
    @           0xba0f5d  _ZNSt17_Function_handlerIFvvESt12_Bind_resultIvFZN3poi16ParallelExecutorIN8parallel4cpp212HttpResponseEE12AsyncExecuteEOSt8functionIFS6_vEEEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @           0xba8c3c  _ZNSt17_Function_handlerIFN8parallel4cpp212HttpResponseEvESt12_Bind_resultIS2_FZN11HttpHandler7PrepareEONS1_16ComboHttpRequestEEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @           0xb979fc  poi::FunctionWrapper::ThreadFunc()
    @          0x1139469  google::LogMessageFatal::~LogMessageFatal()
    @           0xb9b6a4  _ZN5folly11makeTryWithIZZN3poi16ParallelExecutorIN8parallel4cpp212HttpResponseEE12AsyncExecuteEOSt8functionIFS5_vEEENUlvE_clEvEUlvE_EENSt9enable_ifIXntsrSt7is_sameINSt9result_ofIFT_vEE4typeEvE5valueENS_3TryISJ_EEE4typeEOSG_
    @           0xf117b6  brpc::Controller::IssueRPC()
    @           0xf117b6  brpc::Controller::IssueRPC()
    @           0xba0f5d  _ZNSt17_Function_handlerIFvvESt12_Bind_resultIvFZN3poi16ParallelExecutorIN8parallel4cpp212HttpResponseEE12AsyncExecuteEOSt8functionIFS6_vEEEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @           0xeff8cd  bthread::TaskGroup::task_runner()
    @           0xb979fc  poi::FunctionWrapper::ThreadFunc()
    @           0xf117b6  brpc::Controller::IssueRPC()
    @           0xeff8cd  bthread::TaskGroup::task_runner()
    @           0xf0ad1d  brpc::Channel::CallMethod()
    @           0xf0ad1d  brpc::Channel::CallMethod()
    @          0x1023091  bthread_make_fcontext

**Comment by jamesge** [comment]
这个可能和流量都倾斜到一台机器上有关

**Comment by lorinlee** [comment]
流量倾斜到一台机器上可能是什么导致的呢

**Comment by beyond-wyc** [comment]
同问！~
