### ISSUE TITLE
错误返回

### ISSUE THREAD

**Issue by yjhjstz** [brpc/brpc#543]
> 如果RPC失败(Controller被SetFailed), Content-Type会框架强制设为text/plain，而response body设为Controller::ErrorText()。

有什么方式可以定制 ErrorText,  比如返回 json .

**Comment by yjhjstz** [comment]
怎么改变成员变量 _error_text 呢？

**Comment by yjhjstz** [comment]
> if (encoding != NULL && *encoding == common->GZIP) {
                TRACEPRINTF("Decompressing request=%lu",
                            (unsigned long)req_body.size());
                butil::IOBuf uncompressed;
                if (!policy::GzipDecompress(req_body, &uncompressed)) {
                    cntl->SetFailed(EREQUEST, "Fail to un-gzip request body");
                    return SendHttpResponse(cntl.release(), server, method_status, msg->received_us());
                }
                req_body.swap(uncompressed);
            }

setfailed 由框架内部设置，该如何定制返回内容呢？

**Comment by jamesge** [comment]
看上面的回复。

**Comment by yjhjstz** [comment]
@jamesge 看了 ，我是说在 brpc::ProcessHttpRequest 函数内部出错，还没到用户自定义的接口函数，就被框架设置set failed， 比如 Fail to un-gzip request body。

**Comment by jamesge** [comment]
这种无法自定义
