### ISSUE TITLE
bthread::Mutex不校验返回值的疑问

### ISSUE THREAD

**Issue by hairet** [brpc/brpc#548]
bthread::Mutex封装了对bthread_mutex_lock系列接口的调用，但是无需处理返回值非0
代码如下:https://github.com/brpc/brpc/blob/master/src/bthread/mutex.h
![image](https://user-images.githubusercontent.com/7167017/47544165-48e1cc00-d918-11e8-8dd5-08284c8aae6a.png)

然而如https://github.com/brpc/brpc/blob/master/src/bthread/mutex.cpp
![image](https://user-images.githubusercontent.com/7167017/47544222-8d6d6780-d918-11e8-8299-382fc48ab109.png)
mutex_lock_contended里的butex_wait，遇到非EWOULDBLOCK且非EINTR的错误，是会直接返回errno的。

具体满足这些条件的case有
https://github.com/brpc/brpc/blob/master/src/bthread/butex.cpp
![image](https://user-images.githubusercontent.com/7167017/47544306-e1784c00-d918-11e8-89be-1e84666263ae.png)
还有WAITER_STATE_TIMEDOUT，当然在我们的bthread_mutex_lock里面是没有TIMEDOUT的，而ESTOP也只有设置了timer才可能出现。

总结来说，会不会有类似ESTOP这种case的errno导致bthread_mutex_lock返回，但是不是取锁成功。从而导致bthread::Mutex::lock没拿到锁也返回了？

**Comment by jamesge** [comment]
严格地来说这里应该抛出std::system_error，目前的实现可以改进。不过实践中不判pthread_mutex_lock的返回值的情况也确实非常多，对这个问题的重视度会低一点

**Comment by hairet** [comment]
> 严格地来说这里应该抛出std::system_error，目前的实现可以改进。不过实践中不判pthread_mutex_lock的返回值的情况也确实非常多，对这个问题的重视度会低一点

嗯，那请问当前如果直接用bthread::Mutex::lock，会不会有坑，比如不是拿到锁的锁主，函数也可能会返回？
