### ISSUE TITLE
brpc/example/http_c++ Failed to make on ubuntu 16.04

### ISSUE THREAD

**Issue by beenchaos** [brpc/brpc#55]
sudo apt-get install git g++ make libssl-dev
sudo apt-get install libgflags-dev libprotobuf-dev libprotoc-dev protobuf-compiler libleveldb-dev
sudo apt-get install libsnappy-dev
sudo apt-get install google-perftools libgoogle-perftools-dev
sh config_brpc.sh --headers=/usr/include --libs=/usr/lib

gcc version 5.3.1

Error:
ubuntu:~/brpc/example/http_c++$ make
../..//config.mk:15: *** "Fail to find gperftools".  Stop.

**Comment by jamesge** [comment]
Something might go wrong with your gperftools installation, check if the headers/libs are actually there, or you can set NEED_GPERFTOOLS to 0 in the Makefile of the example, which turns off tcmalloc linkage.

**Comment by zyfo2** [comment]
I had the same issue and I disabled NEED_GPERFTOOLS to make it work. It seems the getting started tutorial should mention about installing gpertools before the example instead of after it.

**Comment by 564064202** [comment]
I met this bug on centos.
Fail to find gperftools,why?

**Comment by 564064202** [comment]
please resolve this fatal bug ,dear baiduer

**Comment by 564064202** [comment]
@jamesge yes
