### ISSUE TITLE
编译安装使用问题

### ISSUE THREAD

**Issue by jiapengwen** [brpc/brpc#550]
**Describe the bug (描述bug)**
在centos上按照编译步骤，cmake 是有问题的，原因是 yum安装的gflags，protobuf等版本太旧，导致头文件不一致，所以cmake ..  这步是 通过不了的
**To Reproduce (复现方法)**
https://github.com/brpc/brpc/blob/master/docs/cn/getting_started.md 
centos 下，按照步骤
**Expected behavior (期望行为)**
提供源码安装步骤

**Versions (各种版本)**
OS:centos7
Compiler:gcc4.8.2
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by liucong-roadstar** [comment]
@jiapengwen 我使用的是Ubuntu，我发现使用config_brpc.sh编译会报错，但是如果使用cmake编译是没问题的。不知道能否解决你的问题

**Comment by mengrenfeixiang** [comment]
**执行make时，报如下错误。**
<命令行>:0:11: 错误：‘gflags’未声明
src/butil/logging.cc:1387:50: 附注：in expansion of macro ‘GFLAGS_NS’
 const bool ALLOW_UNUSED validate_vmodule_dummy = GFLAGS_NS::RegisterFlagValidator(
                                                  ^
<命令行>:0:11: 错误：‘gflags’未声明
src/butil/logging.cc:1417:44: 附注：in expansion of macro ‘GFLAGS_NS’
 const bool ALLOW_UNUSED validate_v_dummy = GFLAGS_NS::RegisterFlagValidator(
                                            ^
<命令行>:0:11: 错误：‘gflags’未声明
src/butil/logging.cc:1425:5: 附注：in expansion of macro ‘GFLAGS_NS’
     GFLAGS_NS::RegisterFlagValidator(&FLAGS_crash_on_fatal_log, PassValidate);
     ^
<命令行>:0:11: 错误：‘gflags’未声明
src/butil/logging.cc:1428:5: 附注：in expansion of macro ‘GFLAGS_NS’
     GFLAGS_NS::RegisterFlagValidator(&FLAGS_print_stack_on_check, PassValidate);
     ^
<命令行>:0:11: 错误：‘gflags’未声明
src/butil/logging.cc:1434:50: 附注：in expansion of macro ‘GFLAGS_NS’
 const bool ALLOW_UNUSED validate_min_log_level = GFLAGS_NS::RegisterFlagValidator(
                                                  ^
make: *** [src/butil/logging.o] 错误 1

**Comment by hexiecs** [comment]
> **执行make时，报如下错误。**
> <命令行>:0:11: 错误：‘gflags’未声明
> src/butil/logging.cc:1387:50: 附注：in expansion of macro ‘GFLAGS_NS’
> const bool ALLOW_UNUSED validate_vmodule_dummy = GFLAGS_NS::RegisterFlagValidator(
> ^
> <命令行>:0:11: 错误：‘gflags’未声明
> src/butil/logging.cc:1417:44: 附注：in expansion of macro ‘GFLAGS_NS’
> const bool ALLOW_UNUSED validate_v_dummy = GFLAGS_NS::RegisterFlagValidator(
> ^
> <命令行>:0:11: 错误：‘gflags’未声明
> src/butil/logging.cc:1425:5: 附注：in expansion of macro ‘GFLAGS_NS’
> GFLAGS_NS::RegisterFlagValidator(&FLAGS_crash_on_fatal_log, PassValidate);
> ^
> <命令行>:0:11: 错误：‘gflags’未声明
> src/butil/logging.cc:1428:5: 附注：in expansion of macro ‘GFLAGS_NS’
> GFLAGS_NS::RegisterFlagValidator(&FLAGS_print_stack_on_check, PassValidate);
> ^
> <命令行>:0:11: 错误：‘gflags’未声明
> src/butil/logging.cc:1434:50: 附注：in expansion of macro ‘GFLAGS_NS’
> const bool ALLOW_UNUSED validate_min_log_level = GFLAGS_NS::RegisterFlagValidator(
> ^
> make: *** [src/butil/logging.o] 错误 1

请问这个问题有解决吗? 我使用config_brpc.sh编译也遇到了同样的问题

**Comment by jiapengwen** [comment]
建议你看下 gflag 怎么使用的

**Comment by hexiecs** [comment]
> 建议你看下 gflag 怎么使用的

这是个编译问题，跟使用有关吗?你最后是怎么解决的?

**Comment by jiapengwen** [comment]
我后来是安装新版本的依赖解决的
