### ISSUE TITLE
有计划开源 Go 客户端吗？

### ISSUE THREAD

**Issue by choleraehyq** [brpc/brpc#554]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
Go 官方客户端
**Describe the solution you'd like (描述你期望的解决方法)**
开源 baidu_std 协议的单连接方式官方客户端
**Describe alternatives you've considered (描述你想到的折衷方案)**
用 grpc 客户端，也是单连接，但是 grpc 的 http2 协议在 tcp 上又做了很多封装，性能不如 baidu_std
**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
grpc-go的性能还可以，你主要是用在什么场景中？
