### ISSUE TITLE
thrift协议_run_counter计数判断导致错误资源泄露

### ISSUE THREAD

**Issue by hairet** [brpc/brpc#555]
**Describe the bug (描述bug)**
thrift协议_run_counter计数判断导致错误资源泄露，可能还不止资源泄露，因为done里面还涉及回包等各种操作
**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**
代码如下
![image](https://user-images.githubusercontent.com/7167017/47694656-835da880-dc39-11e8-9673-1059feb1f987.png)
src/brpc/policy/thrift_protocol.cpp里面，ThriftClosure对象是在ThriftClosure::DoRun里面通过std::unique_ptr<ThriftClosure> recycle_ctx(this);释放的，但是_run_counter被初始化为0，_run_counter.fetch_add返回1是不对的，应该是返回0？

**Comment by jamesge** [comment]
已修复，感谢报告
