### ISSUE TITLE
brpc client 可以编译成一个静态库，供其他程序使用吗？

### ISSUE THREAD

**Issue by sunwsh** [brpc/brpc#556]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
我们一个已有项目想用brpc，需要封装成一个静态库，给外部用。

**Describe the solution you'd like (描述你期望的解决方法)**
希望提供一个模版，可以直接编译成静态库或动态库的方法。

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
本身编译结果中不是就有libbrpc.a么？
