### ISSUE TITLE
还是thrift协议，cntl Failed之后处理疑似有问题

### ISSUE THREAD

**Issue by hairet** [brpc/brpc#557]
**Describe the bug (描述bug)**

跟https://github.com/brpc/brpc/issues/555
这次有一定关系，就是最新fix的代码加了SuspendRunning和ResumeRunning，正常到ProcessThriftFramedRequestNoExcept里的处理逻辑没问题。但是在ProcessThriftRequest里面
![image](https://user-images.githubusercontent.com/7167017/47716393-867a8800-dc7d-11e8-9dd5-cb0789b049f9.png)
https://github.com/brpc/brpc/blob/master/src/brpc/policy/thrift_protocol.cpp
当cntl failed，比如命中ELIMIT，此时还会正常执行thrift server的业务逻辑，然后才给client回包。而像baidu_rpc_protocol.cpp里面，遇到cntl failed会break出去，不执行server的业务逻辑，直接回包。
**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
个人理解thrift_protocol.cpp更合理的写法应该是
do {
        if (!server->IsRunning()) {
            cntl->SetFailed(ELOGOFF, "Server is stopping");
            break;
        }
        //各种cntl failed
    } while (false);
// add this
    if (cntl->Failed()) {
        return thrift_done->Run();
    }

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
这里有两种理解，一种是错误要递给用户回调(ProcessThriftFramedRequest)处理，以允许定制化错误的传回方式；另一种是协议本身规定了传递错误的方式，就无需访问到用户回调了。thrift应该两者皆可，我倾向于后者。这里这么写的原因大概是因为代码修改自nshead_service，这个协议是一定要传递给回调的。你可以考虑提一个pr。

**Comment by hairet** [comment]
> 这里有两种理解，一种是错误要递给用户回调(ProcessThriftFramedRequest)处理，以允许定制化错误的传回方式；另一种是协议本身规定了传递错误的方式，就无需访问到用户回调了。thrift应该两者皆可，我倾向于后者。这里这么写的原因大概是因为代码修改自nshead_service，这个协议是一定要传递给回调的。你可以考虑提一个pr。

大概理解，不过这里的错误，我认为不太需要给用户回调处理加定制化了，都是框架级别的标准错误

**Comment by hairet** [comment]
> 已调整为错误不递给回调

好的，我提交了一个关于号码串行化处理的相关代码pr，不影响原来brpc代码.请戈兄帮看看，https://github.com/brpc/brpc/pull/570，有啥问题也请帮指出。串行化的需求，一些对顺序有要求的业务有需要。
