### ISSUE TITLE
redis client能够在多线程同时使用吗？

### ISSUE THREAD

**Issue by njdragonfly** [brpc/brpc#56]
如果能同时使用，多个线程发出的redis request怎么和返回的response一一对应？

**Comment by jamesge** [comment]
可以，并且一个进程内只使用一个连接。redis的response是按返回顺序和request发出顺序一一对应的。如果一个线程一次请求中包含了多个command，response中也会有相同个数个reply。文档里都有说明。

**Comment by njdragonfly** [comment]
redis protocol 里没有correlation_id，如果两个线程在同一个连接上各自发出一个request，当response返回时，怎么和request对应起来？

**Comment by jamesge** [comment]
“response是按返回顺序和request发出顺序一一对应”

**Comment by njdragonfly** [comment]
看代码看到 Socket对象里有个_pipeline_q队列，利用队列的顺序特性，可以把request的cid和response的cid对应起来。
不知道我理解的对不对？

**Comment by njdragonfly** [comment]
ParseRedisMessage函数里， socket->PopPipelinedInfo(&pi)； 和 socket->GivebackPipelinedInfo(pi); 两个调用之间可能有其他线程操作了队列，这样会导致队列的顺序错误。不知道这里是否有问题？

**Comment by jamesge** [comment]
对，同时这个队列也记录了request中包含了几个command，response会等收到对应个数的reply后才从_pipeline_q中弹掉对应的元素。你贴的那两个函数没有问题，因为[Socket.StartInputEvent](https://github.com/brpc/brpc/blob/master/src/brpc/socket.cpp#L1831)保证一个socket同时最多被一个线程读。

**Comment by njdragonfly** [comment]
理解了，多谢答复。
