### ISSUE TITLE
config_brpc.sh配置多个搜索路径时出错

### ISSUE THREAD

**Issue by handsberg** [brpc/brpc#569]
**Describe the bug (描述bug)**
config_brpc.sh配置多个headers、libs搜索路径时出错

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: GNU/Linux 2.6.32
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

$sh config_brpc.sh --headers="../../build/include /usr/include" --libs="../../build/lib /usr/lib64 ../../build/bin"
readlink: extra operand `/usr/include'
Try `readlink --help' for more information.
readlink: extra operand `/usr/lib64'
Try `readlink --help' for more information.
config_brpc: --headers=HDRPATHS --libs=LIBPATHS must be specified

**Comment by songlong** [comment]
真是个大问题
