### ISSUE TITLE
pthread_mutex_unlock symbol conflict

### ISSUE THREAD

**Issue by fr0zenrain** [brpc/brpc#57]
conflict with  pthread,why use same function name

**Comment by jamesge** [comment]
for implementing contention profiler.

**Comment by fr0zenrain** [comment]
have example? if not change name is well.thanks.

**Comment by fr0zenrain** [comment]
and contention profiler may be the advance use,please  implemented contention profiler in example,  so  changed?

**Comment by jamesge** [comment]
要不你讲中文吧。。。你这英文我看不懂

**Comment by fr0zenrain** [comment]
contention profiler 是高级用法吧，example里没有，那为啥不改名，改名字也不会影响其他功能。

**Comment by fr0zenrain** [comment]
另外还有一个问题，tcmalloc_extension.cpp引用dlsym导致无法静态编译，要不要解决一下？

**Comment by jamesge** [comment]
我这里都没有问题。你可以贴下具体的错误以及环境。
