### ISSUE TITLE
brpc 使用redis client 访问redis，长时间超时 无法恢复

### ISSUE THREAD

**Issue by gtarcoder** [brpc/brpc#572]
**Describe the bug (描述bug)**
brpc 使用  [Redis client](https://github.com/brpc/brpc/blob/95285fe7e4a183c70924975fbb4f47f6d6d0a50d/docs/cn/redis_client.md) 访问 redis 集群 （通过 list的naming），一段时间后出现 连续 timeout，且长时间不能恢复，甚至出现 "can not select server from xxx" 报错。

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
redis 超时后，能够快速重连恢复，而不是一直timeout，甚至 can not select server from xxx

**Versions (各种版本)**
OS: ubuntu16.04
Compiler: gcc 5.4
brpc:  master 
protobuf: 3.5

**Additional context/screenshots (更多上下文/截图)**
我们查 了网络，在出现 连续 timeout的时间段，网络并没有很差，且redis 的log显示redis 并没有慢查询。出现timeout，可以理解，但是 一旦timeout之后，长时间不能恢复，这个不应该。怀疑是BRPC 内部 的重连机制有问题

**Comment by gtarcoder** [comment]
还有个疑问：

**Comment by gtarcoder** [comment]
上面的额问题
还有一个问题，
void LocalityAwareLoadBalancer::Describe(
    std::ostream& os, const DescribeOptions& options) {
    if (!options.verbose) {
        os << "la";
        return;
    }
    os << "LocalityAware{total="
       << _total.load(butil::memory_order_relaxed) << ' ';
    butil::DoublyBufferedData<Servers>::ScopedPtr s;
    if (_db_servers.Read(&s) != 0) {
        os << "fail to read _db_servers";
    } else {
        const int64_t now = butil::gettimeofday_us();
        const size_t n = s->weight_tree.size();
        os << '[';
        for (size_t i = 0; i < n; ++i) {
            const ServerInfo & info = s->weight_tree[i];
            os << "\n{id=" << info.server_id;
            {
                SocketUniquePtr tmp_ptr;
                if (Socket::Address(info.server_id, &tmp_ptr) != 0) {
                    os << "(broken)";
                }
            }
            os << " left="
               << info.left->load(butil::memory_order_relaxed) << ' ';
            info.weight->Describe(os, now);
            os << '}';
        }
        os << ']';
    }
    os << '}';
}

这里有时候会出现 某个节点 broken， 因为无法通过serverId (即 socketId) 去定位到 , 

> 还有个疑问：
> [LocalityAwareLoadBalancer](https://github.com/brpc/brpc/blob/master/src/brpc/policy/locality_aware_load_balancer.cpp) 中，
> 
> ```
>     } else if (Socket::Address(info.server_id, out->ptr) == 0
>                && !(*out->ptr)->IsLogOff()) {
>         if ((ntry + 1) == n  // Instead of fail with EHOSTDOWN, we prefer
>                              // choosing the server again.
>             || !ExcludedServers::IsExcluded(in.excluded, info.server_id)) {
>             if (!in.changable_weights) {
>                 return 0;
>             }
>             const Weight::AddInflightResult r =
>                 info.weight->AddInflight(in, index, dice - left);
>             if (r.weight_diff) {
>                 s->UpdateParentWeights(r.weight_diff, index);
>                 _total.fetch_add(r.weight_diff, butil::memory_order_relaxed);
>             }
>             if (r.chosen) {
>                 out->need_feedback = true;
>                 return 0;
>             }
>         }
>         if (++ntry >= n) {
>             break;
>         }
> ```
> Socket::Address(info.server_id, out->ptr) 这行
> 通过 serverId（socketId） 去获取 背后的socket 对象。 serverId / socketId 是在 naming service thread 的AddServer的时候就确定好的（通过 GlobalSocketCreator->CreateSocket()）。
> 
> 如果我的naming service url 为 list:// Server11,Server2,Server3, 那么就会在naming service thread中，创建三个 底层的socket，并分配socketId（也就是 serverId）， Socket1, Socket2, Socket3。
> 
> 每次我通过 LALB 算法，选择出来一个 remote server (比如 Server1)之后，去获取 socket 总是得相同的（Server1 就对应为 Socket1）。
> 
> 而我理解，BRPC的client 对于同一个 remote server （ip:port），可以有多个socket 与之相连。那么这种 LALB 方法，对于同一个remote server，总是选择固定的一个本地socket。
> 
> 是我的理解有问题么？ @jamesge


哦我理解了，是 在 naming service thread中创建的 和 server 一一对应的 socket 为 main socket，但LALB 选择出来 （固定的几个）main socket之后，会通过 socket pool 再去轻量级的创建  pooled socket，然后通过 pooled socket 去进行读写操作。

话说这样做的好处是什么呢？以及如果 由main socket 创建出来的**所有** pooled socket 失败了的话，main socket会怎么样？

**Comment by troycheng** [comment]
请问一下，这个问题解决了吗，如果解决了是如何解决的呢？
