### ISSUE TITLE
bazel编译，使用glog问题

### ISSUE THREAD

**Issue by superlong** [brpc/brpc#577]
背景：
使用<butil/logging.h>发现不能像glog一样可以设置不同级别的LOG打印到对应的文件，而且没有控制日志大小的配置？（如果有烦请指出如何使用）
问题：
使用glog，bazel编译通过(不修改brpc/BUILD)，执行时出错：
ERROR: flag 'v' was defined more than once (in files 'external/com_github_google_glog/src/vlog_is_on.cc' and 'external/com_github_brpc_brpc/src/butil/logging.cc').

修改brpc/BUILD，将with_glog所有行都删除，重新编译，执行后问题依然存在。
请问是什么问题？
谢谢！

**Comment by fengliangwang** [comment]
请问此问题是如何修复解决的？

**Comment by veyrony** [comment]
> 请问此问题是如何修复解决的？
不用改代码，编译时加上 --define=with_glog=true
$ bazel build --define=with_glog=true  ...

**Comment by fengliangwang** [comment]
> > 请问此问题是如何修复解决的？
> > 不用改代码，编译时加上 --define=with_glog=true
> > $ bazel build --define=with_glog=true  ...

好的，看到了，谢谢

**Comment by pursuemoon** [comment]
感谢，这是什么原理呢？
