### ISSUE TITLE
What should I do if I need shared mutex?

### ISSUE THREAD

**Issue by YaroslavErsteniuk** [brpc/brpc#579]
Hello!
For an aplication, which use brpc and bthread, there is need for using something like shared mutex ( e. g. std::shared_mutex).
I've tried to find in this project, but coudn't.
Is there a class for this? Or I should use posix shared mutex? Or I can use std::shared_mutex and it will work fine with bthread?
Anybody, please, help!

**Comment by YaroslavErsteniuk** [comment]
Thank a lot for a explanation!
One more questuon: is there an easy way to change bthreads, used in brpc/braft to std::threads or posix threads? Because project use smth like that before we decide use braft(which depend on brpc), and we dont use shared ptr before.

**Comment by jamesge** [comment]
You can use shared_mutex in bthreads as well, although the code blocks underlying pthreads. bthread is designed to be compatible with legacy code(that runs in pthreads) with one exception: thread-locals

**Comment by YaroslavErsteniuk** [comment]
Once more thanks for a reply and good explanation!
