### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by pengdao** [brpc/brpc#58]
编译时出现错误：
In file included from ./src/butil/basictypes.h:18:0,
                 from ./src/butil/files/file.h:20,
                 from src/butil/files/file_posix.cc:5:
src/butil/files/file_posix.cc: In member function ‘int64_t butil::File::Seek(butil::File::Whence, int64_t)’:
./src/butil/macros.h:173:34: error: static assertion failed: off_t_64_bit
 #define BAIDU_CASSERT(expr, msg) static_assert(expr, #msg)
                                  ^
./src/butil/macros.h:218:36: note: in expansion of macro ‘BAIDU_CASSERT’
 #define COMPILE_ASSERT(expr, msg)  BAIDU_CASSERT(expr, msg)
                                    ^
src/butil/files/file_posix.cc:286:3: note: in expansion of macro ‘COMPILE_ASSERT’
   COMPILE_ASSERT(sizeof(int64_t) == sizeof(off_t), off_t_64_bit);
   ^
make: *** [src/butil/files/file_posix.o] 错误 1

**Comment by jamesge** [comment]
什么环境和编译器

**Comment by stevenwake** [comment]
我也碰到了这个问题，g++版本4.8.4，ubuntu14.04 32位

**Comment by jamesge** [comment]
不支持32位系统。
