### ISSUE TITLE
上线brpc之后，集群同一个时刻访问下游服务出现集体超时现象

### ISSUE THREAD

**Issue by scottzzq** [brpc/brpc#582]
**Describe the bug (描述bug)**

上线brpc之后，集群偶尔会出现（一天出现）同一个时刻访问下游服务出现集体超时现象，同一时刻网卡出入流量掉一个大坑，整个过程1分钟之内可以自动恢复，同时也发现访问下游服务rpc调用耗时远远超出设置的timeout，甚至出现访问某些下游出现20s的现象，整个过程cpu远远没有达到瓶颈，排查过业务代码，业务代码只有一个地方用到锁，同时也没有除了rpc其他外部服务的流程。问下造成这种想象的原因可能是啥？谢谢

**To Reproduce (复现方法)**
暂时找不到很好的复现方法!

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:centos7.4
Compiler:gcc5.2
brpc:release1.0
protobuf:2.5

**Additional context/screenshots (更多上下文/截图)**

**Comment by dyike** [comment]
https://github.com/brpc/brpc/blob/master/docs/cn/server.md

**Comment by scottzzq** [comment]
@dyike 我们用的bthread模式，可以排除业务层死锁、访问外部服务导致的io阻塞，唯一的可能就是打日志可能阻塞一下bthread worker,实际上我们的glog开了buf缓存的，这个我理解阻塞时间非常短，不会造成大量超时。

**Comment by scottzzq** [comment]
@dyike 我们监控到的cpu利用率也比较低

**Comment by scottzzq** [comment]
出问题的那一分钟，打印的Checking SocketId1分钟之内有1600条，我们使用的la负载均衡算法

**Comment by dyike** [comment]
https://github.com/brpc/brpc/blob/master/docs/cn/bthread.md

**Comment by jamesge** [comment]
@scottzzq 能使用下rr看看还有这个问题么

**Comment by scottzzq** [comment]
@jamesge 问了下我们兄弟团队的同学，他们有用不同的负载均衡算法，每种都有遇到过超时控制远远超出设定的timeout值，目前比较确定的是我们业务代码不太可能出现长达20s的阻塞操作。

**Comment by jamesge** [comment]
想到的一些问题：
* 使用的什么协议？
* 使用rr负载均衡出问题时也会Checking SocketId这种日志么？这个日志一般说明下游挂了
* 能确认是上游（包含client的服务）卡了还是下游卡了？
* channel还有其他特殊设置么？
* 能看到出问题时的bvar数据么？这个需要监控系统定期搜集bvar数据。

**Comment by scottzzq** [comment]
@jamesge  我们最近在brpc代码中插入了一些耗时监控代码，发现rpc的序列化、反序列化最长耗时可能到110s，所以超时控制不准确和这个有关，但是目前还不清楚根源是什么，序列化、反序列化使用了lz4压缩算法。

**Comment by scottzzq** [comment]
@jamesge 是的

**Comment by scottzzq** [comment]
@jamesge 通过查看机器秒级监控，发现当时cpu被打满了，所以导致序列化、反序列化耗时异常，进而导致超时，不确定是不是和brpc内部的spin lock有关，之前我们有遇到过tcmalloc中的spin lock导致cpu打满的问题。

**Comment by jamesge** [comment]
只有bthread在一个自增version处用了spinlock，其他地方都没用。看起来也和pb序列化没什么关系。可以尝试写一个脚本在cpu占用率很高时perf record，然后看看到底是什么函数。

**Comment by scottzzq** [comment]
将pthread worker从48->16 rpc各项指标的max值均得到大大改善，比如之前反序列化pb的max值100s，调整完之后max值1s，调整前后机器流量不变，cpu利用率基本维持在20%以下，之前使用sofa-pbrpc的时候max值没有1s的情况。

**Comment by scottzzq** [comment]
@jamesge 在线上部署过脚本，没有抓到有用的信息，抓到的栈没有异常，可能和持续时间非常短有关系。

**Comment by jamesge** [comment]
目前的表现很难用pthread worker从48调整到16来解释。链接tcmalloc或jemalloc了么

**Comment by scottzzq** [comment]
@jamesge  我们有链接jemalloc

**Comment by jamesge** [comment]
有条件的话可以在48个线程的情况下不链接或链tcmalloc看看

**Comment by xiangpdu** [comment]
请问这个问题后续怎么样了， 遇到相同的问题，请教一下最后是怎么解决的？
