### ISSUE TITLE
链接jemalloc后在bthread中启动的pthread在结束时crash

### ISSUE THREAD

**Issue by niukuo** [brpc/brpc#588]
**Describe the bug (描述bug)**

**To Reproduce (复现方法)**
1. brpc server端
2. 链接了 jemalloc
2. usercode_in_pthread=false
3. 在 rpc method 代码中使用std::thread启动了新的线程并detach
4. 新启动的线程中会同步调用其它rpc服务。
5. 线程在结束时crash，stack在jemalloc清理tcache(应该和thread local storage有关)时一个pthread_unlock。
6. 设置usercode_in_pthread=true后到目前没有发现进程挂掉的情况

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: centos 5u7
Compiler: gcc-4.9.2
brpc: 
protobuf: 2.4.1

**Additional context/screenshots (更多上下文/截图)**
coredump和stack暂时没有 如果需要可以复现一下。
在bthread文档中大概找了一下，猜测可能与stacktype有关。能否提供一些调查方向？

**Comment by niukuo** [comment]
以及，在bthread中启动pthread的正确姿势应该是怎样的。。。

**Comment by jamesge** [comment]
crash时server在退出进程么？
新启动的线程如果不做rpc，还会crash么？
新启动的线程可能引用失效的对象么？包括那个pthread_unlock的mutex

**Comment by niukuo** [comment]
1. crash时只有那个线程在退出，进程没有退出，正常提供服务。
3. 那个mutex是jemalloc内部的，暂时没有研究。
后面修改了一些工作流程，暂时无法重现了。怀疑是我这边的用户代码有内存问题，暂时先关闭。

**Comment by niukuo** [comment]
(gdb) bt
#0  je_arena_run_regind (ptr=<optimized out>, bin_info=0x24b93c0, run=<optimized out>) at include/jemalloc/internal/arena.h:1170
#1  arena_run_reg_dalloc (ptr=<optimized out>, run=<optimized out>) at src/arena.c:309
#2  arena_dalloc_bin_locked_impl (tsdn=0x7fe8c5f61120, arena=0x7fe9b1ad1d80, chunk=0x7fe847e00000, ptr=0x7fe847e3cf00, bitselm=<optimized out>, junked=<optimized out>) at src/arena.c:2963
#3  0x000000000087fc0d in je_tcache_bin_flush_small (tsd=0x7fe8c5f61120, tcache=0x7fe9aa27d000, tbin=0x7fe9aa27d1a8, binind=<optimized out>, rem=16) at src/tcache.c:137
#4  0x00000000008462e2 in je_tcache_dalloc_small (slow_path=<optimized out>, binind=<optimized out>, ptr=<optimized out>, tcache=<optimized out>, tsd=<optimized out>) at include/jemalloc/internal/tcache.h:419
#5  je_arena_dalloc (slow_path=<optimized out>, tcache=<optimized out>, ptr=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/arena.h:1441
#6  je_idalloctm (slow_path=<optimized out>, is_metadata=<optimized out>, tcache=<optimized out>, ptr=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:1170
#7  je_iqalloc (slow_path=<optimized out>, tcache=<optimized out>, ptr=<optimized out>, tsd=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:1187
#8  ifree (tsd=0x7fe8c5f61120, ptr=0x7fe846f1b000, tcache=0x7fe9aa27d000, slow_path=<optimized out>) at src/jemalloc.c:1896

4.5版本依然会coredump

**Comment by niukuo** [comment]
原因找到了，是因为对栈上的对象执行了delete操作。
猜测是因为jemalloc将部分申请、释放内存的动作暂存在了thread cache中，线程退出时才归还到全局内存池中，触发crash。

**Comment by jamesge** [comment]
这类问题可以看看跑asan是否能报出来。

**Comment by niukuo** [comment]
> 这类问题可以看看跑asan是否能报出来。

恩 这个是在链接了tcmalloc之后发现的 tcmalloc在删除栈上的对象时候会立即crash
