### ISSUE TITLE
新增私有协议，进程运行core掉

### ISSUE THREAD

**Issue by cxxcunow** [brpc/brpc#589]
[libprotobuf ERROR google/protobuf/descriptor_database.cc:318] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'

**Comment by jamesge** [comment]
信息量太少了，并不知道你是怎么加的，加协议本身也有一定的复杂度。
