### ISSUE TITLE
Does brpc support bidirectional comms for callback

### ISSUE THREAD

**Issue by thincal** [brpc/brpc#59]

**Comment by jamesge** [comment]
Read this: https://github.com/brpc/brpc/blob/master/docs/cn/server_push.md

**Comment by thincal** [comment]
thanks for your information, but is there any example about this "server push" ?

**Comment by jamesge** [comment]
no. there's no utilities or abstractions on "server push" inside brpc now, users should implement the feature according to scenarios. Reopen this issue if you have further requests.
