### ISSUE TITLE
查看锁冲突报告时提示Fail to execute

### ISSUE THREAD

**Issue by niukuo** [brpc/brpc#591]
**Describe the bug (描述bug)**
Fail to execute `perl ./rpc_data/profiling/pprof.pl --dot ./my_app ./rpc_data/profiling/81e3de43631c328971a1b32153b748bb/20181211.161855.contention 2>&1 ', No child processes

run_command_through_clone为true和false时都可以在进程列表中看见 sh -c perl xxx 及其子进程

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: 编译 centos 5.7 静态链接 运行 centos 7.2
Compiler: gcc 4.9.2
brpc: 1c73d2a384d7ca4ed7aa00ea341cba55633e03a0
protobuf: 2.4.1

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/6831097/49787705-5802c900-fd62-11e8-90a5-a23b026b8aa6.png)

不知道是否有人遇到过类似的问题？看代码中似乎所有错误都会设置errno为ECHILD，很奇怪

**Comment by jamesge** [comment]
run_command_through_clone设置为false（默认值）时也是挂掉的么？errno是什么

**Comment by niukuo** [comment]
> run_command_through_clone设置为false（默认值）时也是挂掉的么？errno是什么

设置成true和false会有sh -c的进程，都会提示Fail to execute

**Comment by niukuo** [comment]
错误信息也是一样的 no child processes

**Comment by niukuo** [comment]
调用 signal(SIGCHLD, SIG_DFL);后恢复正常。
应该是我这边有模块调用了SIGCHLD, SIG_IGN，继续调查中。此问题与brpc无关，关闭。
