### ISSUE TITLE
src/butil/stl_util.h的全局函数可能与其它库的函数冲突

### ISSUE THREAD

**Issue by ufosky** [brpc/brpc#595]
**Describe the bug (描述bug)**
这个文件是从chromium的项目里面弄过来的，其它库也有这样搞的，结果两个库同时使用就会导致重复定义，现在chromium的实现加了命名空间，brpc里面是不是也加个命名空间，防止和其它库冲突

**Comment by jamesge** [comment]
默认是加了butil，这个似乎漏了，还有其他类似的问题么

**Comment by jamesge** [comment]
added, please help to check the compilation again.
