### ISSUE TITLE
发起rpc调用偶尔101错误

### ISSUE THREAD

**Issue by dengzhanqiao** [brpc/brpc#596]
我们框架是在proxy端使用brpc,链接多个logic，logic层使用brpc链接单个DAO层。
proxy端的client有多个，链接不同类型的logic。单个logic的list ip由1~n个。
现在偶尔在proxy调用logic时会报错：
E1214 15:52:08.763095  2005  2016 BrpcHandler.cpp:46] BrpcHandler::Run error test cntl.ErrorText():[E112]Fail to select server from list://192.168.8.6:9900 lb=c_hash [R1][E112]Fail to select server from list://192.168.8.6:9900 lb=c_hash [R2][E112]Fail to select server from list://192.168.8.6:9900 lb=c_hash [R3][E112]Fail to select server from list://192.168.8.6:9900 lb=c_hash
E1214 15:52:08.763164  2005  2016 BrpcHandler.cpp:169] BrpcHandler::onFailed ret:101 protocol_type:1009 uid:1000113 clientId:45957 seq:52 controller->remote_side():0.0.0.0:0 controller->local_side():0.0.0.0:0 controller->log_id():1544773928762
想问问这个大概时什么原因导致的。之前策略时RR，现在是hash。都有这种偶尔的错误。此时logic也不存在coredump之类的

**Comment by dengzhanqiao** [comment]
通讯方式是同步

**Comment by jl2005** [comment]
@dengzhanqiao  这个问题解决了吗？我也遇到同样的问题。
