### ISSUE TITLE
python requests通过http访问brpc接口CPU使用率高

### ISSUE THREAD

**Issue by lgbo-dev** [brpc/brpc#597]
**Describe the bug (描述bug)**

使用http+ json的方式访问brpc接口，出现CPU使用过高的问题。
**To Reproduce (复现方法)**
使用以下代码访问brpc接口，发现但线程CPU使用率到80%以上。不知是否正常。
如果换成其他网址访问，发现cpu使用并不高。

 for i in range(0, 10000):
    ret = requests.post(url, data=json.dumps(req), headers=header)
    print ret.headers
    print ret.text

**Comment by jamesge** [comment]
这里的cpu使用高是指被访问的server进程占用的cpu高么？还是这个py client的cpu高？有多高
