### ISSUE TITLE
example Linking Error: undefined reference to 'butil::demangle(char const*)'

### ISSUE THREAD

**Issue by sduzh** [brpc/brpc#6]
libbrpc.so编译成功，cd example/echo_c++; make链接错误：

![linkingerror](https://user-images.githubusercontent.com/4351040/30481745-d0fc9bf2-9a52-11e7-867e-437d9752aac5.JPG)
使用nm查看好像生成了C++11的ABI：
![nm](https://user-images.githubusercontent.com/4351040/30481797-ff95f94a-9a52-11e7-8568-75f597ceab91.JPG)

编译环境如下：
ubuntu 16.04 x86_64
gcc 5.4.0

**Comment by chenzhangyi** [comment]
目前没有这样的编译环境:(.. 方便的话在 src/butil/class_name.cpp  里面加上. #include <butil/class_name.h> (这样这个编译单端能看到函数声明)。 并尝试再次编译.

**Comment by sduzh** [comment]
解决了，原因是因为在模板函数class_name_str()内部声明了std::string demangle(const char*)这个函数，这个好像是gcc 5的bug：在模板内部声明的std::string不会有[abi:cxx11] tag，[这里](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69621)有个相似问题描述。
解决方法就是删除class_name_str()内部的demangle()函数声明
