### ISSUE TITLE
hulupbrpcprotocol.cpp bug

### ISSUE THREAD

**Issue by cxxcunow** [brpc/brpc#602]
您好：
在ProcessHuluRequest中，
    SocketUniquePtr socket_guard(msg->ReleaseSocket());
    Socket* socket = socket_guard.get();
。。。。
    accessor.set_server(server)
        .set_security_mode(security_mode)
        .set_peer_id(socket->id())
        .set_remote_side(socket->remote_side())
        .set_local_side(socket->local_side())
        .set_auth_context(socket->auth_context())
        .set_request_protocol(PROTOCOL_HULU_PBRPC)
        .set_begin_time_us(msg->received_us())
        .move_in_server_receiving_sock(socket_guard);

这里会将socket的内存给了accessor中的controller来管理，
但是我遇到了一个问题，就是在 ProcessHuluResponse 中，再次来取 
    ControllerPrivateAccessor accessor(cntl);
    Span* span = accessor.span();
    if (span) {
        span->set_start_send_us(butil::cpuwide_time_us());
    }
    Socket* sock = accessor.get_sending_socket()

这个sock是空的， 请问这个问题如何解决？ 谢谢。

**Comment by jamesge** [comment]
建议跑一下asan。

**Comment by cxxcunow** [comment]
>           建议跑一下asan。
我部署的环境是： 本端---->brpc server1 ---->brpc client2--->远端. 在server1 处发现了这个问题，加了log发现server1在调用回调函数之前，sock已经被释放，释放的路径是Controller::EndRPC ----Controller::Call::OnComplete 这里会reset掉。
