### ISSUE TITLE
建连过程设置qos

### ISSUE THREAD

**Issue by athree** [brpc/brpc#603]
麻烦问下，brpc是否支持qos功能？包括建连过程中的三次握手(client->server和server->client)设置qos？
谢谢！

**Comment by athree** [comment]
https://github.com/brpc/brpc/blob/master/src/brpc/socket.cpp#562，你好可能我没表述清楚，你说的这个接口我类似找到了这个实现，对于三次握手的server端来说，设置了socket的选项后，就污染了所有从这个端口接入的链接，局限性太大！

**Comment by jamesge** [comment]
没有
