### ISSUE TITLE
brpc 添加不同的服务，如何保证服务的优先级别？

### ISSUE THREAD

**Issue by xuxiping** [brpc/brpc#606]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
brpc在AddService 添加服务的时候，如何保证某个服务的优先，因为多个service都是共享一个线程池，当业务压力大时无法保证最基本的服务正常运行。比如 添加一个braft服务时优先保证raft服务的稳定性？

**Describe the solution you'd like (描述你期望的解决方法)**
添加服务的时候有优先级处理

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
不能保证。此种情况下应扩容或解决代码问题。
