### ISSUE TITLE
单向调用的问题

### ISSUE THREAD

**Issue by BillyJoy** [brpc/brpc#611]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
有的时候，只是单纯的想发一个东西到server端，但是server端并不需要回复数据给调用端

**Describe the solution you'd like (描述你期望的解决方法)**
不等待被调方回复

**Describe alternatives you've considered (描述你想到的折衷方案)**
折中的方案是一发一回 ？（无法手动滑稽）

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
必须得处理回复。一个折衷是把response设置为NULL（不会解析了），并递一个done，其中删除了对应的Controller（和done自己）。

**Comment by Lowpower** [comment]
我这样试了一下貌似不行
