### ISSUE TITLE
关于服务端异步回调问题

### ISSUE THREAD

**Issue by reachfish** [brpc/brpc#612]
因为业务的需要，我们的服务器采用了异步模式，在service的响应函数中没有调用 done->Run()函数，而是在我们独立的业务线程（使用c++11的std::thread创建的）中调用 done->Run()。  这种使用业务线程来执行done，而不是brpc框架下的线程，会不会有些坑，要注意哪些问题 ？

**Comment by jamesge** [comment]
之所以server端也要有一个done，就是为了让用户在自己的event-loop或thread-pool中调用的，所以这么用是by design的。done里做的事情就是给client发response。这里需要注意的是入业务线程池时，不管是失败(满载了)还是成功，都要调用done。标记失败是调用controller.setfailed。

**Comment by reachfish** [comment]
@jamesge 非常感谢您的详细解答哈。还有个问题，在自己的业务流程中调用done和在brpc的线程中调用done， 这两者是否会有不一样的地方呢？  brpc框架中socket的收发流程本身很复杂， 在业务自己的线程里调done write socket,  会不会破坏socket的一些逻辑 ？

**Comment by jamesge** [comment]
不会，brpc的实现已经考虑了会在用户自己的线程中运行。
