### ISSUE TITLE
brpc新手，想用brpc做流计算的底层rpc，请给点建议怎么做，谢谢

### ISSUE THREAD

**Issue by deardeng** [brpc/brpc#614]
目标：底层rpc传递消息资源消耗尽量小，压测时单个计算节点吞吐量尽量高，处理消息的延时低。
期望解答：
1. 由于才调研brpc不久，想知道，这种类似单向代理clientA---> (serverB,clientB)--->serverC，B节点用brpc中的那种模式（同步，异步，半同步，streaming rpc）靠近目标？
2. 能否去掉brpc的rpc功能，只把它当作消息传递的框架？单纯的发一个消息到server端，但是server端并不需要回复数据给调用端，client端只管尽量的转发消息。

**Comment by jamesge** [comment]
1. serverB和clientB都用异步。
2. 不支持。

**Comment by deardeng** [comment]
@jamesge 那想自己修改brpc，支持2的话，工作量会不会非常大？

**Comment by jamesge** [comment]
不建议修改。“消息传递”一般并不意味着没有回复，而是会用批量发送来提高吞吐，没有回复必然拥塞。不妨考虑下先用现成的流式系统，也了解下它们的一些实现原理。

**Comment by deardeng** [comment]
好的，我先用异步模式写个demo测试一下性能。现成的流式系统，大多是java系的，对底层 消息处理 没有brpc中IO处理的这么好。

**Comment by deardeng** [comment]
@jamesge 请教一下，麻烦帮我看看，照猫画虎写的echo 异步中继服务器代码 有没有问题（按照session_data_and_thread_local 和 asynchronous_echo_c++，改的），希望给些建议，谢谢。

1. 用session_data_and_thread_local的client->server直接测试qps大约10w多。
2. 用session_data_and_thread_local的client->async_relay->server测得结果只有6.6w左右。
应该是我async_relay的代码写的有问题。请教，怎么改一下
[relay.txt](https://github.com/brpc/brpc/files/2740794/relay.txt)
![question](https://user-images.githubusercontent.com/3887565/50898735-0033ac80-144b-11e9-97a0-ba0c73705ea7.jpg)

**Comment by jamesge** [comment]
这是因为这儿的client都是同步压测的，延时高了，在相同的压力线程数下，qps肯定降了，把thread_num调多点试试

**Comment by jamesge** [comment]
另外这里server逻辑如果就是把收到的请求转发至下游server的话， 没什么必要启动一个线程来做这个事情，直接在service callback中写访问逻辑就行了。

**Comment by deardeng** [comment]
@jamesge  谢谢，ge大，我把client改成异步的，测了一下，qps加上中继没啥变化了。另去掉server的那个开启的thread，中继cpu压力也低了。
