### ISSUE TITLE
C++ rpc client访问异常，长连接找不到下游节点，短连接出现CLOSE_WAIT

### ISSUE THREAD

**Issue by cserken** [brpc/brpc#615]
**Describe the bug (描述bug)**
C++通过rpc client访问server
协议使用baidu_std/http
连接方式偿试过single/pooled/short
名字服务使用http://
当使用single或pooled连接方式时，运行一段时间出现"failed to select server"问题，导致请求下流失败
，偿试换成baidu_std和http协议，问题也一样
当使用short连接方式时，运行时，会出现几个连接CLOSE_WAIT的状态，再过一段时间，突然变成100个左右的CLOSE_WAIT状态的连接，设置的最大并发数为100，然后server返回E2004 max_concurrency的错误

**注：请求经过了marathon转发，即名字服务使用了marathon，经过几台机器，将请求转发到实际的server**

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: centos 7
Compiler:gcc 4.8
brpc: master
protobuf:2.4.1

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/5810937/50808168-4a783900-1338-11e9-896e-9449a1ccb8d6.png)

**Comment by cserken** [comment]
经过定位，发现进程中的一些work线程被read调用阻塞了，导致新请求触发max_concurrency错误，同时导致一些连接无法正常关闭而出现了CLOSE_WAIT状态.

**Comment by yqynju** [comment]
> 经过定位，发现应用代码中的发起的一些网络调用有问题，导至brpc的work线程被read调用阻塞了，从而新请求触发max_concurrency错误，同时导致一些连接无法正常关闭而出现了CLOSE_WAIT状态.

能详细展开一下不？感谢
