### ISSUE TITLE
ubuntu 编译

### ISSUE THREAD

**Issue by encrylife** [brpc/brpc#62]
brpc-master$ sh config_brpc.sh  --headers=/usr/local/lib  --libs=/usr/lib/ 这里两个参数是要指定什么，如果是jar包 是指的哪个 我系统里protoc --version libprotoc 2.5.0不知道这两个参数分别是什么路径，然后文档里也没有

**Comment by jamesge** [comment]
两个参数分别传什么文档中不是有示例么
 https://github.com/brpc/brpc/blob/master/docs/cn/getting_started.md
--headers是所有可能包含头文件的目录，--libs是所有可能包含静态库、动态库的目录

**Comment by encrylife** [comment]
Compiling client.o
client.cpp:18:27: fatal error: butil/logging.h: 没有那个文件或目录 这个是？

**Comment by encrylife** [comment]
当我修改了client.pp 路径改成了绝对路径 
#include </home/ubuntu/Downloads/brpc-master/src/butil/logging.h>
#include </home/ubuntu/Downloads/brpc-master/src/butil/time.h>
这时候又提示
Compiling client.o
In file included from client.cpp:20:0:
/home/ubuntu/Downloads/brpc-master/src/butil/logging.h:23:46: fatal error: butil/config.h: 没有那个文件或目录
 #include <butil/config.h>   // BRPC_WITH_GLOG
是不是路径有什么问题，C 这块我也不清楚

**Comment by jamesge** [comment]
要先编译后brpc目录后再去编译example目录下的。

**Comment by encrylife** [comment]
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
