### ISSUE TITLE
服务端是否可以支持消息有序处理

### ISSUE THREAD

**Issue by reachfish** [brpc/brpc#623]
对客户端发来的请求，服务端能不能支持有序处理，比如，对具有相同order Id字段的消息，服务端会按它们到达的次序顺序处理。 如果现在还没支持， 是否可以给一种修改的方法 ？ 我们想照着修改。麻烦戈总了 ~~

**Comment by jamesge** [comment]
server端无法假设Order Id不重不漏，如果只是简单"有序处理"，这里可能会出现活锁。具体处理方法和业务特性关系密切，是不可能在rpc层直接托管掉的。框架提供了[ExecutionQueue](https://github.com/brpc/brpc/blob/master/docs/cn/execution_queue.md)来提供基本的有序执行能力。

**Comment by reachfish** [comment]
好的，我先研究一下~  谢谢戈总 ！
