### ISSUE TITLE
[求教] brpc同一fd并发写和SSL_set_fd/SSL_write的配合问题

### ISSUE THREAD

**Issue by kevinis** [brpc/brpc#627]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
MesaLink是一个基于Rust语言实现的内存安全的TLS实现，最近我正在为brpc添加MeasLink的支持。

我在测试brpc_ssl_unittest.cpp的sanity测试用例时发现
https://github.com/brpc/brpc/blob/459387620f35209c8952f87d007e6efbca9b4da2/test/brpc_ssl_unittest.cpp#L121

在线程数大于1时，客户端和服务端的SSL_write都会写入错误数据，导致TLS会话解密错误。
我注意到Channel是线程间共享的，而Channel的Init方法生成了一个SSL_CTX插入了SocketMap。
https://github.com/brpc/brpc/blob/459387620f35209c8952f87d007e6efbca9b4da2/src/brpc/channel.cpp#L309-L312

我的问题是：
1. Channel和Socket和fd如何对应的？
2. Socket::SSLHandshake创建的SSLSession(即OpenSSL的SSL*)是否也是跨线程共享的？
3. 多线程共享同一个fd的话，SSL_set_fd是怎样解决的？

感谢指导！

**Describe the solution you'd like (描述你期望的解决方法)**
请求指点

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by old-bear** [comment]
1. Channel与Socket是n : 1，不同的Channel可能拥有相同的ChannelOption，那样就对应同一个Socket
2. ChannelOption里有SSLOption，所以SSL配置参数不一样的Channel，也会对应不同的Socket区分
3. 一个Socket对应一个SSL_CTX，一个Socket一个fd
4. SSLSession跨线程共享，在启动时会调用
https://github.com/brpc/brpc/blob/459387620f35209c8952f87d007e6efbca9b4da2/src/brpc/details/ssl_helper.cpp#L638-L649
5. 但是这并不意味着可以多线程同时去write，因为SSL read和write同样不保证原子，数据会交织在一起；需要外面自己保证（比如brpc内Socket的实现，就是保证一个writer，一个reader）
6. 那个SSL的ut，原版的build应该都是能pass的

**Comment by kevinis** [comment]
@old-bear  多谢指点！请您看下我的理解对不对。

以SSL的UT的sanity case为例
https://github.com/brpc/brpc/blob/1aeef03ce3c23e1f9ced301d52a1ead397157821/test/brpc_ssl_unittest.cpp#L89-L157

1 . 客户端NUM个线程共享一个Channel，这个Channel对应一个Socket、一个fd、和一个SSL_CTX*。
2. 这一个SSL_CTX*建立了一个SSL*赋给SSLSession。
3. 多个线程共用一个SSL*读同一个fd，靠brpc防止数据交织。

我还不清楚的是brpc是怎么防止数据交织的，我看到ssl_helper.cpp的CreateSSLSession函数调用SSL_set_app_data把SocketId保存在SSL里，和这个关系么？
https://github.com/brpc/brpc/blob/459387620f35209c8952f87d007e6efbca9b4da2/src/brpc/details/ssl_helper.cpp#L543

**Comment by xiongji** [comment]
这个是操作系统保证的吧，操作系统能保证同一台机器上不同的线程或进程使用相同的端口时，将数据送达对应的进程或线程

**Comment by kevinis** [comment]
搞定了，是MesaLink SSL线程不安全的bug，多谢！
