### ISSUE TITLE
fatal error: butil/reader_writer.h: No such file or directory

### ISSUE THREAD

**Issue by cswxin** [brpc/brpc#634]
Building brpc...
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/c++
-- Check for working CXX compiler: /usr/local/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found gflags: /usr/local/lib/libgflags.a
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found version "3.6.1") 
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1e") 
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread;-lpthread (found version "3.6.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/www/unit-dmkit-master/brpc/_build
[  1%] Generating brpc/streaming_rpc_meta.pb.h, brpc/streaming_rpc_meta.pb.cc
[  2%] Generating brpc/rtmp.pb.h, brpc/rtmp.pb.cc
[  2%] Generating idl_options.pb.h, idl_options.pb.cc
[  2%] Generating brpc/get_favicon.pb.h, brpc/get_favicon.pb.cc
[  2%] Generating brpc/rpc_dump.pb.h, brpc/rpc_dump.pb.cc
[  3%] Generating brpc/span.pb.h, brpc/span.pb.cc
Scanning dependencies of target BUTIL_LIB
Scanning dependencies of target OBJ_LIB
[  3%] Generating brpc/builtin_service.pb.h, brpc/builtin_service.pb.cc
[  3%] Generating brpc/get_js.pb.h, brpc/get_js.pb.cc
[  4%] Generating brpc/errno.pb.h, brpc/errno.pb.cc
[  4%] Generating brpc/options.pb.h, brpc/options.pb.cc
[  4%] Generating brpc/nshead_meta.pb.h, brpc/nshead_meta.pb.cc
[  5%] Generating brpc/policy/baidu_rpc_meta.pb.h, brpc/policy/baidu_rpc_meta.pb.cc
[  5%] Generating brpc/policy/hulu_pbrpc_meta.pb.h, brpc/policy/hulu_pbrpc_meta.pb.cc
[  5%] Generating brpc/policy/public_pbrpc_meta.pb.h, brpc/policy/public_pbrpc_meta.pb.cc
[  6%] Generating brpc/policy/sofa_pbrpc_meta.pb.h, brpc/policy/sofa_pbrpc_meta.pb.cc
[  6%] Generating brpc/policy/mongo.pb.h, brpc/policy/mongo.pb.cc
[  6%] Generating brpc/trackme.pb.h, brpc/trackme.pb.cc
Scanning dependencies of target PROTO_LIB
[  6%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/rtmp.pb.cc.o
[  6%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/rpc_dump.pb.cc.o
[  6%] Building CXX object CMakeFiles/PROTO_LIB.dir/idl_options.pb.cc.o
[  7%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/get_favicon.pb.cc.o
[  7%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/span.pb.cc.o
[  7%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/dmg_fp/g_fmt.cc.o
[  7%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/dmg_fp/dtoa_wrapper.cc.o
[  7%] Building C object src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/dynamic_annotations/dynamic_annotations.c.o
[  8%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/icu/icu_utf.cc.o
[  8%] Building C object src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/superfasthash/superfasthash.c.o
[  8%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/modp_b64/modp_b64.cc.o
[  8%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/collector.cpp.o
[  9%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/nspr/prtime.cc.o
[  9%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/symbolize/demangle.cc.o
[  9%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/builtin_service.pb.cc.o
[ 10%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/get_js.pb.cc.o
[ 10%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/symbolize/symbolize.cc.o
[ 10%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/errno.pb.cc.o
[ 11%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/snappy/snappy-sinksource.cc.o
[ 11%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/snappy/snappy-stubs-internal.cc.o
[ 11%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/snappy/snappy.cc.o
[ 12%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/third_party/murmurhash3/murmurhash3.cpp.o
[ 12%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/nshead_meta.pb.cc.o
[ 12%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/arena.cpp.o
[ 12%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/at_exit.cc.o
[ 13%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/options.pb.cc.o
[ 14%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/atomicops_internals_x86_gcc.cc.o
[ 14%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/policy/baidu_rpc_meta.pb.cc.o
[ 14%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/base64.cc.o
[ 14%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/big_endian.cc.o
[ 14%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/policy/hulu_pbrpc_meta.pb.cc.o
[ 14%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/cpu.cc.o
[ 14%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/default_variables.cpp.o
[ 15%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/debug/alias.cc.o
[ 15%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/debug/asan_invalid_access.cc.o
[ 15%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/debug/crash_logging.cc.o
[ 16%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/policy/public_pbrpc_meta.pb.cc.o
[ 17%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/debug/debugger.cc.o
[ 17%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/policy/sofa_pbrpc_meta.pb.cc.o
[ 17%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/debug/debugger_posix.cc.o
[ 17%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/debug/dump_without_crashing.cc.o
[ 17%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/policy/mongo.pb.cc.o
[ 18%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/debug/proc_maps_linux.cc.o
[ 18%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/debug/stack_trace.cc.o
[ 19%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/trackme.pb.cc.o
[ 19%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/debug/stack_trace_posix.cc.o
[ 19%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/streaming_rpc_meta.pb.cc.o
[ 20%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/environment.cc.o
[ 20%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/files/file.cc.o
[ 21%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/detail/percentile.cpp.o
[ 21%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/detail/sampler.cpp.o
[ 21%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/files/file_posix.cc.o
[ 22%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/files/file_enumerator.cc.o
[ 22%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/files/file_enumerator_posix.cc.o
[ 22%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/files/file_path.cc.o
[ 23%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/files/file_path_constants.cc.o
[ 23%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/files/memory_mapped_file.cc.o
[ 23%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/files/memory_mapped_file_posix.cc.o
[ 23%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/files/scoped_file.cc.o
[ 23%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/gflag.cpp.o
[ 24%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/files/scoped_temp_dir.cc.o
[ 24%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/file_util.cc.o
[ 24%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/file_util_posix.cc.o
[ 25%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/latency_recorder.cpp.o
[ 26%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/guid.cc.o
[ 26%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/guid_posix.cc.o
[ 26%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/hash.cc.o
[ 26%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/variable.cpp.o
[ 27%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/lazy_instance.cc.o
[ 27%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/location.cc.o
[ 27%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/md5.cc.o
[ 28%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/memory/aligned_memory.cc.o
[ 28%] Built target PROTO_LIB
[ 28%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/memory/ref_counted.cc.o
[ 28%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/memory/ref_counted_memory.cc.o
[ 29%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/memory/singleton.cc.o
[ 29%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/memory/weak_ptr.cc.o
[ 29%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/posix/file_descriptor_shuffle.cc.o
[ 30%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/posix/global_descriptors.cc.o
[ 30%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/process_util.cc.o
[ 30%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/rand_util.cc.o
[ 30%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/rand_util_posix.cc.o
[ 31%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/fast_rand.cpp.o
[ 31%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/safe_strerror_posix.cc.o
[ 31%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/sha1_portable.cc.o
[ 32%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/strings/latin1_string_conversions.cc.o
[ 32%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/strings/nullable_string16.cc.o
[ 32%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/strings/safe_sprintf.cc.o
[ 33%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/strings/string16.cc.o
[ 33%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/strings/string_number_conversions.cc.o
[ 33%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/strings/string_split.cc.o
[ 34%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/strings/string_piece.cc.o
[ 34%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/strings/string_util.cc.o
[ 34%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/strings/string_util_constants.cc.o
[ 35%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/strings/stringprintf.cc.o
[ 35%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/strings/utf_offset_string_conversions.cc.o
[ 35%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/strings/utf_string_conversion_utils.cc.o
[ 36%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/strings/utf_string_conversions.cc.o
[ 36%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/bthread.cpp.o
[ 36%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/synchronization/cancellation_flag.cc.o
[ 36%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/synchronization/condition_variable_posix.cc.o
[ 36%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/synchronization/waitable_event_posix.cc.o
[ 37%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/threading/non_thread_safe_impl.cc.o
[ 37%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/threading/platform_thread_posix.cc.o
[ 38%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/butex.cpp.o
[ 38%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/threading/simple_thread.cc.o
[ 39%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/threading/thread_checker_impl.cc.o
[ 39%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/threading/thread_collision_warner.cc.o
[ 39%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/threading/thread_id_name_manager.cc.o
[ 40%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/threading/thread_local_posix.cc.o
[ 40%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/threading/thread_local_storage.cc.o
[ 40%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/threading/thread_local_storage_posix.cc.o
[ 41%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/threading/thread_restrictions.cc.o
[ 41%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/threading/watchdog.cc.o
[ 41%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/time/clock.cc.o
[ 42%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/time/default_clock.cc.o
[ 42%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/time/default_tick_clock.cc.o
[ 42%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/time/tick_clock.cc.o
[ 43%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/time/time.cc.o
[ 43%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/time/time_posix.cc.o
[ 43%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/version.cc.o
[ 43%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/logging.cc.o
[ 43%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/condition_variable.cpp.o
[ 44%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/class_name.cpp.o
[ 44%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/errno.cpp.o
[ 44%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/find_cstr.cpp.o
[ 45%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/status.cpp.o
[ 45%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/string_printf.cpp.o
[ 45%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/context.cpp.o
[ 46%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/countdown_event.cpp.o
[ 46%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/errno.cpp.o
[ 46%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/execution_queue.cpp.o
[ 46%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/thread_local.cpp.o
[ 47%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/unix_socket.cpp.o
[ 47%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/endpoint.cpp.o
[ 47%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/fd_utility.cpp.o
[ 48%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/files/temp_file.cpp.o
[ 48%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/files/file_watcher.cpp.o
[ 48%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/time.cpp.o
[ 49%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/zero_copy_stream_as_streambuf.cpp.o
[ 49%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/crc32c.cc.o
[ 49%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/containers/case_ignored_flat_map.cpp.o
[ 50%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/iobuf.cpp.o
[ 50%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/popen.cpp.o
[ 50%] Building CXX object src/CMakeFiles/BUTIL_LIB.dir/butil/file_util_linux.cc.o
In file included from /opt/www/unit-dmkit-master/brpc/src/butil/iobuf.cpp:31:
/opt/www/unit-dmkit-master/brpc/src/butil/iobuf.h:31:10: fatal error: butil/reader_writer.h: No such file or directory
 #include "butil/reader_writer.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/BUTIL_LIB.dir/butil/iobuf.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 51%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/fd.cpp.o
[ 51%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/id.cpp.o
[ 51%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/interrupt_pthread.cpp.o
[ 51%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/key.cpp.o
[ 52%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/mutex.cpp.o
In file included from /opt/www/unit-dmkit-master/brpc/src/bthread/mutex.cpp:28:
/opt/www/unit-dmkit-master/brpc/src/butil/iobuf.h:31:10: fatal error: butil/reader_writer.h: No such file or directory
 #include "butil/reader_writer.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/OBJ_LIB.dir/bthread/mutex.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/BUTIL_LIB.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/OBJ_LIB.dir/all] Error 2
make: *** [all] Error 2

**Comment by jamesge** [comment]
master head是有这个文件的。

**Comment by cswxin** [comment]
unit-dmkit的deps.sh脚本checkout了2ae7f04ce513c6aee27545df49d5439a98ae3a3f版本
