### ISSUE TITLE
brpc server 主动断开连接

### ISSUE THREAD

**Issue by LittlePigIsKid** [brpc/brpc#636]
hi  brpc‘s deves，我的业务场景需要在http server 端主动断开连接，请问如何做到？ 比如现在服务端在组回包的时候要回的status-code是404，server要在回包后主动断开这个请求的连接

**Comment by LittlePigIsKid** [comment]
打扰各位，已经找到了。controller中的一个接口

**Comment by hongbshi** [comment]
我现在也在找brpc server端如何主动关闭连接, 想问下具体是在哪一块？

**Comment by ppzhoujun** [comment]
我也想知道 谁知道呀？

**Comment by chenBright** [comment]
Controller::CloseConnection
