### ISSUE TITLE
bthread并发问题

### ISSUE THREAD

**Issue by kenshinxf** [brpc/brpc#64]
场景如下:
1. Server是CPU密集型终端模块, 纯计算逻辑, 单个处理逻辑耗时大约500us-1000us.
2. Server提供批量接口, 一个批量(batch)请求包含N(5)个单独(single)请求, 每个single请求对应上面的一个处理逻辑, 消耗500us
3. Server为了降低平响, 并行化的处理这N个single请求, 即按照wiki中方式启动4个bthread, 本地运行一个bthread, 然后join, 合并结果后返回
4. CPU: 48, MEM: 128G, brpc_thread: 48左右

问题如下:
1. 用rpc_press进行压测, 发现随着时间变化, single请求的处理时间是恒定的(纯CPU处理, 时间很短, 500us左右), 但是主bthread线程join后等待的时间越来越长(即batch接口的总处理时间), 查看系统CPU占用率, 上升不是很明显, 不到总体的50% 但是主bthread线程总处理时间随着压测时间变得越来越长, 感觉像bthread队列(task_meta)在增大, pthread消耗不过来, 想请问/vars里面有地方可以统计bthread的队列总长度吗? 还有不知道可能的问题在哪里
2. 另外补充一点, 如果压力停了, 重启启动, 平响立刻降低, 然后重复上面的过程.
3. 现在的实现是每次RPC请求来了, 创建N-1个bthread并行运行任务, 准备改造成bthread线程池试试看, 不知道有没有效果

**Comment by jamesge** [comment]
先测试numactl绑核效果，以及结合https://github.com/brpc/brpc/blob/master/docs/cn/server_debugging.md排查

**Comment by kenshinxf** [comment]
经过测试和沟通, 发现是rpc_press工具设置的问题, rpc_press工具默认thread_num=1, 在QPS比较高的情况下, 可能有队列堆积, 所以看到的平响会缓缓上升, 设置thread_num=50后, 经过一晚上压测, 没有发现问题.
