### ISSUE TITLE
  brpc/example/http_c++ Failed to make on ubuntu14.04

### ISSUE THREAD

**Issue by tony-xiao** [brpc/brpc#65]
/usr/lib/x86_64-linux-gnu/libunwind.a(elf64.o): In function `xz_uncompressed_size':
/build/buildd/libunwind-1.1/src/elfxx.c:194: undefined reference to `lzma_stream_footer_decode'
/build/buildd/libunwind-1.1/src/elfxx.c:201: undefined reference to `lzma_index_buffer_decode'
/build/buildd/libunwind-1.1/src/elfxx.c:205: undefined reference to `lzma_index_size'
/build/buildd/libunwind-1.1/src/elfxx.c:210: undefined reference to `lzma_index_end'
/build/buildd/libunwind-1.1/src/elfxx.c:207: undefined reference to `lzma_index_uncompressed_size'
/build/buildd/libunwind-1.1/src/elfxx.c:210: undefined reference to `lzma_index_end'
/usr/lib/x86_64-linux-gnu/libunwind.a(elf64.o): In function `_Uelf64_extract_minidebuginfo':
/build/buildd/libunwind-1.1/src/elfxx.c:278: undefined reference to `lzma_stream_buffer_decode'
collect2: error: ld returned 1 exit status

**Comment by jamesge** [comment]
lzma is required by libunwind and should be installed separately.
