### ISSUE TITLE
Protoc Version 版本冲突，怎么解决？

### ISSUE THREAD

**Issue by XufengXufengXufeng** [brpc/brpc#661]
**Describe the bug (描述bug)**
这个错误之前几个issue里见过，但是只是说protoc版本冲突，就被关了。请问具体是怎么解决这个问题的？

Compiling src/mcpack2pb/generator.o
In file included from src/mcpack2pb/generator.cpp:27:0:
./src/idl_options.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
./src/idl_options.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
./src/idl_options.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from src/mcpack2pb/generator.cpp:27:0:
./src/idl_options.pb.h:23:35: fatal error: google/protobuf/arena.h: 没有那个文件或目录
compilation terminated.
Makefile:276: recipe for target 'src/mcpack2pb/generator.o' failed
make: *** [src/mcpack2pb/generator.o] Error 1

**To Reproduce (复现方法)**
按照getting_started.md安装，’Compile brpc with config_brpc.sh‘ 的第一个make报错。

**Expected behavior (期望行为)**
正常编译不报错。

**Versions (各种版本)**
OS: Ubuntu 16
Compiler: make
brpc: 
protobuf: 3.5.1

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
protoc和libprotobuf可能是两个包，protoc也可能被用户自定义path中的同名bin覆盖。排查掉一些基本的因素，再用包管理工具检查它们的版本是否一致，是否要更新到最新。

**Comment by XufengXufengXufeng** [comment]
不好意思，我找不到libprotobuf，find 和which都用了。protoc用which找到了，在我的anaconda bin里，不知道是不是我应该找的。没有了解过protobuf也对ubuntu文件管理系统不了解，只是想把这个brpc编译好，做其它事情。求讲的再具体些，@jamesge .

**Comment by XufengXufengXufeng** [comment]
这个错误我通过了，不知道是不是解决了，但是不再报了。

首先我使用：protoc --version 检查了我的protoc版本是3.5.1，然后我在[protobuf下载地址]( https://github.com/protocolbuffers/protobuf/releases)下载了c_++版protobuf。并按照[c++安装方法](https://github.com/protocolbuffers/protobuf/blob/master/src/README.md)安装来protobuf3.5.1，然后选择了系统内的protoc作为编译软件？输入`./configure --with-protoc=protoc`。 

然后我在做getting_started.md中的’Compile brpc with config_brpc.sh‘，就不会报’newer version of protoc‘错误了。现在在报Linking protoc-gen-mcpack过程中一大堆未定义的引用错误。我再开一个issue来问。

**Comment by drgnchan** [comment]
我是删掉了${DORIS_HOME}/thirdparty/src/brpc-1.4.0/doris_build文件夹后，再重新构建（bash build_thirdparty.sh）就通过了
