### ISSUE TITLE
编译example/echo_c++时出错

### ISSUE THREAD

**Issue by ehds** [brpc/brpc#669]
**Describe the bug (描述bug)**
编译example/echo_c++时出错

**To Reproduce (复现方法)**
在example/echo_c++下，make

**Versions (各种版本)**
OS: Manjora 18.0.2
Compiler: g++ 8.2.1
brpc:  0.9.5
protobuf: 3.6.1

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/17853449/53299158-e4a52980-3871-11e9-9fd8-9d66bf749744.png)

/usr/bin/ld: /home/ehds/Project/brpc-master/output/lib/libbrpc.a(global.o): in function `brpc::GlobalInitializeOrDieImpl()':
/home/ehds/Project/brpc-master/src/brpc/global.cpp:323: undefined reference to `SSL_library_init'
/usr/bin/ld: /home/ehds/Project/brpc-master/src/brpc/global.cpp:325: undefined reference to `SSL_load_error_strings'
/usr/bin/ld: /home/ehds/Project/brpc-master/output/lib/libbrpc.a(ssl_helper.o): in function `brpc::SSLThreadInit()':
/home/ehds/Project/brpc-master/src/brpc/details/ssl_helper.cpp:643: undefined reference to `CRYPTO_num_locks'
/usr/bin/ld: /home/ehds/Project/brpc-master/src/brpc/details/ssl_helper.cpp:644: undefined reference to `CRYPTO_set_locking_callback'
/usr/bin/ld: /home/ehds/Project/brpc-master/src/brpc/details/ssl_helper.cpp:646: undefined reference to `CRYPTO_THREADID_set_callback'
/usr/bin/ld: /home/ehds/Project/brpc-master/output/lib/libbrpc.a(ssl_helper.o): in function `brpc::SSLDHInit()':
/home/ehds/Project/brpc-master/src/brpc/details/ssl_helper.cpp:657: undefined reference to `get_rfc2409_prime_1024'
/usr/bin/ld: /home/ehds/Project/brpc-master/src/brpc/details/ssl_helper.cpp:680: undefined reference to `get_rfc3526_prime_2048'
/usr/bin/ld: /home/ehds/Project/brpc-master/src/brpc/details/ssl_helper.cpp:703: undefined reference to `get_rfc3526_prime_4096'
/usr/bin/ld: /home/ehds/Project/brpc-master/src/brpc/details/ssl_helper.cpp:726: undefined reference to `get_rfc3526_prime_8192'
/usr/bin/ld: /home/ehds/Project/brpc-master/output/lib/libbrpc.a(ssl_helper.o): in function `brpc::ExtractHostnames(x509_st*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)':
/home/ehds/Project/brpc-master/src/brpc/details/ssl_helper.cpp:213: undefined reference to `sk_num'
/usr/bin/ld: /home/ehds/Project/brpc-master/src/brpc/details/ssl_helper.cpp:215: undefined reference to `sk_value'
/usr/bin/ld: /home/ehds/Project/brpc-master/src/brpc/details/ssl_helper.cpp:225: undefined reference to `sk_pop_free'
/usr/bin/ld: /home/ehds/Project/brpc-master/output/lib/libbrpc.a(ssl_helper.o): in function `brpc::CreateClientSSLContext(brpc::ChannelSSLOptions const&)':
/home/ehds/Project/brpc-master/src/brpc/details/ssl_helper.cpp:444: undefined reference to `SSLv23_client_method'
/usr/bin/ld: /home/ehds/Project/brpc-master/output/lib/libbrpc.a(ssl_helper.o): in function `brpc::CreateServerSSLContext(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, brpc::ServerSSLOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)':
/home/ehds/Project/brpc-master/src/brpc/details/ssl_helper.cpp:473: undefined reference to `SSLv23_server_method'
/usr/bin/ld: /home/ehds/Project/brpc-master/output/lib/libbrpc.a(ssl_helper.o): in function `brpc::SSLGetThreadId(crypto_threadid_st*)':
/home/ehds/Project/brpc-master/src/brpc/details/ssl_helper.cpp:611: undefined reference to `CRYPTO_THREADID_set_numeric'
/usr/bin/ld: /home/ehds/Project/brpc-master/output/lib/libbrpc.a(dh.o): in function `brpc::policy::DHWrapper::do_initialize()':
/home/ehds/Project/brpc-master/src/brpc/policy/dh.cpp:94: undefined reference to `get_rfc2409_prime_1024'
/usr/bin/ld: /usr/local/lib64/libleveldb.a(table_builder.cc.o): in function `leveldb::port::Snappy_Compress(char const*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
table_builder.cc:(.text._ZN7leveldb4port15Snappy_CompressEPKcmPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN7leveldb4port15Snappy_CompressEPKcmPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x2b): undefined reference to `snappy::MaxCompressedLength(unsigned long)'
/usr/bin/ld: table_builder.cc:(.text._ZN7leveldb4port15Snappy_CompressEPKcmPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN7leveldb4port15Snappy_CompressEPKcmPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x6b): undefined reference to `snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)'
/usr/bin/ld: /usr/local/lib64/libleveldb.a(format.cc.o): in function `leveldb::port::Snappy_GetUncompressedLength(char const*, unsigned long, unsigned long*)':
format.cc:(.text._ZN7leveldb4port28Snappy_GetUncompressedLengthEPKcmPm[_ZN7leveldb4port28Snappy_GetUncompressedLengthEPKcmPm]+0x27): undefined reference to `snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)'
/usr/bin/ld: /usr/local/lib64/libleveldb.a(format.cc.o): in function `leveldb::port::Snappy_Uncompress(char const*, unsigned long, char*)':
format.cc:(.text._ZN7leveldb4port17Snappy_UncompressEPKcmPc[_ZN7leveldb4port17Snappy_UncompressEPKcmPc]+0x27): undefined reference to `snappy::RawUncompress(char const*, unsigned long, char*)'
collect2: 错误：ld 返回 1
make[2]: *** [CMakeFiles/echo_client.dir/build.make:118：echo_client] 错误 1
make[1]: *** [CMakeFiles/Makefile2:73：CMakeFiles/echo_client.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2

**Comment by ehds** [comment]
换了一下gflag的版本又重新编译了一下，可以通过了，braft也跑通了！

**Comment by loveDxq** [comment]
> 换了一下gflag的版本又重新编译了一下，可以通过了，braft也跑通了！

老兄，我和你一样的问题一样的系统和环境，你是用的哪个版本的gflags，是源码重新编译的吗

**Comment by ehds** [comment]
> > 换了一下gflag的版本又重新编译了一下，可以通过了，braft也跑通了！
> 
> 老兄，我和你一样的问题一样的系统和环境，你是用的哪个版本的gflags，是源码重新编译的吗

如果是Manjaro的话，sudo pacman -S gflags 就可以了，我之前是源码重新安装的，现在直接安装这些库也可以。

**Comment by loveDxq** [comment]
> > > 换了一下gflag的版本又重新编译了一下，可以通过了，braft也跑通了！
> > 
> > 
> > 老兄，我和你一样的问题一样的系统和环境，你是用的哪个版本的gflags，是源码重新编译的吗
> 
> 如果是Manjaro的话，sudo pacman -S gflags 就可以了，我之前是源码重新安装的，现在直接安装这些库也可以。

我问题解决了...有点狗血。系统lib和include里原本有一个openssl，但是在安装wps-office-cn后，系统又额外多安装了一个openssl-1.0。编译brpc的时候，config_brpc.sh脚本生成的config.mk的HDRS和LIBS路径都指向了openssl-1.0的版本。感觉应该是这个原因，我把config.mk的路径重新指向了include和lib路径下的openssl版本，重新编译brpc和example就没问题.......
