### ISSUE TITLE
bazel support

### ISSUE THREAD

**Issue by mapx** [brpc/brpc#67]
Is there any plan to support building the project with [bazel](http://bazel.io/), or would you accept third parties' contributions to make it?

Thanks :)

**Comment by jamesge** [comment]
PR is always welcome, especially those on adapting different OS/compiler/deps/building etc. Currently compilation brpc is still somewhat straightforward, you can have a try on building with bazel and send the PR to us.

**Comment by jamesge** [comment]
bazel is supported (with some known issues).
