### ISSUE TITLE
brpc 可以配合epoll使用么？

### ISSUE THREAD

**Issue by feng-y** [brpc/brpc#69]

**Comment by jamesge** [comment]
这两件事情不在一个层级上，brpc在linux下使用的就是epoll。

**Comment by E-HERO** [comment]
看一下baidu-rpc的源码就知道了，rpc就是用epoll来实现socket事件提醒的，在event_dispatcher里面

**Comment by feng-y** [comment]
可能没有说清楚，是想问现在使用了libev，想使用brpc，是想问brpc结合libev使用

**Comment by moxiami** [comment]
重新写个channel

**Comment by jamesge** [comment]
libev和rpc解决的是不同层面的问题，如果你原来是基于libev实现了类似于RPC的功能，改用brpc的接口重新实现就行了。

**Comment by jamesge** [comment]
reopen if you have further issues.
