### ISSUE TITLE
Link tcmalloc_and_profiler is not enough to enable cpu/heap profiler on ubuntu-16-04 LTS

### ISSUE THREAD

**Issue by duanmeng** [brpc/brpc#70]
**env**
>gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

**log**
* only link tcmalloc_and_profiler
```Makefile
STATIC_LINKINGS += -ltcmalloc_and_profiler -lbrpc
```
>Linking echo_client
g++ -L/usr/lib/x86_64-linux-gnu -L..//env/lib -Xlinker "-(" echo.pb.o client.o -Wl,-Bstatic -lgflags -lprotobuf -ltcmalloc_and_profiler -lbrpc -Wl,-Bdynamic -Xlinker "-)" -lpthread -lrt -lssl -lcrypto -ldl -lz -lleveldb -o echo_client
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libtcmalloc_and_profiler.a(stacktrace.o): In function `GetStackTraceWithContext_libunwind(void**, int, int, void const*)':
(.text+0x93): undefined reference to `_Ux86_64_getcontext'

* link libunwind & tcmalloc_and_profiler
```Makefile
STATIC_LINKINGS += -lunwind -ltcmalloc_and_profiler -lbrpc
```
>g++ -L/usr/lib/x86_64-linux-gnu -L..//env/lib -Xlinker "-(" echo.pb.o client.o -Wl,-Bstatic -lgflags -lprotobuf -lunwind -ltcmalloc_and_profiler -lbrpc -Wl,-Bdynamic -Xlinker "-)" -lpthread -lrt -lssl -lcrypto -ldl -lz -lleveldb -o echo_client
/usr/lib/x86_64-linux-gnu/libunwind.a(elf64.o): In function `xz_uncompressed_size':
/build/libunwind-VOtC4T/libunwind-1.1/src/elfxx.c:194: undefined reference to `lzma_stream_footer_decode'

**fix suggestion**
* link liblzma, libunwind & tcmalloc_and_profiler
```Shell
sudo apt-get install libunwind-dev # may be pre-installed by default
sudo apt-get install liblzma-dev
STATIC_LINKINGS += -lunwind -ltcmalloc_and_profiler -lbrpc
```

**Comment by jamesge** [comment]
Are you using the latest version of brpc? [config_brpc.sh](https://github.com/brpc/brpc/blob/master/config_brpc.sh#L263) uses ldd to test if libtcmalloc depends on libunwind and only statically link libtcmlloc when libunwind.a and liblzma.a (required by libunwind) are present. The issue you met is just that the program tries to statically link libtcmalloc without the 2 libs.

**Comment by duanmeng** [comment]
I use the latest version. It's my mistake not to include config.mk and install lzma, thanks a lot:)
