### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ly850918** [brpc/brpc#78]
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.

./src/bvar/detail/agent_group.h:144:35: error: no matching function
      for call to 'max'
            _s_tls_blocks->resize(std::max(block_id + 1, 32ul));
                                  ^~~~~~~~

**Comment by jamesge** [comment]
compiler/platform/deps etc

**Comment by jamesge** [comment]
reopen if you have further issues.
