### ISSUE TITLE
bthread切换开销多少？

### ISSUE THREAD

**Issue by tashanzhishi** [brpc/brpc#79]
cpu busy/idle 下的bthread切换，函数调用开销，pthread切换开销，大概是多少？
有测试结果吗？

**Comment by tashanzhishi** [comment]
经验结果也行

**Comment by jamesge** [comment]
* 切换性能有两个维度，一个是单次切换耗费的cpu，另一个是从发起到开始运行的延时，前者在bthread中不忙的时候和pthread类似（均值在3us左右），但越忙越低，这和work stealing的工作方式有关。后者起始值也是3us左右，越忙越高，因为任务越多，排队时间显然越长。
* 网络程序的整体性能主要取决第二个维度。一个反例是N:1线程库可以把前者做的很低(100-200ns)，但后者就会长很多（得挨个执行，不能并发）。目前的bthread主要是优化了后者。
* 函数的调用效率和切换没有直接关系，如果是RPC阻塞操作，那和实现质量关系更大。
* 同样的多线程代码运行在同样个数的bthread和pthread中时，一般bthread会更快。这个现象可以通过example中的多线程例子验证，client一般都有-use_bthread选项，打开运行在bthread中，否则pthread。但提高的原因不仅仅和切换有关，而是和很多因素有关，三言两语说不清楚了。

**Comment by tashanzhishi** [comment]
ok，明白了，多谢戈神。
