### ISSUE TITLE
关于bthread和golang协程的异同

### ISSUE THREAD

**Issue by Allen93** [brpc/brpc#80]
[这篇文档](https://github.com/brpc/brpc/blob/master/docs/cn/bthread.md) 中提到: 
>   Q：bthread是协程(coroutine)吗？
不是。我们常说的协程特指N:1线程库，即所有的协程运行于一个系统线程中，计算能力和各类eventloop库等价。由于不跨线程，协程之间的切换不需要系统调用，可以非常快(100ns-200ns)，受cache一致性的影响也小。但代价是协程无法高效地利

[参考这篇文章](http://morsmachine.dk/go-scheduler)  
go的goroutine也是M:N的线程实现并且也有stealing机制。 可否告知下和go的协程比较有合异同吗？ 

ps： 文档写的非常好，这几天看文档非常有收获。

**Comment by jamesge** [comment]
Duplicate of #45
