### ISSUE TITLE
brpc communicat mysql

### ISSUE THREAD

**Issue by seiyap70** [brpc/brpc#82]
Is there a good way to communicate brpc with MYSQL? Any suggestions?

**Comment by jamesge** [comment]
just use myclient

**Comment by seiyap70** [comment]
The mysql client library is not a mult-thread safe api. The brpc was used in mult-thread and bthread, it is really need to consider the multhread.

**Comment by jamesge** [comment]
Thread-safety is a specific problem that should be solved by the official client in principle. In common practices, you can use a connection pool (of mysql clients) to work around the issue. It's possible that brpc supports mysql's protocol directly as we've investigated before. However the priority is low and the ticket is suspended. If you're interested in extending brpc with the protocol by yourself, we could offer detailed suggestions. For example: a easier solution is to wrap libmysqlclient as part of the implementation.
