### ISSUE TITLE
brpc communicate with couchbase?

### ISSUE THREAD

**Issue by feng-y** [brpc/brpc#86]
Is there a good way to communicate brpc with couchbase? Any suggestions?

**Comment by jamesge** [comment]
using the official client?

**Comment by feng-y** [comment]
Currently official client support exists for
libuv (Windows and POSIX)
libev (POSIX)
libevent (POSIX)
select (Windows and POSIX)
IOCP (Windows Only)

Is there a good way to use brpc and couchbase both？Any suggestions?

**Comment by jamesge** [comment]
brpc does not prevent you from using dedicated threads running libevent + couchbase clients. It should simply work. This also applies to clients of other systems. brpc does not relate to these clients until users need more efficiencies, in which case, the protocol can be integrated into brpc directly for better experiences just like redis and memcached. But they're still a plus, not a must.
To support new protocols, read [this](https://github.com/brpc/brpc/blob/master/docs/cn/new_protocol.md)

**Comment by tjb1216** [comment]
麻烦在client文档中补充一下客户端的认证怎么扩展吧，要实现couchbase client需要用到认证功能，谢谢。

**Comment by jamesge** [comment]
现在有了：https://github.com/brpc/brpc/blob/master/docs/cn/client.md#认证
