### ISSUE TITLE
Ubuntu16.10 最后的链结失败: 输出不可表示的节

### ISSUE THREAD

**Issue by pangPython** [brpc/brpc#90]
cpu:intel-core-i3-7100
os:Ubuntu 16.10
err_info:
Linking protoc-gen-mcpack
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libgflags.a(gflags.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libgflags.a(gflags_reporting.cc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libgflags.a(gflags_completions.cc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: 最后的链结失败: 输出不可表示的节
collect2: error: ld returned 1 exit status
Makefile:197: recipe for target 'protoc-gen-mcpack' failed
make: *** [protoc-gen-mcpack] Error 1
make的时候的报错

**Comment by jamesge** [comment]
你这里的问题看起来是系统中没有libgflags.so，gcc会转而链接libgflags.a，而这个在编译时没有加-fPIC。如果是自己编译的gflags（看起来时），需要在configure时就指明要编译出libgflags.so（默认是只编.a）。如果是系统的（不太像），考虑重新安装gflags。

**Comment by nfjiffy** [comment]
我这边重新安装了libgflags，但是还是报以上错误
root@ubuntu:~/work/brpc# ls /usr/lib/x86_64-linux-gnu/libgflags.*
/usr/lib/x86_64-linux-gnu/libgflags.a   /usr/lib/x86_64-linux-gnu/libgflags.so.2
/usr/lib/x86_64-linux-gnu/libgflags.so  /usr/lib/x86_64-linux-gnu/libgflags.so.2.1.2

**Comment by jamesge** [comment]
你看看系统里有没有libgflags.so吧

**Comment by nfjiffy** [comment]
系统中有libgflags.so ，就是提示编译出错

**Comment by jamesge** [comment]
和libgflags.a在同一个目录下么？不在的话，可能是有问题的。

**Comment by nfjiffy** [comment]
在同一个啊，我现在又重现编译了一次，结果通过了，我昨晚试过很多次，都无法编译成功........一开始，我是从网上下载的libgflags，编译不过，最后自己使用源码编译，结果还是编译brpc还是失败，现在竟然成功了...

**Comment by jamesge** [comment]
修改依赖后要重新调用config_brpc.sh

**Comment by nfjiffy** [comment]
我想问问，您们这边是使用什么的IDE环境开发的哦，我刚刚将brpc代码迁移到了VS2013+Visual gdb，阅读代码，调试代码

**Comment by liaosimin** [comment]
搞掂了。一语中的。高

**Comment by Seafoodair** [comment]
我安装了libgflags.so，且跟libgflags.a同一个目录。编译的时候还会出现关于生成protoc-gen-mcpack失败的问题 。新手，求指导。
