### ISSUE TITLE
编译问题求指教

### ISSUE THREAD

**Issue by z572505258** [brpc/brpc#93]
在链接的时候出现下面的问题，gcc版本4.8.5
[ 23%] Built target press-client
[ 29%] Linking CXX executable mining-route-db-service
/usr/bin/ld: BFD version 2.20.51.0.2-5.43.el6 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

collect2: error: ld returned 1 exit status
make[2]: *** [mining-route-db-service] Error 1
make[2]: *** Deleting file `mining-route-db-service'
make[1]: *** [CMakeFiles/mining-route-db-service.dir/all] Error 2
make: *** [all] Error 2

**Comment by jamesge** [comment]
这个错误看起来似乎和rpc没什么关系
