### ISSUE TITLE
求教 ParallelChannel如何为每个 subchannel 指定关联的controller

### ISSUE THREAD

**Issue by Tsrign** [brpc/brpc#94]
看ParallelChannel示例，是将 controller 绑定到ParallelChannel上的，比如 http 服务，url 是绑定到 controller上的。
比如我想并发访问两个不同url，创建两个 SubChannel,  ParallelChannel该如何把这两个url分别绑定到两个SubChannel上，这个地方很迷惑。

**Comment by jamesge** [comment]
http在当前实现下用不了parallel channel，但可以用[半同步](https://github.com/brpc/brpc/blob/master/docs/cn/client.md#%E5%8D%8A%E5%90%8C%E6%AD%A5)

**Comment by Tsrign** [comment]
嗯嗯，多谢大神。

**Comment by better0001** [comment]
当前版本parallel channel支持http了吗？谢谢

> http在当前实现下用不了parallel channel，但可以用[半同步](https://github.com/brpc/brpc/blob/master/docs/cn/client.md#%E5%8D%8A%E5%90%8C%E6%AD%A5)
