### ISSUE TITLE
有没有一个详细介绍服务发现、服务注册、client/server配合的文档？

### ISSUE THREAD

**Issue by peacedog123** [brpc/brpc#96]
比如写好一个server并运行， 发布到naming service, 客户端请求这一整套流程；这个比基本的echo client/server复杂一些的，也更贴近实际生产环境的使用文档。
看了一圈doc，好像没有找到这样的文档。谢谢！

**Comment by jamesge** [comment]
这个流程本身是简单的。就是server启动后自动或手动挂载到名字服务中，“自动”指的是server调用名字服务的API，“手动”指的OP调用名字服务的命令行工具。client端应定期或被通知去扫描变动的名字服务，加入新增的机器，去除消失的机器。在请求时以某种负载均衡算法选择一台机器去访问。
具体做起来时，不同公司在名字服务这块花样会比较多，用文件列表，zookeeper，etcd，mysql，甚至redis。所以这块更多还是留给brpc的使用者自己去[定制](https://github.com/brpc/brpc/blob/master/docs/cn/load_balancing.md)了。

**Comment by peacedog123** [comment]
好的明白了，谢谢
