### ISSUE TITLE
将服务注册到类似Etcd注册中心的功能怎么扩展

### ISSUE THREAD

**Issue by kevin-xu-158** [brpc/brpc#97]

**Comment by kevin-xu-158** [comment]
现在在业务场景中需要整合Etcd进行服务的搭建，如何将服务注册到Etcd中，在brpc中如何扩展

**Comment by jamesge** [comment]
先看下#96了解下服务注册的一般流程。具体到etcd，server就是调用etcd的API或由OP操作etcd的工具来挂载到对应的目录下去。然后继承[brpc::NamingService](https://github.com/brpc/brpc/blob/master/src/brpc/naming_service.h)来把一个名字（目录名）映射为一堆机器的列表，这个ns可以用etcd作为前缀，比如channel.Init("etcd://DIRECTORY_NAME", "rr", &options);就能建立一个连接etcd下目录名为DIRECTORY_NAME的的channel。

**Comment by kevin-xu-158** [comment]
我继承了brpc::NamingService，实现了服务发现的功能，同时，也在server里增加了一个检测服务状态并且自动将服务注册到Etcd的功能，另外，我为工程也增加了CMakeLists.txt，代码还在不断完善中，等我测试差不多，就提交合并，到时候再请教您

**Comment by kevin-xu-158** [comment]
谢谢
