### ISSUE TITLE
jump_stack问题请教

### ISSUE THREAD

**Issue by moxiami** [brpc/brpc#99]
戈神：
jump_stack(cur_meta->stack, next_meta->stack)切meta任务后，会返回吗，切换后cur_meta还未结束吧？
切换next_meta后会调用task_runner是个循环中,其中会继续切换下一个new_meta,看起来像是迭代执行。
最后jump_stack返回，如果这个cur_meta执行bruex_wait操作，提前被唤醒，返回后会不会有问题？
求教

**Comment by moxiami** [comment]
如果有返回没看到寄存器切回到cur_meta的操作

**Comment by jamesge** [comment]
"如果这个cur_meta执行butex_wait操作，提前被唤醒", 这是不会的，只有**决定**唤醒一个bthread，它才会最终被跳转到。
